### ISSUE TITLE
new screenshot

### ISSUE THREAD

**Issue by jaredpalmer** [vercel/ai#1024]
<img width="1500" alt="Cover Github AI Server Components (1)" src="https://github.com/vercel/ai/assets/4060187/f21fa839-c710-4f09-9af4-2056f603d98f">

**Comment by lgrammel** [comment]
## Identify issue type

Identified as **None**  
Confidence: **High**

### Rationale
This appears to be an asset or bookkeeping task rather than a bug report, documentation request, example request, or product feature.

### Evidence
- The title only says “new screenshot.”
- The description contains a promotional image for AI SDK 3.0 and provides no requested product, documentation, or example change.
- There are no comments clarifying an actionable issue.
