### ISSUE TITLE
ai/rsc layout example from document might incorrect?

### ISSUE THREAD

**Issue by himself65** [vercel/ai#1033]
### Description

https://sdk.vercel.ai/docs/concepts/ai-rsc#connect-to-the-airsc-instance-from-the-client

```tsx
import { AI } from 'ai/rsc';
 
export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <AI>
          {children}
        </AI>
      </body>
    </html>
  )
}
```

I didn't see AI in `ai/rsc` package.

<img width="574" alt="image" src="https://github.com/vercel/ai/assets/14026360/ca4412f1-ce16-411e-a35f-e010839abaad">

**Comment by himself65** [comment]
https://github.com/vercel/ai/blob/f0e9dcf96a6c3f65f4357d5656a16e4fab56bb35/examples/next-ai-rsc/app/layout.tsx#L8

**Comment by MaxLeiter** [comment]
Thanks, you're supposed to create it yourself with `createAI`. Fix incoming

**Comment by himself65** [comment]
so fast, thank u

**Comment by lgrammel** [comment]
## Identify issue type

Identified as **Documentation**  
Confidence: **High**

### Rationale
The reported problem is an incorrect documentation snippet that references a nonexistent export; resolving it requires correcting the docs rather than changing SDK behavior.

### Evidence
- The documentation imports `AI` from `ai/rsc`, but TypeScript reports that the module has no exported member `AI`.
- A maintainer confirmed users must create `AI` themselves with `createAI` and stated that a fix was incoming.
