### ISSUE TITLE
createStreamableUI.append only appends on the last node

### ISSUE THREAD

**Issue by tom-sherman** [vercel/ai#1038]
### Description

Calling streamable.update() won't append unless it's immediately followed by streamable.done(). This has the effect that append can't actually append unless you have the use case of two nodes.

### Code example

```tsx
export default function Home() {
  const streamable = createStreamableUI();

  setTimeout(() => {
    streamable.append(<p>Foo</p>);
    setTimeout(() => {
      streamable.append(<p>Bar</p>);
    }, 1000);
  }, 1000);

  return streamable.value;
}
```

### Additional context

Reproduction: https://github.com/tom-sherman/vercel-ai-stream-ui-append-bug

**Comment by lgrammel** [comment]
## Identify issue type

Identified as **Bug**  
Confidence: **High**

### Rationale
This describes a concrete failure in the existing `createStreamableUI.append` API rather than requesting a new capability.

### Evidence
- The report gives a concrete reproduction where successive `createStreamableUI().append()` calls fail to render all appended nodes.
- It states that appending only works when immediately followed by `done()`, making the existing `append` behavior incorrect for more than two nodes.
- A reproduction repository is provided.
