### ISSUE TITLE
AssistantResponse documentation page could not be found

### ISSUE THREAD

**Issue by tomatac** [vercel/ai#1042]
### Description

This link [assistant-response](https://sdk.vercel.ai/docs/api-reference/assistant-response)
https://sdk.vercel.ai/docs/api-reference/assistant-response
returns a 404 error

**Comment by gusfraser** [comment]
You may be looking for this; it's experimental: https://sdk.vercel.ai/docs/api-reference/providers/assistant-response

**Comment by tomatac** [comment]
Thank you! 
There is another page that does not work. That maybe the same content.
<img width="162" alt="image" src="https://github.com/vercel/ai/assets/15964070/3704df5b-e1c4-467a-9290-ef2256cea35b">

**Comment by tomatac** [comment]
@gusfraser, this link works:
https://sdk.vercel.ai/docs/api-reference/providers/assistant-response
Thank you!
@shuding, there were 2 menu items for assistant-response, one was not in the right location and it worked and one was in the correct location but did not work (returned 404).
The fix just eliminated the link that worked.
This link (called from the menu):
https://sdk.vercel.ai/docs/api-reference/assistant-response
still returns 404 and does auto refresh in an infinite cycle

**Comment by lgrammel** [comment]
## Identify issue type

Identified as **Documentation**  
Confidence: **High**

### Rationale
The issue concerns an incorrect documentation navigation link and missing API reference route, so it requires a documentation correction rather than an SDK behavior change.

### Evidence
- The documented AssistantResponse API reference URL returns a 404.
- A working page exists at `/docs/api-reference/providers/assistant-response`, but the documentation menu links to the broken `/docs/api-reference/assistant-response` path.
- The reporter says the broken menu link also triggers an infinite auto-refresh cycle.
