### ISSUE TITLE
docs/ai-rsc: model gpt-4-turbo does not exist

### ISSUE THREAD

**Issue by alonzuman** [vercel/ai#1048]
### Description

Simply copying & pasting the example from concepts/generative-ui uses the `gpt-4-turbo` model which doesn't exist, should be updated to either `gpt-4-0125-preview` which is the latest gpt-4-turbo checkpoint.

```json
  error: {
    message: 'The model `gpt-4-turbo` does not exist',
    type: 'invalid_request_error',
    param: null,
    code: 'model_not_found'
  },
```

**Comment by MaxLeiter** [comment]
Thanks!

**Comment by lgrammel** [comment]
## Identify issue type

Identified as **Documentation**  
Confidence: **High**

### Rationale
This is a correction to sample code embedded in the documentation, rather than a change to AI SDK behavior or a standalone example project.

### Evidence
- The generative UI documentation example uses `gpt-4-turbo`, which produced a `model_not_found` error when copied and run.
- The reporter asks to update the documented model name to the valid `gpt-4-0125-preview` checkpoint.
