### ISSUE TITLE
Selecting a Date Range in the stock action UI crashes the application 

### ISSUE THREAD

**Issue by athrael-soju** [vercel/ai#1056]
### Description

Simply click "What's the stock price of AAPL?" from one of the options and try to adjust the date range.

### Code example

The error happens due to the change done [here](https://github.com/vercel/ai/commit/1860d529be30278a23c261ba278fcf7e19935bd5#diff-a423f9c0ef33a7edcde03f2c5a68b7fb90b6fee29e3ace21925bbb8d6e67d7d6R57) which causes an infinite loop within useEffect

reverting back to `  }, [startHighlight, endHighlight]);` should have the desired effect

**Comment by athrael-soju** [comment]
https://github.com/vercel/ai/pull/1073

**Comment by shuding** [comment]
Closed by #1073

**Comment by lgrammel** [comment]
## Identify issue type

Identified as **Bug**  
Confidence: **High**

### Rationale
This is a concrete failure in existing UI behavior, traced to an infinite render loop and resolved with a code fix.

### Evidence
- Adjusting the stock action UI's date range causes the application to crash due to an infinite useEffect loop.
- The issue identifies a regressing commit and proposes restoring safer dependencies and functional state updates.
- A corrective pull request, #1073, was approved and closed the issue.
