### ISSUE TITLE
Following the steps in https://sdk.vercel.ai/docs/concepts/ai-rsc results in multiple build errors

### ISSUE THREAD

**Issue by nickdobos** [vercel/ai#1063]
### Description

Do this exactly:

https://sdk.vercel.ai/docs/concepts/ai-rsc

### Code example

Following the steps here:
https://sdk.vercel.ai/docs/concepts/ai-rsc

Results in this error:
![CleanShot 2024-03-03 at 10 05 48@2x](https://github.com/vercel/ai/assets/4662442/eb734b27-de70-48ff-9ee7-7b7d742ffabd)

**Comment by nickdobos** [comment]
Fixed!
https://x.com/shuding_/status/1764368862013792445?s=20

**Comment by lgrammel** [comment]
## Identify issue type

Identified as **Documentation**  
Confidence: **High**

### Rationale
The report identifies broken or incomplete code in a documentation guide, requiring a docs correction rather than a product behavior change.

### Evidence
- Following the AI RSC documentation exactly produced a runtime ReferenceError: “UserMessage is not defined.”
- The failing code was copied from a documentation guide rather than a standalone example project.
- The reporter later confirmed the issue was fixed.
