### ISSUE TITLE
Parameters are returned as string when `tools` is used

### ISSUE THREAD

**Issue by jeremyphilemon** [vercel/ai#1093]
### Description

Using the `tools` field returns parameters as string. Instead, it should return the type as mentioned in the zod schema. Using the `functions` field works as intended and can be a temporary workaround.

### Code example

```typescript
import { render } from 'ai/rsc'
import OpenAI from 'openai'
import { z } from 'zod'

const openai = new OpenAI()

async function submitMessage(userInput) { // 'What is the weather in SF?'
  'use server'

  return render({
    provider: openai,
    model: 'gpt-3.5-turbo,
    messages: [
      { role: 'system', content: 'You are a helpful assistant' },
      { role: 'user', content: userInput }
    ],
    text: ({ content }) => <p>{content}</p>,

    // "tools" returns a string while "functions" returns the object
    tools: {
      get_city_weather: {
        description: 'Get the current weather for a city',
        parameters: z.object({
          city: z.string().describe('the city')
        }).required(),
        render: async function* ({ city }) {
          yield <Spinner/>
          const weather = await getWeather(city)
          return <Weather info={weather} />
        }
      }
    }
  })
}
```

### Additional context
- Reproduced with ai@3.0.4

**Comment by valstu** [comment]
Related issue: https://github.com/vercel/ai/issues/1026

**Comment by jeremyphilemon** [comment]
@valstu ah didn't realize an issue was already open – will close this in favor of that!

**Comment by lgrammel** [comment]
## Identify issue type

Identified as **Bug**  
Confidence: **High**

### Rationale
This is a concrete report of incorrect runtime behavior in the existing `tools` API. Its duplicate status does not change the underlying issue type.

### Evidence
- With `ai@3.0.4`, tool parameters are reportedly passed to `render` as a string instead of the object defined by the Zod schema.
- The deprecated/alternative `functions` field reportedly returns the expected object, indicating inconsistent existing behavior.
- The reporter later identified issue #1026 as a duplicate and closed this issue in its favor.
