### ISSUE TITLE
experimental_AssistantResponse link in docs is unreachable

### ISSUE THREAD

**Issue by maxxxymum** [vercel/ai#1096]
### Description

Click `experimental_AssistantResponse` link in API refferrence in documentation. The link doesn't work, route doesn't change. There is no visual feedback. There are no errors in Devtools console.

**Comment by conroywhitney** [comment]
@maxxxymum -- here's the URL where those docs now live: https://sdk.vercel.ai/docs/api-reference/assistant-response

@MaxLeiter @shuding -- Can we re-build the left nav for all the pages? (or maybe that requires rebuilding all  the pages?)

It looks like the links are correct on the index (https://sdk.vercel.ai/docs) but are broken on other pages (e.g., https://sdk.vercel.ai/docs/getting-started)

You can see broken left-nav links for both:

 * `experimental_AssistantResponse` (path: `docs/pages/docs/api-reference/assistant-response.mdx`), which was moved in https://github.com/vercel/ai/pull/1086, as well as for
 * `Hugging Face` (path: `docs/pages/docs/guides/providers/huggingface.mdx`) which I moved in https://github.com/vercel/ai/pull/1085

**Comment by tchanxx** [comment]
+1 I am seeing the link stuck in a refreshing 404 loop.

https://github.com/vercel/ai/assets/46210938/60994a6b-a461-497b-ac7d-ed25ab44f44f

**Comment by lgrammel** [comment]
## Identify issue type

Identified as **Documentation**  
Confidence: **High**

### Rationale
This is a broken link/navigation issue within the documentation site, requiring correction or rebuilding of documentation navigation rather than an AI SDK product behavior change.

### Evidence
- The API reference navigation link for `experimental_AssistantResponse` does not open the page and can enter a 404 refresh loop.
- A maintainer confirmed stale navigation links caused by documentation caching/rebuild issues and supplied the correct page URL.
