### ISSUE TITLE
Task timed out after 300.01 seconds using the experimental_useAssistant 

### ISSUE THREAD

**Issue by marcolivierbouch** [vercel/ai#1098]
### Description

Im getting many errors using the vercel/ai sdk "Task timed out after 300.01 seconds" with the assistant api. Is there a way to stop gettings timeout in vercel even with a 300 seconds limit?

### Code example

Client side code: https://github.com/marcolivierbouch/OpenAssistantGPT/blob/main/chatbotjs/src/Chat.tsx 
Server side code: https://github.com/marcolivierbouch/OpenAssistantGPT/blob/main/app/api/chatbots/%5BchatbotId%5D/chat/route.ts

**Comment by marcolivierbouch** [comment]
![unnamed](https://github.com/vercel/ai/assets/29548847/5cdea2be-ee36-458e-9820-54dcb56d4b7e)

**Comment by marcolivierbouch** [comment]
Hi @shuding, thanks for anwsering we can stream response with  the experimental_useAssistant  ?

**Comment by lgrammel** [comment]
## Identify issue type

Identified as **None**  
Confidence: **High**

### Rationale
This is primarily a deployment/runtime support question, with possible upstream OpenAI service impact, rather than a demonstrated AI SDK defect or a concrete request to change the SDK.

### Evidence
- The reported error occurs when a Vercel Node.js function reaches its 300-second execution limit.
- A maintainer recommends using the Edge runtime for streaming without the same duration limit.
- The attached status notice reports elevated failed or stuck runs in OpenAI's Assistants API.
- The follow-up asks whether `experimental_useAssistant` can stream responses.
