### ISSUE TITLE
Function calling support for Anthropic models

### ISSUE THREAD

**Issue by AWKohler** [vercel/ai#1103]
### Feature Description

Add function calling support for anthropic's claude 3 models

### Use Case

For using functions with Anthropic's new function call supporting models.

**Comment by nabilfatih** [comment]
yess please :)

**Comment by alex-cortenix** [comment]
Subscribed.

**Comment by chanmathew** [comment]
Yes!

**Comment by lgrammel** [comment]
The AI SDK Core Anthropic provider supports function calls: https://sdk.vercel.ai/providers/ai-sdk-providers/anthropic

**Comment by lgrammel** [comment]
## Identify issue type

Identified as **Feature**  
Confidence: **High**

### Rationale
This is a request for new provider capability, later confirmed as implemented, rather than a report of broken existing behavior.

### Evidence
- The description explicitly requests adding function-calling support for Anthropic Claude 3 models.
- The maintainer later confirms that the AI SDK Core Anthropic provider supports function calls and links to the provider documentation.
