### ISSUE TITLE
hugging-face provider document not accessed

### ISSUE THREAD

**Issue by fport** [vercel/ai#1112]
### Description

hugging-face provider document not accessed => https://sdk.vercel.ai/docs/guides/providers/hugging-face

**Comment by CollComm** [comment]
Issue observed is identical to the one described; merged with https://github.com/vercel/ai/issues/1115

**Comment by lgrammel** [comment]
There is a type in the URL, the correct URL is https://sdk.vercel.ai/docs/guides/providers/huggingface

**Comment by lgrammel** [comment]
## Identify issue type

Identified as **None**  
Confidence: **High**

### Rationale
This is primarily a support/duplicate report caused by an incorrect URL, with no documented request to change the SDK or its documentation.

### Evidence
- The reported URL uses an incorrect `hugging-face` path.
- A maintainer supplied the working `huggingface` URL, indicating the problem was a typo rather than inaccessible documentation.
- A comment notes the report was merged with issue #1115.
