### ISSUE TITLE
Render supporting google vertex provider

### ISSUE THREAD

**Issue by Godrules500** [vercel/ai#1198]
### Feature Description

I just upgraded to use the ai/rsc when I realized render only uses open ai. Are there plans to switch this to use google's vertex ai as a provider?

**Comment by lgrammel** [comment]
Duplicates #1269

**Comment by lgrammel** [comment]
## Identify issue type

Identified as **Feature**  
Confidence: **High**

### Rationale
This requests new provider support rather than reporting broken or incorrect existing behavior. The duplicate note does not change the underlying request type.

### Evidence
- The requester asks for Google Vertex AI provider support in AI/RSC rendering, which is a new provider capability.
- The maintainer notes that the issue duplicates #1269; no current behavioral failure is described.
