### ISSUE TITLE
Error: failed to pipe response

### ISSUE THREAD

**Issue by sagar-vaghela** [vercel/ai#1203]
### Description

First of all, let me be clear that I am not using open ai api, instead I am using a third party keywordsai[https://keywordsai.co/]

### Code example

import { OpenAIStream, StreamingTextResponse } from "ai";

import { NextRequest, NextResponse } from "next/server";

export async function POST(req: NextRequest) {
  try {
    const { prompt } = await req.json();

    const res = await fetch("https://api.keywordsai.co/api/chat/completions", {
      method: "POST",
      headers: {
        Authorization: `Bearer ${process.env.KEYWORDSAI_API_KEY}`,
        "Content-Type": "application/json; charset=UTF-8",
      },
      body: JSON.stringify({
        messages: [
          {
            role: "user",
            content: prompt,
          },
        ],
        stream: true,
        model: "gpt-3.5-turbo",
      }),
    });

    const stream = OpenAIStream(res);
    return new StreamingTextResponse(stream);
  } catch (error) {
    console.error(error);
    return NextResponse.json(
      { error: "Internal server error" },
      { status: 500 },
    );
  }
}

### Additional context

It was working fine without ai package

**Comment by GauravBurande** [comment]
Is there a fix for this problem in the latest version of vercel ai SDK?

**Comment by lgrammel** [comment]
Closing since we have moved to a new architecture in 3.1

**Comment by lgrammel** [comment]
## Identify issue type

Identified as **Bug**  
Confidence: **Medium**

### Rationale
The issue reports a concrete runtime failure in the SDK’s response-streaming behavior, although it involves a third-party OpenAI-compatible endpoint and lacks detailed diagnostics.

### Evidence
- Using `OpenAIStream(res)` with a streaming chat-completions response results in “failed to pipe response.”
- The reporter states the streaming flow worked without the AI SDK package.
- A maintainer later closed the issue because the SDK moved to a new architecture in version 3.1, without identifying a usage error.
