### ISSUE TITLE
useChat is not stream

### ISSUE THREAD

**Issue by Ezreal09** [vercel/ai#1208]
### Description

the next-openai demo ，this case is not streaming output,I found that ai will always wait until all information is completed and return it together

### Code example

https://github.com/vercel/ai/blob/main/examples/next-openai/app/page.tsx

**Comment by MaxLeiter** [comment]
Hi, can you please share more information like your next.js and node.js versions? The demo works fine for me.

**Comment by lgrammel** [comment]
Please check this out: https://sdk.vercel.ai/docs/troubleshooting/common-issues/streaming-not-working-on-vercel

**Comment by lgrammel** [comment]
## Identify issue type

Identified as **Bug**  
Confidence: **Medium**

### Rationale
This reports a concrete failure of expected `useChat` streaming behavior, although the cause and reproducibility are not established.

### Evidence
- The reporter says the `next-openai` demo waits for the full response instead of streaming incrementally.
- A maintainer could not reproduce the behavior and requested environment/version details.
- Another maintainer linked troubleshooting guidance for streaming failures on Vercel.
