### ISSUE TITLE
Dark mode support

### ISSUE THREAD

**Issue by CerxMe** [vercel/ai#122]
Add dark mode pls your docs are burning my eyes.

**Comment by amxv** [comment]
i love the ai sdk but my eyes don't :/

pls add dark mode guys

**Comment by lgrammel** [comment]
Dark mode is now available (switch in bottom right corner)

**Comment by lgrammel** [comment]
## Identify issue type

Identified as **Feature**  
Confidence: **High**

### Rationale
This is a request for a new documentation-site capability rather than a correction to documentation content or a failure of existing behavior.

### Evidence
- The issue requests a new dark mode capability for the documentation site.
- A maintainer confirmed dark mode was later added via a switch in the bottom-right corner.
