### ISSUE TITLE
Support toolChoice in streamText, generateText, streamUI

### ISSUE THREAD

**Issue by hinderberg** [vercel/ai#1254]
### Feature Description

Render does not have the tool_choice prop available, making forcing a specific tool of choice impossible, making all calls using auto which is the default. 

### Use Case

Forcing the model to call a specific tool constantly and ensuring the tool is called every time. It works better than trying to force it through a prompt.

**Comment by someguy9** [comment]
Would love this too

**Comment by blechatellier** [comment]
@lgrammel thanks, this can't be used with multiple tools though, right?

**Comment by tarunamasa** [comment]
I feel like this is an incredibly necessary use case.

**Comment by lgrammel** [comment]
https://github.com/vercel/ai/pull/1718

**Comment by lgrammel** [comment]
## Identify issue type

Identified as **Feature**  
Confidence: **High**

### Rationale
This requests a new API capability for controlling tool selection and does not describe a failure of documented existing behavior.

### Evidence
- The issue explicitly requests adding a `toolChoice` option to `streamText`, `generateText`, and `streamUI`.
- The requested capability would allow selecting and forcing a specific tool instead of using the existing automatic selection.
- A maintainer linked PR #1718 in response, indicating work toward the requested enhancement.
