### ISSUE TITLE
handling errors in the streaming response

### ISSUE THREAD

**Issue by avianion** [vercel/ai#1266]
### Description

When handling errors in the stream, it breaks the entire stream and gives an error coming. 

Is there a better way to do this?

Because it removes the ability to retry and just ends up in a user facing error.

### Code example

error

**Comment by lgrammel** [comment]
Can you share the code / function that is causing this?

**Comment by lgrammel** [comment]
## Identify issue type

Identified as **None**  
Confidence: **High**

### Rationale
This is an incomplete support question rather than a concrete, reproducible bug report or a clear request for a product change.

### Evidence
- The report asks generally how to handle streaming errors but provides no code, function, reproduction steps, or specific SDK behavior.
- A maintainer requested the missing code/function details, and no further clarification is included.
