### ISSUE TITLE
Google Vertex AI provider tool calling

### ISSUE THREAD

**Issue by goodrules** [vercel/ai#1269]
### Feature Description

Currently, only the consumer APIs are available via @google/generative-ai-js for Gemini.  Would like to include access to the Vertex SDK for the GCP endpoints for Gemini via https://github.com/googleapis/nodejs-vertexai.

### Use Case

Developers wanting to leverage their GCP resources to build with Vercel.

**Comment by williamsmt** [comment]
#863 seemed to introduce this but closed?

**Comment by lgrammel** [comment]
Basic provider (no tool calls / gen ui): https://sdk.vercel.ai/providers/ai-sdk-providers/google-vertex

**Comment by lgrammel** [comment]
https://github.com/vercel/ai/pull/1775

**Comment by lgrammel** [comment]
## Identify issue type

Identified as **Feature**  
Confidence: **High**

### Rationale
This requests expanded provider capability—Google Vertex AI support with tool calling—rather than reporting broken existing behavior.

### Evidence
- The issue requests access to Gemini through Google Vertex AI/GCP endpoints, beyond the existing consumer API provider.
- A maintainer noted that a basic Google Vertex provider existed but lacked tool calls/generative UI, and linked a subsequent implementation PR.
