### ISSUE TITLE
TS Error: Argument of type 'EventStream<ChatCompletions>' is not assignable to parameter of type 'Response | AsyncIterableOpenAIStreamReturnTypes'.

### ISSUE THREAD

**Issue by aalhayali** [vercel/ai#1271]
### Description

When setting up the SDK with Azure OpenAI, I'm facing the following TS error:
```
Argument of type 'EventStream<ChatCompletions>' is not assignable to parameter of type 'Response | AsyncIterableOpenAIStreamReturnTypes'.
  Type 'EventStream<ChatCompletions>' is not assignable to type 'AsyncIterable<AzureChatCompletions>'.
    The types returned by '[Symbol.asyncIterator]().next(...)' are incompatible between these types.
      Type 'Promise<IteratorResult<ChatCompletions, any>>' is not assignable to type 'Promise<IteratorResult<AzureChatCompletions, any>>'.
        Type 'IteratorResult<ChatCompletions, any>' is not assignable to type 'IteratorResult<AzureChatCompletions, any>'.
          Type 'IteratorYieldResult<ChatCompletions>' is not assignable to type 'IteratorResult<AzureChatCompletions, any>'.
            Type 'IteratorYieldResult<ChatCompletions>' is not assignable to type 'IteratorYieldResult<AzureChatCompletions>'.
              Type 'ChatCompletions' is not assignable to type 'AzureChatCompletions'.
```

### Code example

My code is an exact copy from what's written in the [documentation](https://sdk.vercel.ai/docs/guides/providers/azure-openai).

### Additional context

Here are the package versions I'm using:
```
    "@azure/openai": "1.0.0-alpha.20240403.1",
    "ai": "^3.0.17",
```

**Comment by adamhockemeyer** [comment]
Same issue. I changed to` "@azure/openai": "^1.0.0-beta.11"` and it resolved.

**Comment by sethcarlton** [comment]
This is breaking again in `"@azure/openai": "^1.0.0-beta.12"`

**Comment by toonverbeek** [comment]
Also running into this using `"@azure/openai": "^1.0.0-beta.12"` and `"ai": "3.0.35"`.

**Comment by alexknipfer** [comment]
> This is breaking again in `"@azure/openai": "^1.0.0-beta.12"`

I'm seeing the same, on beta 12 and seeing this type error.

**Comment by lgrammel** [comment]
## Identify issue type

Identified as **Bug**  
Confidence: **High**

### Rationale
This is a concrete interoperability/type compatibility failure in the existing Azure OpenAI integration, including code presented by the SDK documentation, rather than a request for new capability.

### Evidence
- Code copied from the Azure OpenAI documentation produces a TypeScript incompatibility between `EventStream<ChatCompletions>` and the stream types accepted by the AI SDK.
- Downgrading `@azure/openai` to beta.11 reportedly resolves the error, while beta.12 and the newer alpha reproduce it.
- Multiple commenters confirm the same type error with supported AI SDK 3.0.x versions.
