### ISSUE TITLE
Expressjs: Allow streamToResponse to send back custom data in response body

### ISSUE THREAD

**Issue by Banhawy** [vercel/ai#1285]
### Feature Description

I am using React ^18.2.0 and Express ^4.19.2 and openai as the ai provider. I am proposing the addition of a feature that allows the streamToResponse function to send back custom data in the response body. Currently, the streamToResponse function only supports streaming LLM response directly from the AI provider to the client with the ability to modify only the response headers and status.
```js
/**
 * A utility function to stream a ReadableStream to a Node.js response-like object.
 */
declare function streamToResponse(res: ReadableStream, response: ServerResponse, init?: {
    headers?: Record<string, string>;
    status?: number;
}): void;
``` 

However, there are use cases where it would be beneficial to include additional custom data in the response **body**. 

This option is available in the [similar function](https://sdk.vercel.ai/docs/api-reference/stream-to-response) `experimental_StreamingReactResponse`  where you can send custom data in the body.  
```js
/**
 * A utility class for streaming React responses.
 */
declare class experimental_StreamingReactResponse {
    constructor(res: ReadableStream, options?: {
        ui?: (message: {
            content: string;
            data?: JSONValue[];
        }) => UINode | Promise<UINode>;
        data?: experimental_StreamData;
        generateId?: IdGenerator;
    });
}
```
However this doesn't work in Nodejs servers and works only on Vercel as far as I know.

### Use Case

It would be incredibly useful to piggyback on the final response and add custom data to the response body sent back to the client.  For example if the function can be modified to accept an options params with the following signature:
```js
declare function streamToResponse(res: ReadableStream, response: ServerResponse, options?: {
    init?: {
        headers?: Record<string, string>;
        status?: number;
    }
    data?: experimental_StreamData;
    generateId?: IdGenerator;
}): void;
```
Which in turn would be use like so:
```js
router.post('/chat/:id', async (req, res) => {
    const openai = new OpenAI();

    const { messages } = req.body;

    const data = new experimental_StreamData();

    await data.append({
        customData: {
            messageCount: 1,
            id: '1',
        }
    });

    await data.close();

    try {
        const aiResponse = await openai.chat.completions.create({
          model: 'gpt-3.5-turbo',
          stream: true,
          messages,
        });

        const stream = OpenAIStream(aiResponse);

        return streamToResponse(stream, res, { data });
    } catch (error) {
        res.status(500).json({ error: 'Error forwarding request to OpenAI' });
    }
});
```

Currently struggling to find a way around this, and I really don't want to migrate to vercel just for this one feature.

**Comment by valstu** [comment]
I created my own version of `streamToResponse` which is pretty much the same as the original streamToResponse but with data support.

So add this function somewhere in your code:
```ts
export function streamToResponse(
  res: ReadableStream,
  response: ServerResponse,
  init?: { headers?: Record<string, string>; status?: number },
  data?: StreamData,
) {
  response.writeHead(init?.status || 200, {
    'Content-Type': 'text/plain; charset=utf-8',
    ...init?.headers,
  });

  let processedStream = res;

  if (data) {
    processedStream = res.pipeThrough(data.stream);
  }

  const reader = processedStream.getReader();
  function read() {
    void reader
      .read()
      .then(({ done, value }: { done: boolean; value?: any }) => {
        if (done) {
          response.end();
          return;
        }
        response.write(value);
        read();
      });
  }
  read();
}
```

Then use this streamToResponse instead of the one provided with AI SDK. I could make a PR about this if this is something maintainers would agree on?

**Comment by MartinCura** [comment]
Hello, i almost opened a similar PR to @valstu and @lgrammel's. My use case is adding some custom data as a "prelude" before streaming the LLM generation; for example, to add an identifier of the agent that is responding.

This can be done either by adding a stream or data argument that is written to `response` before the actual LLM streaming, or by allowing headers to not be set by `streamToResponse()` so that there's no errors because of twice trying to set the headers.

Below a simple example of both together jic it's of any use to see how we're now using it.

```typescript
/**
 * Adds the ability to not set headers (`{ headers: null }`) and/or write a prelude before streaming.
 */
export function streamToResponse(
  stream: ReadableStream,
  response: ServerResponse,
  { headers, prelude, status }: { headers?: Record<string, string> | null; prelude?: string; status?: number } = {},
) {
  if (headers !== null) {  // new check
    response.writeHead(status || 200, {
      "Content-Type": "text/plain; charset=utf-8",
      ...headers,
    });
  }

  if (prelude) {  // allow adding a "prelude" before the stream; another stream would also be fine but wasn't necessary for us
    response.write(prelude);
  }

  const reader = stream.getReader();
  function read() {
    reader.read().then(({ done, value }: { done: boolean; value?: any }) => {
      if (done) {
        response.end();
        return;
      }
      response.write(value);
      read();
    });
  }
  read();
}
```

**Comment by lgrammel** [comment]
@MartinCura adding a prelude can cause problems with stream parsing on the client (if you use useChat or useCompletion). Have you considered using `StreamData` instead? https://sdk.vercel.ai/docs/ai-sdk-ui/streaming-data

**Comment by lgrammel** [comment]
`streamToResponse` supports stream data in `v3.1.12`

**Comment by lgrammel** [comment]
## Identify issue type

Identified as **Feature**  
Confidence: **High**

### Rationale
This is a request for a new `streamToResponse` capability that was subsequently implemented, rather than a failure of existing promised behavior.

### Evidence
- The issue explicitly requests adding custom response-body data support to `streamToResponse`, beyond its existing headers and status options.
- Users propose API additions and custom implementations using `StreamData`; no existing documented behavior is reported as broken.
- A maintainer confirms that stream data support was added in v3.1.12.
