### ISSUE TITLE
Support tool use when using cohere provider

### ISSUE THREAD

**Issue by chanmathew** [vercel/ai#1331]
### Feature Description

With Cohere's new [Command R+](https://txt.cohere.com/command-r-plus-microsoft-azure/) model, it's a very viable and much cheaper option that can reliably function call. I don't believe the current AI SDK correctly handles the Cohere function responses, would be great to see this added.

### Use Case

Enabling tool use and function calling

**Comment by lgrammel** [comment]
https://github.com/vercel/ai/pull/1954

**Comment by lgrammel** [comment]
## Identify issue type

Identified as **Feature**  
Confidence: **High**

### Rationale
This requests a new provider capability—tool and function calling support for Cohere—rather than reporting a regression or violation of documented behavior.

### Evidence
- Title requests tool-use support for the Cohere provider.
- Description asks to add handling for Cohere Command R+ function responses to enable tool use and function calling.
- Maintainer comment links implementation PR #1954.
