### ISSUE TITLE
Trigger API Call without needing a message

### ISSUE THREAD

**Issue by ahmadbilaldev** [vercel/ai#1385]
### Feature Description

Folks is there a way to trigger the API call without needing an input (using handleSubmit) or message (using append)? 

Just need to trigger the call without providing any message. Any suggestions on how to go about it?

### Use Case

We have generation tasks where we already store messages on the API, and just take some variable values from the user. So, we don't need an additional message. Just need to trigger the call. 

Currently, it is not possible. The handle submit function requires an input to run. I have also tried replacing it with append but that (obviously) also requires a message. 

### Additional context

We are going around this by adding a dummy input message and removing it on the API. Not ideal.

**Comment by jeremyphilemon** [comment]
#2164 adds support for requesting a generation without adding another user message while using handleSubmit

**Comment by lgrammel** [comment]
## Identify issue type

Identified as **Feature**  
Confidence: **High**

### Rationale
This requests a new API capability for message-free generation rather than reporting a failure of documented behavior.

### Evidence
- The reporter asks to trigger an API call through `handleSubmit` or `append` without supplying a new input message.
- Current APIs require a message, forcing the reporter to send and then remove a dummy message.
- A maintainer comment states that #2164 adds support for generation without adding another user message.
