### ISSUE TITLE
Using OpenAI SDK with Ollama

### ISSUE THREAD

**Issue by mishushakov** [vercel/ai#1409]
### Description

See issue https://github.com/ollama/ollama/issues/3824#issuecomment-2071006813

### Code example

```
const result = await experimental_generateObject({
    model,
    schema,
    messages: [{ role: 'assistant', content: '' }, { role: 'user', content: '' }],
    temperature,
 })
```

**Comment by shouryan01** [comment]
Any updates on this?

**Comment by lgrammel** [comment]
There is now a dedicated Ollama provider: https://github.com/sgomez/ollama-ai-provider

**Comment by lgrammel** [comment]
## Identify issue type

Identified as **Feature**  
Confidence: **Medium**

### Rationale
This concerns adding or enabling Ollama provider compatibility rather than a demonstrated failure of existing promised behavior.

### Evidence
- The issue seeks to use Ollama with `experimental_generateObject` through the OpenAI SDK but provides no concrete error or documented-behavior violation.
- A maintainer points to a newly available dedicated Ollama provider as the solution.
