### ISSUE TITLE
Using Antropic with the new Generative UI

### ISSUE THREAD

**Issue by ElectricCodeGuy** [vercel/ai#1420]
### Feature Description

Is it possible to use the Antropic modes with the new Generetive UI? IO can't figure it out from the documentation or from the examples in the Github examples folder. From what I can see it only works with an API Route witch i have implemented and is working just fine, but I want to implement it using the generetive UI. 

### Use Case

See Above

### Additional context

```
const model = anthropic('claude-3-haiku-20240307', {
    topK: 0.2
  });
  // @ts-ignore
  const ui = render({
    provider: openai,
    model: 'gpt-4-turbo',
    messages: [
      { role: 'system', content: systemPromptTemplate },
      ...aiState.get().map((info: any) => ({
        role: info.role,
        content: info.content,
        name: info.name
      }))
    ],
    temperature: 0,
    initial: <ChatMessageSkeleton />,
    text: ({ content, done }) => {
      if (done) {
        aiState.done([
          ...aiState.get(),
          {
            role: 'assistant',
            content
          }
        ]);
      }
      return <BotMessage>{content}</BotMessage>;
    }
  });

  return {
    id: Date.now(),
    display: ui
  };
}
```

I have implanted this here and it is working fine, but i can see that this currently only works for OpenAI models, so is it possible to use the Antropic provider yet and create a streaming text response from the generative UI?

**Comment by lgrammel** [comment]
Right now, this is not possible, because
a) the new provider api is not compatible with render yet
b) the Anthropic API does not support streaming tool calls yet

**Comment by lgrammel** [comment]
## Identify issue type

Identified as **None**  
Confidence: **High**

### Rationale
This is primarily a usage/support question about choosing the appropriate API, not a confirmed bug or a concrete request to change the SDK, documentation, or examples.

### Evidence
- The reporter asks how to stream basic Anthropic text with Generative UI rather than identifying a concrete SDK failure.
- A maintainer explains that `render` is not compatible with the new provider API, while basic text streaming is possible through RSCs or `useChat`/`useCompletion`.
- The reporter clarifies that only basic text streaming is needed.
