### ISSUE TITLE
Error in Gemini Chat Template

### ISSUE THREAD

**Issue by ggukggukee** [vercel/ai#1450]
### Description

I want to run gemini chat in localhost but get `ai/google` error

### Code example

```
./lib/chat/actions.tsx:30:0
Module not found: Package path ./google is not exported from package /Users/user/Downloads/gemini-chatbot-main/node_modules/ai (see exports field in /Users/user/Downloads/gemini-chatbot-main/node_modules/ai/package.json)
  28 | import { format } from 'date-fns'
  29 | import { experimental_streamText } from 'ai'
> 30 | import { google } from 'ai/google'
  31 | import { GoogleGenerativeAI } from '@google/generative-ai'
  32 | import { z } from 'zod'
  33 | import { ListHotels } from '@/components/hotels/list-hotels'

https://nextjs.org/docs/messages/module-not-found

Import trace for requested module:
./app/(chat)/page.tsx
```

**Comment by lgrammel** [comment]
Hi please check out this example route: https://github.com/vercel/ai/blob/main/examples/next-google-generative-ai/app/api/chat/route.ts

**Comment by ggukggukee** [comment]
> Please check out this example route: https://github.com/vercel/ai/blob/main/examples/next-google-generative-ai/app/api/chat/route.ts

There was an error because instead of `genAI` is `google`

**Comment by lgrammel** [comment]
This seems resolved. Please re-open if this is still a problem.

**Comment by MihirMalaviya** [comment]
> Please check out this example route: https://github.com/vercel/ai/blob/main/examples/next-google-generative-ai/app/api/chat/route.ts

The link doesn't work for me

**Comment by lgrammel** [comment]
@MihirMalaviya 

we have an updated Google provider that works with the new AI SDK Core:
* https://sdk.vercel.ai/providers/ai-sdk-providers/google-generative-ai

if you want to use the legacy provider, please check out:
https://sdk.vercel.ai/providers/legacy-providers/google

**Comment by lgrammel** [comment]
## Identify issue type

Identified as **Examples**  
Confidence: **High**

### Rationale
The reported failure is in runnable template/sample code using an outdated or incorrect Google provider import, so it is best classified as an examples issue rather than an AI SDK runtime defect.

### Evidence
- The Gemini chatbot template fails to build because it imports `google` from the unexported `ai/google` package path.
- The reporter indicates the template used `google` where the referenced implementation expected `genAI`.
- Maintainer comments point to an updated Google example/provider implementation and a separate legacy-provider guide.
