### ISSUE TITLE
JSON parsing error - possible fixes

### ISSUE THREAD

**Issue by raivatshah** [vercel/ai#1456]
### Description

I've recently noticed that the gpt-4-turbo model (0125) tends to get the JSON wrong more during function calling (I'm using `onExperimentalToolCall`. When that happens, the error stack looks like the following: 

<img width="1328" alt="Screenshot 2024-04-26 at 16 52 41" src="https://github.com/vercel/ai/assets/29497717/d81dd3c5-b6b8-4224-a652-34d9a31ac111">

I'm curious if: 

1. anyone else has seen this pop-up recently 
2. if we have any retry / better error handling within the ai-sdk that we can do because the `JSON.parse` failure is within the `ai` sdk 

Thanks for the hard work @lgrammel!

**Comment by lgrammel** [comment]
@raivatshah what is your use case? we have released `streamText` and `streamObject` in the AI SDK 3.1 which might help

**Comment by lgrammel** [comment]
## Identify issue type

Identified as **None**  
Confidence: **Medium**

### Rationale
This is primarily a support question about handling malformed model output and available retry mechanisms. It does not clearly establish an AI SDK defect or make a definite request for a new capability.

### Evidence
- The malformed JSON originates from the GPT-4 Turbo function-call output and causes JSON.parse in the SDK to throw.
- The reporter asks whether retry or better error-handling facilities already exist rather than identifying behavior that contradicts an SDK guarantee.
- The maintainer requests clarification about the use case and suggests trying streamText or streamObject.
