### ISSUE TITLE
Omit/Modify Conversation History When Triggering Request in useChat

### ISSUE THREAD

**Issue by DarioPanada** [vercel/ai#1466]
### Feature Description

Hi Team,

Firstly, thank you so much for supporting this library, I have been finding it really useful!

I have a usecase where I need to limit the payload size when invoking an inference service. Because of this, it would be useful that the `handSubmit` function exposed by the `useChat` hook allowed to either omit the conversation history from the request (and only pass the latest user prompt), or allowed to override the conversation history that is passed. (So that, for example, I could only pass the first 15 words of each message.)

Right now, I see the library's API doesn't allow for that, but I was wondering if in principle it is something you would be willing to support?  I made a sample PR, happy to take feedback :) https://github.com/vercel/ai/pull/1468

### Use Case

Limiting payload size when back-end service imposes this kind of limit. Eg: AWS CloudFront when intercepting requests with ViewerRequest Lambda@Edge function associations imposes a 40kb limit after which the request is truncated.

**Comment by lgrammel** [comment]
https://github.com/vercel/ai/pull/1991

**Comment by lgrammel** [comment]
## Identify issue type

Identified as **Feature**  
Confidence: **High**

### Rationale
This requests a new `useChat` capability for customizing or omitting conversation history, rather than reporting a failure of existing documented behavior.

### Evidence
- The requester says `useChat` currently always includes conversation history and asks for a way to omit or override it when submitting.
- The proposed capability would enable reducing request payload size by sending only the latest prompt or a truncated history.
- A maintainer links a related implementation PR (#1991), reinforcing that this is an API enhancement.
