### ISSUE TITLE
Importing from "langchain/llms/openai" is deprecated.

### ISSUE THREAD

**Issue by oliviermills** [vercel/ai#1469]
### Description

In your example you use the old method for LangChain : 

https://github.com/vercel/ai/tree/main/examples/next-langchain/app/api/stream-data-chain/route.ts

You should no long user `LLMChain` and  update to using `invoke()` and, here `stream()` 

e.g.:

```js
const chatPrompt = ChatPromptTemplate.fromMessages([...])
const chain = chatPrompt.pipe(chatModel)
response = await chain.pipe(outputParser).stream({...},{ callbacks: [handlers]})
```

### Code example

```js
const model = new OpenAI({ temperature: 0, streaming: true });
  const prompt = PromptTemplate.fromTemplate(
    'What is a good name for a company that makes {product}?',
  );
  const chain = new LLMChain({ llm: model, prompt });
```

### Additional context

Should update the `LangChainStream()` to work with:

```js
import { OpenAI } from '@langchain/openai'
```

**Comment by beeirl** [comment]
@oliviermills have u been able to get it working using `chain.stream()` and Vercel's `LangChainStream()`? If so, mind sharing a gist?

**Comment by oliviermills** [comment]
> @oliviermills have u been able to get it working using `chain.stream()` and Vercel's `LangChainStream()`? If so, mind sharing a gist?

Not with the Vercel version of LangChainStream.. I implemented my own (https://dev.to/omills/vercel-ai-sdk-langchain-3edf) but this could be improved using AIStream I believe. You essentially need to pipe the right stream transformers. This uses the latest Vercel Ai sdk and latest Langchain.

**Comment by lgrammel** [comment]
I've updated the langchain integration: https://sdk.vercel.ai/providers/adapters/langchain

**Comment by lgrammel** [comment]
## Identify issue type

Identified as **Examples**  
Confidence: **High**

### Rationale
The issue primarily requests modernization of an outdated runnable LangChain example rather than reporting a failure of documented SDK behavior.

### Evidence
- The cited `examples/next-langchain` project uses deprecated LangChain imports and the legacy `LLMChain` API.
- The reporter asks to update the sample to use `invoke()`/`stream()` and current `@langchain/openai` imports.
- A maintainer later linked to the updated LangChain integration.
