### ISSUE TITLE
Groq API Support?

### ISSUE THREAD

**Issue by surjithctly** [vercel/ai#1475]
### Feature Description

I would like to see vercel sdk supports GROQ AI (https://groq.com/) using https://console.groq.com/docs/quickstart

It has compatibility with openai, so I guess it will be easier (wild guess)

### Use Case

GROQ API provides Opensource LLM APIs at a fraction of cost compared to Open AI or other similar tools.

**Comment by markusstrasser** [comment]
+1. The groq example within the examples folder doesn't work and uses non-existing imports from 'openai'

**Comment by MaxLeiter** [comment]
@surjithctly why is

```

const groq = createOpenAI({
  apiKey: process.env.GROQ_API_KEY ?? '',
  baseURL: 'https://api.groq.com/openai/v1',
});
```

not sufficient for you?

**Comment by jonschlinkert** [comment]
> why is ... not sufficient for you?

I'm always in favor of avoiding duplicate code and avoiding repetition, but I care even more about type safety and there are a few differences that might warrant more consideration. Groq has some limitations with a few options, and minor differences with expected behavior in one or two places, that seems like enough of a justification to at least have some helper methods or types for groq.  

See:

- https://console.groq.com/docs/tool-use#known-limitations
- https://console.groq.com/docs/openai
- https://console.groq.com/docs/text-chat#json-mode-object-object (look for "known limitations")

fwiw I totally get your perspective and won't lose too much sleep if you don't want to do this, but it'd be awesome if you did.

**Comment by surjithctly** [comment]
@MaxLeiter A dedicated docs will be a good first step because, I have never found this option in the docs in the first place. We usually look the providers page since everything else is there, so its easy to think "oh! its not supported yet". 

Also, I can see the entire docs is now changed and now I can see custom provider option, but still that doesn't explain I can use OpenAI with other providers. Even inside the /openai page, it's not mentioned.

**Comment by n1ckoates** [comment]
A dedicated Groq provider would be great for several reasons:
* It's better DX to have a consistent way of using a provider. For all supported providers, you just change out two lines (`import` and `model` option), but for Groq, you have to add additional boilerplate.
* Groq's [OpenAI compatibility](https://console.groq.com/docs/openai) isn't perfect. A dedicated provider would remove unsupported features instead of having runtime request errors.
* Groq has a different set of models available, which should be shown instead of OpenAI's models.

**Comment by lgrammel** [comment]
## Identify issue type

Identified as **Feature**  
Confidence: **High**

### Rationale
The core request is a new dedicated Groq provider and related ergonomics rather than a failure of promised SDK behavior. Although one comment reports an example problem, the subsequent discussion centers on expanding provider support.

### Evidence
- The description requests official Groq API support through its OpenAI-compatible endpoint.
- Maintainer discussion confirms Groq can currently be used via `createOpenAI` with a custom `baseURL`, while asking for justification for a dedicated provider.
- Later comments request a dedicated provider for improved DX, Groq-specific models, type safety, and handling unsupported OpenAI features.
