### ISSUE TITLE
Passing chatRequestOptions to the reload function provided by useChat does not work

### ISSUE THREAD

**Issue by ErikDale** [vercel/ai#1480]
### Description

1. Use the reload function in a client component
2. See if the data is accessible in the useChat api route (it is not)

### Code example
```JavaScript
//In the client component where reload is called: 

reload({
    data: {
         imageUrl: <image_url>,
    },
});

//In the /api/chat route:

const { messages, chatProfile, id, data } = await req.json(); // Here data is undefined.
```

**Comment by arnab710** [comment]
Same issue here. 
`reload` function ignores `ChatRequestOptions`.
I am trying to set the `header` via `ChatRequestOptions`. But it never reaches the API. 

But, `handleSubmit` with `ChatRequestOptions` works as expected.

@lgrammel do you know any fix?

```

// reload calling
const chatRequestOptions = setAuthorizationHeader(token);
reload(chatRequestOptions);

------------------------------------------

// setting headers
export const setAuthorizationHeader = (token: string) => {
    const chatRequestOptions: ChatRequestOptions = {
        headers: {
            authorization: token,
        },
    };

    return chatRequestOptions;
}; 

```

**Comment by lgrammel** [comment]
https://github.com/vercel/ai/pull/2429

**Comment by lgrammel** [comment]
fixed in main

**Comment by lgrammel** [comment]
## Identify issue type

Identified as **Bug**  
Confidence: **High**

### Rationale
This reports a concrete failure in the existing `useChat.reload` API, subsequently acknowledged and fixed by a maintainer.

### Evidence
- `reload` ignored `ChatRequestOptions`, so request `data` and headers did not reach the API.
- The same options worked with `handleSubmit`, indicating inconsistent existing behavior.
- A maintainer linked PR #2429 and confirmed the issue was “fixed in main.”
