### ISSUE TITLE
Allow array in the root of z schema

### ISSUE THREAD

**Issue by bernaferrari** [vercel/ai#1485]
### Feature Description

`Invalid schema for function 'json': schema must be a JSON Schema of 'type: \\"object\\"', got 'type: \\"array\\"`

I want to tell GPT I expect for ["a", "b", "c"], right now I need to make it like:
{
result: ["a", "b", "c"]
}

which I guess is fine, but maybe I could avoid that? I don't know. What do you think?

**Comment by lgrammel** [comment]
@bernaferrari this is a limitation of the OpenAI function calling API. You cannot pass arrays as top level objects. Instead, you need to create a top-level object with a property that contains the array.

**Comment by lgrammel** [comment]
## Identify issue type

Identified as **Feature**  
Confidence: **High**

### Rationale
This requests a capability beyond the current provider limitation rather than reporting broken or contradicted SDK behavior.

### Evidence
- The requester asks to allow a root-level array in the Zod/JSON schema instead of wrapping it in an object property.
- The maintainer explains that OpenAI function calling requires the top-level schema to be an object and recommends wrapping the array.
