### ISSUE TITLE
I hope that when verifying the schema of the chunk, the object field allows for undefined

### ISSUE THREAD

**Issue by liuhuapiaoyuan** [vercel/ai#1488]
### Feature Description

const openaiChatChunkSchema = z.object({
  object: z.enum([
    'chat.completion.chunk',
    'chat.completion', support for OpenAI-compatible providers such as Perplexity
]),

Because some third-party LLM are not fully standardized when they are compatible with OpenAI's interface, such as missing object, I hope this field can be selected

**Comment by lgrammel** [comment]
@liuhuapiaoyuan can you provide an example of a provider that does not support the `object` field?

**Comment by liuhuapiaoyuan** [comment]
For example, like `Zhipu`, there is no "object" field in its stream chunk. I believe this is an unnecessary validation field.

**Comment by liuhuapiaoyuan** [comment]
```
data: {"id":"8313807536837492492","created":1706092316,"model":"glm-4","choices":[{"index":0,"delta":{"role":"assistant","content":"土"}}]}
data: {"id":"8313807536837492492","created":1706092316,"model":"glm-4","choices":[{"index":0,"delta":{"role":"assistant","content":"星"}}]}

....

data: {"id":"8313807536837492492","created":1706092316,"model":"glm-4","choices":[{"index":0,"delta":{"role":"assistant","content":"，"}}]}
data: {"id":"8313807536837492492","created":1706092316,"model":"glm-4","choices":[{"index":0,"delta":{"role":"assistant","content":"主要由"}}]}
data: {"id":"8313807536837492492","created":1706092316,"model":"glm-4","choices":[{"index":0,"finish_reason":"length","delta":{"role":"assistant","content":""}}],"usage":{"prompt_tokens":60,"completion_tokens":100,"total_tokens":160}}
data: [DONE]
```

**Comment by lgrammel** [comment]
https://github.com/vercel/ai/pull/1702

**Comment by lgrammel** [comment]
## Identify issue type

Identified as **Feature**  
Confidence: **High**

### Rationale
This requests broader compatibility with non-standard OpenAI-compatible providers by relaxing schema validation, which is an enhancement rather than a failure of documented behavior.

### Evidence
- The request proposes making the OpenAI-compatible stream chunk `object` field optional.
- Zhipu stream chunks are provided as an example because they omit the `object` field.
- A maintainer linked PR #1702 in response.
