### ISSUE TITLE
Components rendered by tools will be immediately overwritten by text, causing the execution of generated UI to fail.

### ISSUE THREAD

**Issue by 1057105012** [vercel/ai#1499]
### Description

I thought, maybe this is a difficult problem to solve? Nevertheless, it is inappropriate to expose this ambiguous or unintuitive behavior to users. Sleep should not be needed, or it should be hidden, or it is a bug and some branch judgments are missing.

### Code example

`generate: async ({ symbol, numOfMonths }) => {
          console.log("call func", symbol, numOfMonths)
         // Comment sleep, component exception, no comment, normal rendering after 1 second
         // await sleep(1000);
          history.done((messages: ServerMessage[]) => [
            ...messages,
            {
              role: 'assistant',
              content: `Showing stock information for ${symbol}`
            }
          ])
          return <RenderN/>;
        }`

this is bad

### Additional context

1057105012@qq.com

**Comment by lgrammel** [comment]
Could you specify what example you are referring to? The only sleep code that I found is for illustration purposes (to simulate delay).

**Comment by lgrammel** [comment]
## Identify issue type

Identified as **Bug**  
Confidence: **Medium**

### Rationale
This describes a concrete failure in existing generated UI behavior rather than a request for a new capability. However, the incomplete reproduction details reduce certainty.

### Evidence
- The reporter says a component returned by a tool's `generate` function is overwritten by subsequent text and fails to render unless an artificial delay is added.
- The provided code indicates that uncommenting `await sleep(1000)` makes rendering work normally, suggesting timing-dependent incorrect behavior.
- A maintainer requested clarification about which example is affected, so the report lacks a complete reproduction context.
