### ISSUE TITLE
Add ability to stream additional data immediately in `StreamData`

### ISSUE THREAD

**Issue by raivatshah** [vercel/ai#1500]
### Feature Description

[StreamData](https://sdk.vercel.ai/docs/ai-sdk-ui/streaming-data) is great! What could be even better if there was some way to use the `data` object (or otherwise) to stream data at will -- at anytime basically.

### Use Case

 One big use is in consumer apps - when a tool call is going to take time, you want to indicate that to the client.

**Comment by lgrammel** [comment]
Add better support in `v3.1.11`

**Comment by raivatshah** [comment]
awesome thanks so much @lgrammel <3

**Comment by lgrammel** [comment]
## Identify issue type

Identified as **Feature**  
Confidence: **High**

### Rationale
This requests expanded streaming behavior rather than reporting a failure of existing documented functionality.

### Evidence
- The issue requests the ability to send `StreamData` at any time, including while a long-running tool call is in progress.
- The maintainer stated that better support was added in v3.1.11, indicating this was a capability enhancement.
