### ISSUE TITLE
Add stop helper to useAssistant

### ISSUE THREAD

**Issue by jferrettiboke** [vercel/ai#1503]
### Feature Description

Could we add support for canceling a call that is in progress in the AI SDK UI? I know this feature is available in the AI SDK Core and AI SDK RSC, but can we incorporate it into the AI SDK UI as well?

### Use Case

Many users see no value in waiting for the full response from the server if they notice that the response does not align with their desires or if they realize the response is incorrect. It would be beneficial to have the ability to cancel a call that is in progress while using the AI SDK UI.

**Comment by lgrammel** [comment]
The AI SDK UI functions ( useChat, useCompletion ) return a `stop` helper (see https://sdk.vercel.ai/docs/reference/ai-sdk-ui/use-chat#stop ). Would this work for your use case?

**Comment by jferrettiboke** [comment]
@lgrammel Thanks! I totally missed this in the documentation.

**Comment by jferrettiboke** [comment]
@lgrammel But this doesn't exist in `useAssistant`. Right? I need it there.

**Comment by lgrammel** [comment]
PR: https://github.com/vercel/ai/pull/1524

Unfortunately it seems that OpenAI does not correctly abort the assistant from running when an abort signal is sent, and prevents further chat responses until it has finished completely.

**Comment by jferrettiboke** [comment]
@lgrammel Thanks!

**Comment by lgrammel** [comment]
## Identify issue type

Identified as **Feature**  
Confidence: **High**

### Rationale
This requests a new cancellation capability for `useAssistant`, rather than reporting that an existing promised behavior is broken.

### Evidence
- The request specifically asks to add a `stop`/cancellation helper to `useAssistant`.
- Existing `useChat` and `useCompletion` hooks already expose `stop`, but comments confirm that `useAssistant` does not.
- A maintainer linked an implementation PR and noted an upstream OpenAI limitation when aborting assistant runs.
