### ISSUE TITLE
Error: action is not a function

### ISSUE THREAD

**Issue by camwest** [vercel/ai#1531]
### Description

![CleanShot 2024-05-08 at 10 47 05@2x](https://github.com/vercel/ai/assets/22905/72546e86-2932-40f1-8bad-f991f14ab626)

Copy & Pasted these examples: https://sdk.vercel.ai/docs/ai-sdk-rsc/ai-ui-states

**Comment by camwest** [comment]
Unsure if this is related or not:

![CleanShot 2024-05-08 at 10 48 33@2x](https://github.com/vercel/ai/assets/22905/645de2b0-4a27-4e34-980e-4133e09fbd43)


`export const AI` is typed as `any` instead of AIProvider<...>. Not sure if this is related.

**Comment by lgrammel** [comment]
@camwest do you have a github repository with a reproduction that you could share?

**Comment by camwest** [comment]
> @camwest do you have a github repository with a reproduction that you could share?

I tried to check this one out and get the example set up. I kept running into an issue where it couldn't find "ai/rsc" even after running pnpm install in the root and the example. 

Will attempt again.

**Comment by jeremyphilemon** [comment]
@camwest just checking in, were you able to resolve this?

**Comment by camwest** [comment]
Yes. Darn I forget how I fixed it. I'm pretty sure I was doing something wrong.

**Comment by lgrammel** [comment]
## Identify issue type

Identified as **None**  
Confidence: **High**

### Rationale
The reported failure was ultimately attributed by the reporter to likely usage error, with no reproducible SDK or documentation defect established. This is best treated as a resolved support issue.

### Evidence
- Submitting a message after copying the AI UI States documentation example produced “action is not a function.”
- The reporter could not provide a reproduction and later confirmed the problem was resolved.
- The reporter stated they were “pretty sure” they had been doing something wrong.
