### ISSUE TITLE
Support for batch embed

### ISSUE THREAD

**Issue by blechatellier** [vercel/ai#1602]
The `embed` method doesn't support batch generation of embeddings (supported by OpenAI). It would be great to allow `string | string[]`.

**Comment by blechatellier** [comment]
I can see in code that it's forcing it to be a single value https://github.com/vercel/ai/blob/163fb6633cf05cc3861ceee8b9cc6a06ea842cab/packages/core/core/embed/embed.ts#L47

**Comment by lgrammel** [comment]
https://github.com/vercel/ai/pull/1617

**Comment by lgrammel** [comment]
Implemented in `v3.1.10`

**Comment by blechatellier** [comment]
Thanks @lgrammel 🚀

**Comment by lgrammel** [comment]
## Identify issue type

Identified as **Feature**  
Confidence: **High**

### Rationale
This is a request for a new batch embedding capability rather than a failure of documented single-value behavior.

### Evidence
- The issue requests batch embedding support by allowing `string | string[]` instead of only a single value.
- The reporter notes the implementation forced a single input and returned only the first embedding.
- A maintainer linked the implementing pull request and confirmed the capability was added in v3.1.10.
