### ISSUE TITLE
Add AI Vercel SDK to React

### ISSUE THREAD

**Issue by ejgutierrez74** [vercel/ai#1612]
### Feature Description

I want some tutorials and examples using AI Vercel SDK with React.

### Use Case

Use a chatbot with a LLM provider using React

**Comment by lgrammel** [comment]
## Identify issue type

Identified as **Documentation**  
Confidence: **High**

### Rationale
The issue requests instructional documentation for using the existing SDK with React rather than a change to SDK behavior or capabilities.

### Evidence
- The request is for tutorials and examples showing how to build a React chatbot with an LLM provider.
- The maintainer points to existing Next.js/React tutorials in the AI SDK documentation.
