### ISSUE TITLE
the example of bedrock/anthropic-v3 show error

### ISSUE THREAD

**Issue by willy20040711** [vercel/ai#1660]
### Description

The example  : examples/next-aws-bedrock/app/api/chat-anthropic-v3/route.ts **show error**
It seem that the experimental_buildAnthropicMessages is not  suitable for current InvokeModelWithResponseStreamCommand.
![image](https://github.com/vercel/ai/assets/3763474/c84252eb-f971-4d17-b986-0a315b2b071e)

error ValidationException: Malformed input request: #: required key [prompt] not found#: required key [max_tokens_to_sample] not found#: extraneous key [max_tokens] is not permitted#: extraneous key [message] is not permitted, please reformat your input and try again.

**Comment by dubscode** [comment]
@willy20040711 I had a similar problem, but I was able to get it working with this setup (your credentials setup may be different):
```
import { AWSBedrockAnthropicMessagesStream, StreamingTextResponse } from 'ai';
import {
  BedrockRuntimeClient,
  InvokeModelWithResponseStreamCommand,
} from '@aws-sdk/client-bedrock-runtime';

import { experimental_buildAnthropicMessages } from 'ai/prompts';
import { fromIni } from '@aws-sdk/credential-providers';

const bedrockClient = new BedrockRuntimeClient({
  region: 'us-west-2',
  credentials: fromIni({ profile: 'default' }),
});

export async function POST(req: Request) {
  // Extract the `prompt` from the body of the request
  const { messages } = await req.json();

  // Ask Claude for a streaming chat completion given the prompt
  const bedrockResponse = await bedrockClient.send(
    new InvokeModelWithResponseStreamCommand({
      modelId: 'anthropic.claude-3-opus-20240229-v1:0',
      contentType: 'application/json',
      accept: 'application/json',
      body: JSON.stringify({
        anthropic_version: 'bedrock-2023-05-31',
        max_tokens: 1000,
        messages: experimental_buildAnthropicMessages(messages),
      }),
    })
  );

  // Convert the response into a friendly text-stream
  const stream = AWSBedrockAnthropicMessagesStream(bedrockResponse);

  // Respond with the stream
  return new StreamingTextResponse(stream);
}
```
I don't fully understand how it works, but i hope this can help you.

**Comment by willy20040711** [comment]
@dubscode yes, you're right.
It can work now.
Thanks a lot.  : )

**Comment by lgrammel** [comment]
We have a new AWS Bedrock provider so that example was removed (outdated). Check out https://sdk.vercel.ai/providers/ai-sdk-providers/amazon-bedrock

**Comment by lgrammel** [comment]
## Identify issue type

Identified as **Examples**  
Confidence: **High**

### Rationale
The reported failure is specifically in an outdated runnable example and was resolved by correcting and ultimately removing that example, so this is an examples issue.

### Evidence
- The bundled `examples/next-aws-bedrock/app/api/chat-anthropic-v3/route.ts` produced an AWS Bedrock `ValidationException` because its request body used incompatible fields.
- A commenter supplied corrected sample code using Claude 3's Bedrock message format, which the reporter confirmed worked.
- A maintainer stated that the outdated example was removed after introduction of the new AWS Bedrock provider.
