### ISSUE TITLE
Stop tokens?

### ISSUE THREAD

**Issue by f1shy-dev** [vercel/ai#1685]
### Feature Description

Custom stop tokens - a feature in OpenAI and other providers such as Groq is just missing from the custom options for models in the SDK. Can we please have this feature?

**Comment by lgrammel** [comment]
Duplicates #1633

**Comment by lgrammel** [comment]
## Identify issue type

Identified as **None**  
Confidence: **High**

### Rationale
Although the requested capability would normally be a feature, this issue is primarily duplicate bookkeeping and is therefore classified as none.

### Evidence
- The issue requests support for custom stop tokens in model options.
- The maintainer notes that it duplicates issue #1633.
