### ISSUE TITLE
How to explicitly pass OPEN_AI_TOKEN into `generateText` function 

### ISSUE THREAD

**Issue by nikitavoloboev** [vercel/ai#1691]
### Description

I searched the docs and can't find it.

### Code example

```js
	.handler(async ({ input, ctx }) => {
		const { description } = input
		const result = await generateText({
			model: openai("gpt-4o"),
			tools: { checkIfFoodOrDrinkByDescription },
			system: `You have to answer if image description provided is food or drink and be precise. It has to be precise image of food or drink, otherwise return false.`,
			messages: [{ role: "user", content: description }],
		})
		```
		
		have above code, it works locally but breaks in Vercel production due to missing OPEN_AI_KEY which I added, don't get how to solve this.

**Comment by lgrammel** [comment]
what is the `OPEN_AI_TOKEN`? if you mean the OpenAI API key, you can either set it through an env variable or in the `createOpenAI` function: https://sdk.vercel.ai/providers/ai-sdk-providers/openai#provider-instance

**Comment by lgrammel** [comment]
## Identify issue type

Identified as **None**  
Confidence: **High**

### Rationale
This is primarily a configuration/support question that was answered by pointing to existing provider configuration documentation, rather than a bug or request to change the SDK or docs.

### Evidence
- The reporter asks how to explicitly provide an OpenAI API key after a production environment configuration problem.
- A maintainer explains that the key can be supplied through an environment variable or the documented `createOpenAI` provider instance configuration.
- No broken or contradictory AI SDK behavior is demonstrated.
