### ISSUE TITLE
streamUI and chatgpt: Failed after 3 attempts. Last error: Failed to process error response

### ISSUE THREAD

**Issue by 0xbohu** [vercel/ai#1694]
### Description

I am using this template
https://vercel.com/templates/Next.js/nextjs-ai-chatbot

that uses streamUI from @ai-sdk/openai

```
const result = await streamUI({
    model: openai('gpt-3.5-turbo'),
    initial: <SpinnerMessage />,
```
Got error 
```
⨯ ../core/util/retry-with-exponential-backoff.ts (51:13) @ _retryWithExponentialBackoff
 ⨯ AI_RetryError: Failed after 3 attempts. Last error: Failed to process error response
    at async $$ACTION_1 (./lib/chat/actions.tsx:178:20)
digest: "1632544603"
  49 |
  50 |     if (tryNumber > maxRetries) {
> 51 |       throw new RetryError({
     |             ^
  52 |         message: `Failed after ${tryNumber} attempts. Last error: ${errorMessage}`,
  53 |         reason: 'maxRetriesExceeded',
  54 |         errors: newErrors,
 POST / 500 in 6761ms
```

### Code example

```
import 'server-only'
import {
  createAI,
  createStreamableUI,
  getMutableAIState,
  getAIState,
  streamUI,
  createStreamableValue
} from 'ai/rsc'
import { openai } from '@ai-sdk/openai'

const result = await streamUI({
    model: openai('gpt-3.5-turbo'),
    initial: <SpinnerMessage />,
```

### Additional context

Have ChatGPT plus subscription, created a project API key and configured in this app. Also tried different mode: 
"gpt-4o" but same error

**Comment by nicoalbanese** [comment]
Hey! Sorry you're experiencing this error. Did you add credit to your OpenAI account? It doesn't look like ChatGPT plus subscription includes any credits towards the API as per: https://help.openai.com/en/articles/6950777-what-is-chatgpt-plus#h_e3d911c532

**Comment by 0xbohu** [comment]
thank you @nicoalbanese that is the reason! I have added $10 to API usage and now it is working! have to create a new API key as well, as the old one also gives me insufficent_quota error

**Comment by lgrammel** [comment]
Keeping open, since there seems to be a potential problem parsing errors.

**Comment by lgrammel** [comment]
## Identify issue type

Identified as **Bug**  
Confidence: **High**

### Rationale
This reports incorrect error handling in the existing OpenAI provider. Although adding API credit resolved the underlying quota issue, the SDK failed to parse and present the provider error correctly.

### Evidence
- The SDK returned “Failed to process error response” instead of exposing OpenAI’s insufficient_quota error.
- A maintainer identified a potential error-parsing problem.
- The maintainer confirmed it was working on main and that the chatbot template needed an updated OpenAI provider.
