### ISSUE TITLE
Increase Timeout Duration or Improve Heuristic Detection for StreamData Hanging Warning

### ISSUE THREAD

**Issue by matzkoh** [vercel/ai#1699]
#### Issue Summary

Currently, the `StreamData` component in the Vercel AI library is configured to display a `console.warn` message stating "The data stream is hanging." if the stream is not closed within 3 seconds of starting. This 3-second timeout feels too short for many use cases, leading to unnecessary warnings.

#### Proposal

I propose either:

1. **Increasing the timeout duration**: Extending the 3-second limit to a longer duration (e.g., 5 or 10 seconds) to reduce the frequency of premature warnings.
2. **Implementing more heuristic detection**: Using a more sophisticated approach to determine if the data stream is genuinely hanging, rather than relying on a fixed timeout.

#### Rationale

Many applications might experience legitimate delays longer than 3 seconds due to various factors such as network latency, large data payloads, or backend processing time. Increasing the timeout or employing a more heuristic method would make the warning system more reliable and less prone to false positives.

**Comment by fkesheh** [comment]
onFinish on streamText with AI usually takes much more than 3 seconds, so it's a warning that always shows up. Thanks for investigating this, I really thought there was some issue on my code.

**Comment by lgrammel** [comment]
https://github.com/vercel/ai/pull/2602

**Comment by lgrammel** [comment]
## Identify issue type

Identified as **Bug**  
Confidence: **High**

### Rationale
The issue describes an existing warning heuristic producing false positives during normal stream operation, which is incorrect current behavior despite the proposed timeout and heuristic improvements.

### Evidence
- StreamData emits a "The data stream is hanging" warning after only 3 seconds even when the stream is legitimately still processing.
- A commenter reports the warning consistently appears because streamText's onFinish commonly takes longer than 3 seconds.
- A maintainer linked PR #2602 in response, indicating a code-level resolution.
