### ISSUE TITLE
Safety settings for providers

### ISSUE THREAD

**Issue by ashersamuel8** [vercel/ai#1739]
### Feature Description

Gemini keeps blocking content because of safety-filters. Would really be helpful to know which safety-filters are being triggered and also adjust the safety settings.

Please consider adding this feature for all providers. Thank you!

**Comment by lgrammel** [comment]
duplicates #1686

**Comment by roelfjan** [comment]
Great! Many 🙏

**Comment by lgrammel** [comment]
## Identify issue type

Identified as **None**  
Confidence: **High**

### Rationale
Although the requested capability is an enhancement, this issue was explicitly identified as a duplicate, which falls under duplicate bookkeeping in this classification scheme.

### Evidence
- The request asks to expose triggered Gemini safety filters and allow users to adjust safety settings across providers.
- A maintainer states that the request duplicates issue #1686.
