### ISSUE TITLE
add googleAuthOptions for vertex gemini

### ISSUE THREAD

**Issue by li2109** [vercel/ai#1773]
### Feature Description

Can you add googleAuthOptions to GoogleVertexProviderSettings?
context: https://stackoverflow.com/questions/77944196/vertex-ai-googleautherror-in-nodejs

```
const authOptions = {
        credentials: {
            client_email: process.env.GOOGLE_VERTEX_CLIENT_EMAIL,
            private_key: process.env.GOOGLE_VERTEX_PRIVATE_KEY!.replace(/\\n/g, "\n"),
        }
    }

    const vertex_ai = new VertexAI({
        project: process.env.GOOGLE_VERTEX_PROJECT!,
        location: process.env.GOOGLE_VERTEX_LOCATION,
        googleAuthOptions: authOptions,
    });
const model = vertex_ai.preview.getGenerativeModel({ model: 'gemini-1.5-flash-001' })
```

**Comment by lgrammel** [comment]
https://github.com/vercel/ai/pull/1777

**Comment by lgrammel** [comment]
## Identify issue type

Identified as **Feature**  
Confidence: **High**

### Rationale
This requests an API/provider configuration expansion rather than reporting that existing documented behavior is broken.

### Evidence
- The issue explicitly requests adding `googleAuthOptions` to `GoogleVertexProviderSettings`.
- The supplied code demonstrates credential configuration as the desired new provider capability.
- The maintainer links pull request #1777, indicating an implementation for the requested addition.
