### ISSUE TITLE
no way to abort ai/rsc createStreamableValue / readStreamableValue from the client side

### ISSUE THREAD

**Issue by psai-terwin** [vercel/ai#1795]
### Feature Description

There should be a basic way to cancel a streaming request made with ai/rsc but the most basic feature of a stream seems non existent or undocumented

### Use Case

The basic stop button on all streaming chat UI's like ChatGPT, Claude, etc

**Comment by lgrammel** [comment]
Related to #1122

**Comment by MobileAppVault** [comment]
@psai-terwin did you found any workaround to cancel actions?

**Comment by lgrammel** [comment]
Duplicate of #1122

**Comment by lgrammel** [comment]
## Identify issue type

Identified as **None**  
Confidence: **High**

### Rationale
Although the underlying request is for a new cancellation capability, this issue was confirmed by a maintainer to be duplicate bookkeeping and is therefore classified as none.

### Evidence
- The report requests client-side cancellation for `createStreamableValue` / `readStreamableValue`.
- A maintainer explicitly identified the issue as a duplicate of #1122.
