### ISSUE TITLE
Tools with Generate Object

### ISSUE THREAD

**Issue by arnau01** [vercel/ai#1803]
### Feature Description

Generating structured data is very helpful, would be great if tool calling was supported.

### Use Case

Providing a output schema and having access to external tools

**Comment by lgrammel** [comment]
`generateObject` uses forced tool calling under the hood for some providers, so this might not be possible.

**Comment by arnau01** [comment]
Makes sense, my current workaround is a simple chain, first `generateText` then `streamObject` which allows for tool usage and also controlling the schema.

**Comment by stephenkalnoske** [comment]
> Makes sense, my current workaround is a simple chain, first `generateText` then `streamObject` which allows for tool usage and also controlling the schema.

Can you give an example of this?

**Comment by michaeloliverx** [comment]
How can I use tool calling along with `generateObject`?

My structured output requires some lookups to generate its data, how can I work around this for now?

**Comment by michaeloliverx** [comment]
The queries to lookup need to be inferred by the LLM itself then I would like a chain of thought structured output back. AFAIK structured-outputs and tool calling is supported in "pure" openai SDK usage?

https://platform.openai.com/docs/guides/structured-outputs/examples?lang=node.js

**Comment by lgrammel** [comment]
Not quite the same but you can use the "Agents with Structured Answers" approach: https://sdk.vercel.ai/docs/ai-sdk-core/agents#structured-answers

**Comment by lgrammel** [comment]
We have added a `experimental_output` feature to `generateText` that allows you to create structured information while calling (openai) tools.

https://sdk.vercel.ai/docs/ai-sdk-core/generating-structured-data#structured-output-with-generatetext

**Comment by jeetsoni** [comment]
but what if i want to use antropic insted if openai?

**Comment by lgrammel** [comment]
## Identify issue type

Identified as **Feature**  
Confidence: **High**

### Rationale
This requests a new capability combining structured object generation with tool calling; it does not report broken or contradictory existing behavior.

### Evidence
- The issue explicitly requests tool-calling support while generating schema-constrained structured data.
- A maintainer explains that `generateObject` uses forced tool calling for some providers, creating a design limitation rather than a malfunction.
- Later comments provide workarounds and mention `experimental_output` for structured output with `generateText`, but users still seek broader provider support.
