### ISSUE TITLE
 Support models other than Gemini in Google Vertex Provider

### ISSUE THREAD

**Issue by wong2** [vercel/ai#1813]
### Feature Description

Google Vertex Model Gardens provides a variety of AI models other than the Gemini family, for example, it has support of Anthropic Claude models. But when using them with Vertex Provider currently, we will get the following error:

`/locations/us-west2/publishers/google/models/claude-3-opus` 404

**Comment by fry69** [comment]
FYI: There is a pull request for an `anthropic-vertex` provider -> https://github.com/vercel/ai/pull/2482

**Comment by lgrammel** [comment]
@wottpal we are looking into adding a dedicated provider for Anthropic/GCP cc @shaper

**Comment by shaper** [comment]
Hi @wottpal thanks for the feature request. As Lars mentioned we are working on a Vertex/Anthropic provider now, it would be great to have you try it out when it is ready. I'll update here when we have something for you.

**Comment by shaper** [comment]
https://github.com/vercel/ai/pull/3978 is out for review.

**Comment by wottpal** [comment]
@shaper Amazing! Would love to give it a try. What's the most straightforward way to test it locally? Would I have to build this repo on my own or are there PR-releases?

**Comment by shaper** [comment]
> @shaper Amazing! Would love to give it a try. What's the most straightforward way to test it locally? Would I have to build this repo on my own or are there PR-releases?

We just published the change, if you update to the module versions here https://github.com/vercel/ai/pull/4011 you should be able to try it.

The docs are also updated here: https://sdk.vercel.ai/providers/ai-sdk-providers/google-vertex

**Comment by lgrammel** [comment]
## Identify issue type

Identified as **Feature**  
Confidence: **High**

### Rationale
This asks for a new provider capability/model integration rather than reporting a failure of an already supported or documented behavior.

### Evidence
- The issue requests support for non-Gemini models hosted on Google Vertex Model Garden, specifically Anthropic Claude.
- Maintainers explicitly describe it as a feature request and implemented a dedicated Vertex/Anthropic provider.
- The comments point to the provider's publication and updated documentation.
