### ISSUE TITLE
```onFinish```   is never called in streamText args

### ISSUE THREAD

**Issue by myudak** [vercel/ai#1841]
### Description

Currently running a bit of code in the onFinish handler of streamText on /api/chat. It's never called. The streaming works just fine but the handler isn't called.

i already copied from [documentation](https://sdk.vercel.ai/docs/ai-sdk-ui/storing-messages) and still doesn't work

### Code example

```
import { openai } from '@ai-sdk/openai';
import { streamText, convertToCoreMessages } from 'ai';

// Allow streaming responses up to 30 seconds
export const maxDuration = 30;

export async function POST(req: Request) {
  const { messages } = await req.json();

  const result = await streamText({
    model: openai('gpt-4-turbo'),
    messages: convertToCoreMessages(messages),
    async onFinish({ text, toolCalls, toolResults, usage, finishReason }) {
      // implement your own storage logic:
      console.log("onFinish")
      await saveChat({ text, toolCalls, toolResults });
    },
  });

  return result.toAIStreamResponse();
}
```

### Additional context

Running Next 14, App Router, Served on vercel,      "ai": "^3.1.14",

**Comment by lgrammel** [comment]
`onFinish` was added in `3.1.15`. Can you confirm which exact versions of `ai` and of `@ai-sdk/openai` you are using?

**Comment by lgrammel** [comment]
I just tested it locally and it works, so it's most likely a version or deployment issue.

**Comment by myudak** [comment]
> `onFinish` was added in `3.1.15`. Can you confirm which exact versions of `ai` and of `@ai-sdk/openai` you are using?

oh wow yeah i didnt know this must been the issue thank you

**Comment by myudak** [comment]
fixed it

**Comment by lgrammel** [comment]
## Identify issue type

Identified as **None**  
Confidence: **High**

### Rationale
This was a version-related support issue rather than broken current SDK behavior.

### Evidence
- Reporter was using `ai` version `^3.1.14`, while `onFinish` was added in `3.1.15`.
- Maintainer confirmed the callback worked locally and identified a likely version or deployment mismatch.
- Reporter acknowledged the version issue and confirmed it was fixed.
