### ISSUE TITLE
Azure AI parallel tools call issue 

### ISSUE THREAD

**Issue by thareekanvarm** [vercel/ai#1844]
### Description

I'm getting a 400 error when I try to send an assistant message with 'tool_calls'. The error message says that each 'tool_call_id' must be followed by tool messages responding to each 'tool_call_id'. The 'tool_call_ids' that don't have response messages are listed below. im using azure AI

![image](https://github.com/vercel/ai/assets/117096530/3b516873-0225-42d7-8950-e7176b5c2328)

### Code example

```
CLIENT SIDE 

 const {
    messages,
    input,
    handleInputChange,
    setMessages,
    append,
    handleSubmit,
    reload,
    isLoading,
    stop,
  } = useChat({
    api: "/api/chat",
    experimental_onToolCall: functionCalls,
    initialMessages: initialMessages,
  });

```

```
SERVER SIDE

import { OpenAIStream, StreamingTextResponse } from "ai";
import OpenAI from "openai";

const endpoint = `https://${process.env.AZURE_OPENAI_API_INSTANCE_NAME}.openai.azure.com`;

export const aiConfig = {
  apiKey: process.env.AZURE_OPENAI_API_KEY,
  baseURL: `${endpoint}/openai/deployments/${process.env.AZURE_OPENAI_API_DEPLOYMENT_NAME}`,
  defaultQuery: { "api-version": process.env.AZURE_OPENAI_API_VERSION },
  defaultHeaders: { "api-key": process.env.AZURE_OPENAI_API_KEY },
};

const openai = new OpenAI(aiConfig);

export const config = {
  runtime: "edge",
};

export default async function POST(req) {
  const { messages }: { messages: any[] } = await req.json();

  // Set the number of messages to send  const maxNumMessagesToSend = 20;
  // Get the last `numMessagesToSend` messages  const lastMessages = messages.slice(-maxNumMessagesToSend);

  const response = await openai.chat.completions.create({
    model: process.env.AZURE_OPENAI_API_MODEL_NAME,
    stream: true,
    messages: [...messages],
    temperature: 0.3,
    n: 1,
    // max_tokens: 1000,
    tools: functions,
    tool_choice: "auto",
  });

  const stream = OpenAIStream(response, {
    experimental_onToolCall: async () => {
      return;
    },
  });

  return new StreamingTextResponse(stream);
}

```
### Additional context

using " gpt-4o " and Azure AI

**Comment by thareekanvarm** [comment]
fixed

**Comment by techpeace** [comment]
Looks like our issue wasn't quite the same, but seeing as I came here from a Google search for the same error message, thought I'd share our resolution. It turned out we needed to bump to version 3.3.33 so that `streamText` supported the `maxToolRoundtrips` option, which enables round-trip function calling: https://sdk.vercel.ai/examples/node/tools/call-tools-with-automatic-roundtrips

**Comment by lgrammel** [comment]
## Identify issue type

Identified as **Bug**  
Confidence: **Medium**

### Rationale
This reports a concrete failure in the existing tool-calling flow rather than requesting a new capability. The unexplained resolution makes the SDK’s responsibility somewhat uncertain.

### Evidence
- Sending an assistant message containing parallel `tool_calls` to Azure OpenAI returns HTTP 400 because corresponding tool-response messages are considered missing.
- The report uses AI SDK `useChat` and `OpenAIStream` with GPT-4o and provides client/server reproduction code.
- The author later stated only that it was “fixed,” without explaining whether the cause was SDK behavior or application configuration.
