### ISSUE TITLE
Work with other file attachments instead of just images

### ISSUE THREAD

**Issue by Godrules500** [vercel/ai#1903]
### Feature Description

Currently the SDK works with just image attachments. I would like for it to be able to handle other file types like pdfs, excel, word, and etc.

### Use Case

Our users need the ability to upload documents and compare results, or summarize information.

**Comment by NaucMeIT** [comment]
This would be awesome feature. Especially as Gemini supports videos.

**Comment by BleedingDev** [comment]
I opened PR, it's first attempt, will need more work definitely.

https://github.com/vercel/ai/pull/1945

**Comment by cjlryan** [comment]
> This would be awesome feature. Especially as Gemini supports videos.

👆 This. Would love to be able to use this instead of the VertexAI API 🤮

**Comment by Godrules500** [comment]
> > This would be awesome feature. Especially as Gemini supports videos.
> 
> 👆 This. Would love to be able to use this instead of the VertexAI API 🤮

So far, I've been able to work with the other attachments by passing the base64 URL into the image property, and it has been working praise the Lord!

**Comment by jamiedavenport** [comment]
+1 would also love the ability to work with videos and pdfs using the ai sdk

**Comment by cjlryan** [comment]
> > > This would be awesome feature. Especially as Gemini supports videos.
> 
> > 
> 
> > 👆 This. Would love to be able to use this instead of the VertexAI API 🤮
> 
> 
> 
> So far, I've been able to work with the other attachments by passing the base64 URL into the image property, and it has been working praise the Lord!

Are you using the latest version? This doesn't seem to work for me unfortunately - there **seems** to be checks for mime type

**Comment by lgrammel** [comment]
https://github.com/vercel/ai/pull/3137

**Comment by lgrammel** [comment]
## Identify issue type

Identified as **Feature**  
Confidence: **High**

### Rationale
This asks for new file and media attachment support rather than reporting a failure of an existing promised behavior.

### Evidence
- The description explicitly requests support for additional attachment types such as PDFs, Excel files, and Word documents beyond the SDK's current image support.
- Comments broaden the requested capability to video attachments for models such as Gemini.
- A maintainer linked PR #3137, indicating implementation work toward the requested capability.
