### ISSUE TITLE
Model tried to call unavailable tool

### ISSUE THREAD

**Issue by JasonDevTech** [vercel/ai#1922]
### Description

I am using tools and it seems around 35% of the time I get the following error: 

`NoSuchToolError [AI_NoSuchToolError]: Model tried to call unavailable tool 'multi_tool_use.parallel'. Available tools: search_joke, search_image
at parseToolCall (webpack-internal:///(rsc)/./node_modules/ai/dist/index.mjs:1353:11)
at eval (webpack-internal:///(rsc)/./node_modules/ai/dist/index.mjs:1417:26)
at Array.map (<anonymous>)
at generateText (webpack-internal:///(rsc)/./node_modules/ai/dist/index.mjs:1416:82)`

Is this an expected error? I cannot pinpoint the root cause of this issue.

### Code example

```ts
import { createOpenAI } from '@ai-sdk/openai';
import { generateText, streamText } from 'ai';

const openai = createOpenAI({  compatibility: 'strict'  });

const toolsCompletion = await generateText({
    model: openai(OPEN_AI_MODEL),
    maxTokens: 4096,
    system: 'Some prompt',
    maxToolRoundtrips: 5,
    toolChoice: 'required',
    tools,
    messages
});

completion = await streamText({
    model: openai(OPEN_AI_MODEL),
    maxTokens: 4096,
    system: 'Some prompt',
    messages: toolsCompletion.responseMessages
});

return completion.toTextStreamResponse();
```

### Additional context

AI SDK @ 3.1.30

**Comment by lgrammel** [comment]
This means that the model is trying to call a tool that does not exist. It seems to be an OpenAI issue:

https://community.openai.com/t/model-tries-to-call-unknown-function-multi-tool-use-parallel/490653

**Comment by someguy9** [comment]
Same here Jason

**Comment by wong2** [comment]
same

**Comment by lgrammel** [comment]
Just read through the OpenAI thread again. One potential workaround could be to disable parallel tool calling. Is that an option for you?

**Comment by wong2** [comment]
Is there an options for disable parallel tool calling in AI SDK?

**Comment by wong2** [comment]
@lgrammel Thanks!

**Comment by lgrammel** [comment]
## Identify issue type

Identified as **None**  
Confidence: **High**

### Rationale
This is primarily a support question about provider-generated invalid tool calls. The SDK is correctly reporting the unavailable tool, and no SDK behavior or documentation change is requested.

### Evidence
- The SDK throws `NoSuchToolError` because the model requested an undeclared tool, `multi_tool_use.parallel`.
- The maintainer attributed the behavior to an OpenAI model issue rather than an AI SDK defect.
- The existing `parallelToolCalls` option was provided as a workaround, and the reporter acknowledged it.
