### ISSUE TITLE
onStop callback in the stream callbacks

### ISSUE THREAD

**Issue by Distortedlogic** [vercel/ai#197]
While I was working, i realized it wasnt clear what happens or how to handle when the user calls `stop()` on the frontend.

**Comment by MaxLeiter** [comment]
This is the original issue but #309 has more engagement so closing this in favor of that. Hopefully will open a PR at least partially addressing this soon!

**Comment by lgrammel** [comment]
## Identify issue type

Identified as **None**  
Confidence: **Medium**

### Rationale
This is primarily a superseded duplicate/bookkeeping issue with an underspecified request, so it does not confidently fit bug, documentation, examples, or feature.

### Evidence
- The description says behavior after a frontend `stop()` call is unclear but does not identify a concrete SDK failure or explicit documentation change.
- The issue was closed in favor of #309 because that issue had more engagement.
