### ISSUE TITLE
OpenAI provider does not support all tool names

### ISSUE THREAD

**Issue by mohamedcherifmo** [vercel/ai#1972]
### Description

Create a tool called multi_tool_use.parallel within the tools (to overcome hallucination issue in GTP4-o)
An error is produced
Invalid 'tools[0].function.name': string does not match pattern. Expected a string that matches the pattern '^[a-zA-Z0-9_-]+$'.

### Code example

 const messageStream = await streamUI({
      model: openai('gpt-4o'),
tools: {
 "multi_tool_use.parallel":   {
}

**Comment by lgrammel** [comment]
This is a restriction by OpenAI afaik.

**Comment by lgrammel** [comment]
## Identify issue type

Identified as **Feature**  
Confidence: **High**

### Rationale
The current error reflects an upstream naming restriction rather than broken documented SDK behavior. Supporting arbitrary names through automatic mapping would be a new provider capability.

### Evidence
- A tool named `multi_tool_use.parallel` is rejected because OpenAI requires function names to match `^[a-zA-Z0-9_-]+$`.
- The maintainer states this is an OpenAI restriction and suggests automatic tool-name mapping as a possible enhancement.
