### ISSUE TITLE
Support Azure OpenAI Completions

### ISSUE THREAD

**Issue by Und3rf10w** [vercel/ai#1974]
### Feature Description

Currently the OpenAI package includes support for completion models (e.g. gpt-3.5-turbo-instruct), but the Azure provider does not.

### Use Case

A sample usecase would be for async generation of chat names

### Additional context

~~I submitted a PR #1975, which "should" cover this issue, but may require additional testing.~~

The `@ai-sdk/openai` provider requires patches to conform to the standard where @ai-sdk/azure only `azure-openai-provider.ts`, which has been submitted as PR #1987.

~~Either PR should work, but #1987 is a bit cleaner.~~

**Comment by lgrammel** [comment]
## Identify issue type

Identified as **Feature**  
Confidence: **High**

### Rationale
This requests a new provider capability rather than reporting a failure of existing documented Azure behavior.

### Evidence
- The OpenAI provider supports completion models such as gpt-3.5-turbo-instruct, while the Azure provider does not.
- The issue requests adding Azure OpenAI Completions support and references a proposed implementation in PR #1987.
