### ISSUE TITLE
SvelteKit: support onToolCall / maxToolRoundtrips / tool invocations

### ISSUE THREAD

**Issue by chanmathew** [vercel/ai#1979]
### Description

Hi there,

The onToolCall callback doesn't seem to fire when in a Sveltekit project. See this for repro:
https://stackblitz.com/edit/vercel-ai-sdk-ontoolcall-not-firing?file=src%2Froutes%2F%2Bpage.svelte

I've tested this on local environment as well and same issue.

### Code example

```ts
// client
  const { input, handleSubmit, messages } = useChat({
    async onToolCall({ toolCall }) {
        await console.log(toolCall)
    }
  });
```

```ts
// server
const openai = createOpenAI({
	apiKey: env.OPENAI_API_KEY ?? ''
});

export const POST = (async ({ request }) => {
	const { messages } = await request.json();

	const result = await streamText({
		model: openai('gpt-4o'),
		messages,
		tools: {
			call_tool: tool({
				description: 'Fire this tool call when user asks',
				parameters: z.object({
					tool: z.boolean()
				})
			})
		}
	});

	return result.toAIStreamResponse();
}) satisfies RequestHandler;
```

**Comment by lgrammel** [comment]
`useChat` tool calling is not supported in Svelte yet: https://sdk.vercel.ai/docs/reference/ai-sdk-ui#ui-framework-support

**Comment by chanmathew** [comment]
> `useChat` tool calling is not supported in Svelte yet: https://sdk.vercel.ai/docs/reference/ai-sdk-ui#ui-framework-support

Ah apologies, missed that!

**Comment by MagsMagnoli** [comment]
@lgrammel is there a ticket or some way to track that progress? (if it is in progress even?)

**Comment by lgrammel** [comment]
we could track it here. help would be much appreciated!

**Comment by lgrammel** [comment]
Supported in `@ai-sdk/svelte@0.0.26`

**Comment by lgrammel** [comment]
## Identify issue type

Identified as **Feature**  
Confidence: **High**

### Rationale
The reported callback behavior concerned a capability that was explicitly not yet supported in Svelte, so the issue tracked adding new framework support rather than fixing promised behavior.

### Evidence
- Maintainer clarified that `useChat` tool calling was not supported in Svelte at the time and linked the framework support documentation.
- The issue was then used to track adding Svelte tool-calling support.
- Maintainer later confirmed support was added in `@ai-sdk/svelte@0.0.26`.
