### ISSUE TITLE
Google Gemini System instructions

### ISSUE THREAD

**Issue by tomasmcm** [vercel/ai#1983]
### Feature Description

Google Gemini models now support a "system instructions" parameter that works like the "system messate" in OpenAI.
https://cloud.google.com/vertex-ai/generative-ai/docs/multimodal/send-chat-prompts-gemini

Can you update the google gemini provider to use the new paramter instead of prepending the system prompt as a user message?

### Use Case

Prepending the system prompt as a user message makes it have less importance and users can steer the model away from the intended use case. In order to build role playing assistants, defining the output format, or others as stated here https://cloud.google.com/vertex-ai/generative-ai/docs/multimodal/send-chat-prompts-gemini#system-instructions it's better to use the new system instructions.

**Comment by BleedingDev** [comment]
Would love to work on this, I already cloned the repo, so I'll take a look. :)

**Comment by tomasmcm** [comment]
On closer inspection, it seems the Vertex AI integration already supports system instructions. So it’s a matter to replicating a similar behaviour.

**Comment by lgrammel** [comment]
https://github.com/vercel/ai/pull/2256

**Comment by lgrammel** [comment]
## Identify issue type

Identified as **Feature**  
Confidence: **High**

### Rationale
This is a request to add newly available native system-instruction support to the Google Gemini provider, rather than a failure of previously promised behavior.

### Evidence
- The issue requests updating the Google Gemini provider to use Gemini's newly supported native system-instructions parameter instead of prepending the system prompt as a user message.
- The reporter frames this as adding provider support for a new model capability and explains that native system instructions improve prompt authority.
- A comment notes that Vertex AI already supports this behavior and suggests replicating it in the Google Gemini integration; the maintainer links an implementation pull request.
