### ISSUE TITLE
bug(@ai-sdk/azure): `log_probs` is not be supported for calls to `gpt-4-vision-preview`, causing calls for that deployment to fail entirely

### ISSUE THREAD

**Issue by Und3rf10w** [vercel/ai#2024]
### Description

1. Send a request to Azure OpenAI chat completions, with the deployment pointing to a gpt-4-vision-preview deployment
2. Either specify `logprobs` in the request (defaulting to `false`) or omit it entirely. The `ai-sdk` will send the request with `logprobs` set to false.
3. Receive the following error:

```
error","message":"1 validation error for Request\nbody -> logprobs\n  extra fields not permitted (type=value_error.extra)
```

### Code example

```typescript
import { createAzure } from '@ai-sdk/azure';
import { streamText } from 'ai';
import dotenv from 'dotenv';

dotenv.config();

// create provider instance via factory
const azure = createAzure({
      resourceName: '<redacted>',
      apiKey: '<redacted>',
})

async function main() {
  const result = await streamText({
    model: azure('gpt-4-vision-preview'), // use a deployment pointing to gpt-4-vision-preview
    prompt: 'Invent a new holiday and describe its traditions.',
  });

  for await (const textPart of result.textStream) {
    process.stdout.write(textPart);
  }
}

main().catch(console.error);
```

### Additional context

`log_probs` is not supported in Azure OpenAI specifically only for `gpt-4-vision-preview`, as documented here: https://learn.microsoft.com/en-us/azure/ai-services/openai/reference#chat-completions

![image](https://github.com/vercel/ai/assets/3812012/f08e8e1b-e242-4cec-b78f-e1b5c96b5631)

**Comment by lgrammel** [comment]
## Identify issue type

Identified as **Bug**  
Confidence: **High**

### Rationale
This is a concrete provider compatibility failure: the SDK emits an unsupported request field and otherwise valid calls fail entirely.

### Evidence
- The Azure provider always sends `logprobs: false` even when the caller omits the option.
- Azure rejects the `logprobs` field for `gpt-4-vision-preview`, causing `streamText` requests to fail with a validation error.
- The linked Azure documentation explicitly says this option is unavailable for `gpt-4-vision-preview`.
