### ISSUE TITLE
feat(@ai-sdk/google-vertex): Add Grounding Support

### ISSUE THREAD

**Issue by CaiqueR** [vercel/ai#2026]
### Feature Description

There is a preview feature called Grounding which uses google to search data. You can take a look about it [here](https://github.com/googleapis/nodejs-vertexai?tab=readme-ov-file#grounding-preview).

How can I use it now? Do I need it to be implemented? Is there a way to use it without waiting someone to implement it?

**Comment by davidklaw** [comment]
👀

**Comment by mrlectus** [comment]
Did you solve this?

**Comment by Godrules500** [comment]
This is one of my most requested features that I receive from the user's of my application. Would be awesome if there was at least a workaround in the meantime.

**Comment by lgrammel** [comment]
https://github.com/vercel/ai/pull/2641

**Comment by lgrammel** [comment]
Available in v0.0.27 of the google vertex provider

**Comment by lgrammel** [comment]
## Identify issue type

Identified as **Feature**  
Confidence: **High**

### Rationale
This requests new provider capability rather than reporting broken existing behavior; it was subsequently implemented as grounding support.

### Evidence
- The issue requests support for Google Vertex AI's preview Grounding capability.
- Users describe it as a requested capability and ask whether a workaround exists.
- A maintainer linked the implementation PR and confirmed availability in google-vertex provider v0.0.27.
