### ISSUE TITLE
Anthrophic SDK still doesn't support JSON mode

### ISSUE THREAD

**Issue by NiluK** [vercel/ai#2034]
### Description

I am not sure if this a bug report of a feature request but getting unsupported functionality JSON mode when I try to do a steamObject with it 

UnsupportedFunctionalityError [AI_UnsupportedFunctionalityError]: 'json-mode object generation' functionality not supported.
    at AnthropicMessagesLanguageModel.getArgs (webpack-internal:///(action-browser)/./node_modules/.pnpm/@ai-sdk+anthropic@0.0.21_zod@3.23.8/node_modules/@ai-sdk/anthropic/dist/index.mjs:222:27)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async AnthropicMessagesLanguageModel.doStream (webpack-internal:///(action-browser)/./node_modules/.pnpm/@ai-sdk+anthropic@0.0.21_zod@3.23.8/node_modules/@ai-sdk/anthropic/dist/index.mjs:313:36)
    at async _retryWithExponentialBackoff (webpack-internal:///(action-browser)/./node_modules/.pnpm/ai@3.2.1_openai@4.52.0_react@18.3.1_solid-js@1.8.17_svelte@4.2.15_vue@3.4.26_typescript@5.5.2__zod@3.23.8/node_modules/ai/dist/index.mjs:110:16) {
  functionality: 'json-mode object generation'
}

Now the docs clearly state that it is supported, so not entirely sure what's going on here 
<img width="762" alt="Screenshot 2024-06-21 at 3 55 20 am" src="https://github.com/vercel/ai/assets/14311730/12b24195-aa80-4314-8762-112803ce4816">

### Code example

  ("use server");
  const stream = createStreamableValue();
  (async () => {
    const { partialObjectStream, rawResponse } = await streamObject({
      messages,
      system: `<instructions> 1. You are an expert in document analysis 
      2. You are provided with a document in the form of a file. You must analyze the document and extract the entities from the document. 
      3. If a user provides a user request, you must follow the instructions provided by the user.
      
      </instructions>
      

      <requested_entity_types> ${selectedEntityCategories
        .map((category) => category.title)
        .join(",")} </requested_entity_types>

      
      `,
      model: models[model as keyof typeof models],
      temperature: 0.7,
      mode: "json",
      schema: z.object({
        entities: z.array(
          z.object({
            id: z.string().describe("UUID of a entity."),
            type: z
              .enum(
                selectedEntityCategories.map(
                  (category) => category.type,
                ) as any,
              )
              .describe("Type of a entity."),
            name: z.string().describe("Name of a entity."),
            description: z
              .string()
              .describe("Description of a entity.")
              .min(50),
          }),
        ),
      }),
    });

    for await (const partialObject of partialObjectStream) {
      stream.update(partialObject);
    }
    stream.done();
  })();

**Comment by lgrammel** [comment]
You do not need `mode: "json"`. The automatic mode for anthropic will generate objects using tool calls.

**Comment by must** [comment]
@lgrammel 
> You do not need `mode: "json"`. The automatic mode for anthropic will generate objects using tool calls.

This does not work with thinking though does it?

**Comment by MonkeyLeeT** [comment]
@lgrammel As of today this is still an issue since AI SDK will automatically set tools to have that json tool, and tool_choice to be {"type": "tool", "name": "json"} for structured output / generateObject() call.

And Anthropic will complain that `Thinking may not be enabled when tool_choice forces tool use.`

Behavior in https://github.com/vercel/ai/blob/main/packages/anthropic/src/anthropic-messages-language-model.ts#L236 needs to be changed so that tool_choice can be auto (and tools can still contain that json tool).

**Comment by lgrammel** [comment]
## Identify issue type

Identified as **Bug**  
Confidence: **High**

### Rationale
Although the original explicit JSON-mode error reflects an unsupported mode, subsequent reports establish a concrete failure in the SDK’s automatic object-generation behavior when Anthropic thinking is enabled.

### Evidence
- Explicit `mode: "json"` throws `AI_UnsupportedFunctionalityError` for Anthropic despite object generation being listed as supported.
- A maintainer clarified that Anthropic object generation uses tool calls in automatic mode rather than native JSON mode.
- Later comments report that automatic `generateObject()` still fails with Anthropic thinking because the SDK forces `tool_choice`, which Anthropic rejects with: `Thinking may not be enabled when tool_choice forces tool use.`
