### ISSUE TITLE
Feature parity for `useChat` SolidJS

### ISSUE THREAD

**Issue by spiritledsoftware** [vercel/ai#2062]
### Feature Description

The solid version of `useChat` is a bit behind in terms of features, especially in regards to client-side tool calls and round trips.

### Additional context

I can take a wack at this change myself and submit a PR

**Comment by lgrammel** [comment]
## Identify issue type

Identified as **Feature**  
Confidence: **High**

### Rationale
This requests expanded capabilities and parity for the SolidJS API rather than reporting a concrete failure of existing behavior.

### Evidence
- The issue states that SolidJS `useChat` lacks features available in other versions.
- It specifically requests parity for client-side tool calls and round trips.
- No existing documented SolidJS behavior is described as broken.
