### ISSUE TITLE
Strange question marks in cyrillic symbols are still there

### ISSUE THREAD

**Issue by TimPchelintsev** [vercel/ai#209]
Original issue #155  was closed, but It seems issue is still present. Question marks still appear on https://chat.vercel.ai and in my product even after upgrade to new version with ```stream: true``` fix.
Recent screenshot from https://chat.verce.ai:
<img width="730" alt="Screenshot 2023-06-23 at 10 43 30" src="https://github.com/vercel-labs/ai/assets/3499434/e0f0a6f3-48f1-42b0-afb7-38ab81ce10a5">

_Originally posted by @TimPchelintsev in https://github.com/vercel-labs/ai/issues/155#issuecomment-1603693735_

**Comment by jridgewell** [comment]
Can you log out the individual tokens that are received? Or can you explain the steps to reproduce (I don't know how to get Cyrillic responses) so we can debug?

**Comment by TimPchelintsev** [comment]
Hi @jridgewell sure:
1.  Bug is present in my system, but also on https://chat.vercel.ai, so maybe it will be convenient to debug there?
2. ChatGPT is multilingual so we can ask any question in Russian language to trigger response with cyrillic symbols,
    l personaly used ```"Расскажи сказку"```("Tell me a fairytail" in English)
3. So to reproduce please visit https://chat.vercel.ai and copy-paste ```"Расскажи сказку"```.
4. Question marks seems to appear in completely random positions, but they appear almost every time in long enough AI response.

Please tell me if you need more information or I can help somehow, this bug is really annoying and I think it can be present not only in cyrillic symbols, but in broader range of symbols too.

**P.S.**
I should mention that bug is not present on https://chat.openai.com, so problem should be somewhere in-between.

**Comment by MaxLeiter** [comment]
Is this still an issue @TimPchelintsev? I can't reproduce it anymore


<img width="943" alt="CleanShot 2023-08-17 at 16 22 43@2x" src="https://github.com/vercel/ai/assets/8675906/b5d52b2a-c1f6-454b-abca-44e3b2e2b44e">

**Comment by TimPchelintsev** [comment]
Hi @MaxLeiter, thanks for your response, you made my day.

Well, it seems we finally nailed it.

First I checked https://chat.vercel.ai and confirmed that I did not see bug there anymore.

Than I upgraded all related packages, still saw bug in my project, but after comparing codebases it seems
I found solution:https://github.com/vercel/ai/blob/b84af19b2b2b54b045558d35925abcfcff8d01fa/packages/core/shared/utils.ts#L29

As I used only server side code from ```ai``` package and implemented parsing streaming response in my UI myself,
I missed the ```{ stream: true }``` part in my implementation.

Thank you guys you are legends!

**Comment by lgrammel** [comment]
## Identify issue type

Identified as **Bug**  
Confidence: **High**

### Rationale
This reports a concrete character-corruption failure in existing streaming behavior. Although the hosted app was subsequently fixed and the reporter's custom implementation required configuration, the issue itself concerns broken output rather than a request for new capability.

### Evidence
- The reporter observed replacement characters appearing at random positions in streamed Cyrillic responses on chat.vercel.ai and provided reproducible steps.
- The issue was later no longer reproducible on chat.vercel.ai; the remaining occurrence in the reporter's project was traced to omitting the required `{ stream: true }` option in custom response parsing.
