### ISSUE TITLE
Support streaming tools in streamText, streamUI

### ISSUE THREAD

**Issue by sullyo** [vercel/ai#2101]
### Feature Description

Similar to streamObject, support streaming via streamText and streamUI. This lets us create better interfaces for various tools to show their progress.

### Use Case

Some tool arguments take a while to stream. For example running a code execution tool usually takes much longer for the code arguments to generate, sometimes upwards of 5-10s. Right now there is way to currently show this progress and the user is left with a loading indicator.

**Comment by sullyo** [comment]
bumping this - would atleast be nice to know when a tool name is invoked, even as the model generates the args

**Comment by lgrammel** [comment]
https://github.com/vercel/ai/pull/2295

**Comment by lgrammel** [comment]
`streamUI` : https://github.com/vercel/ai/issues/2915

**Comment by lgrammel** [comment]
## Identify issue type

Identified as **Feature**  
Confidence: **High**

### Rationale
This is a request for a new SDK capability and interface enhancement, not a failure of documented existing behavior.

### Evidence
- The issue requests new streaming support for tool calls and their arguments in `streamText` and `streamUI`.
- The stated goal is to expose tool-generation progress instead of showing only a loading indicator.
- A maintainer linked a PR adding tool-call streaming for `streamText`/`useChat` and a separate issue for `streamUI`.
