### ISSUE TITLE
Tool calling visibility

### ISSUE THREAD

**Issue by zvictor** [vercel/ai#2102]
### Feature Description

While [porting gemini-chatbot to the Anthropic's provider](https://github.com/zvictor/anthropic-chatbot), I faced some unexpected challenges related to tool/function calling.

1. First and foremost, it's not possible to gain any visibility over the tool calling process because all the parsing + validation + error handling of messages received from the provider happen opaquely inside AI SDK. The `tool-call` message can't be accessed in any way if it's invalid.

2. Due to 1️⃣, one is incapable of performing any post-operation using the data from the `tool-call` message, such as requesting the LLM to fix the broken tool calling.

Instead, ideally, it should be possible to:

1. **Activate logging or event triggering** in order to listen to (and **ideally modify**) problematic messages **before** they throw errors that terminate the request.

2. **Take action on the invalid message**, such as: send a new request to the LLM containing the tool-call message generated along side the `AI_InvalidToolArgumentsError`, `AI_JSONParseError`, or whatever error message it caused, requesting the LLM for a fix.

### Use Case

A developer receives too many `AI_InvalidToolArgumentsError` errors and would like to retry the failing requests while appending the tool-call message generated along side the error message.

**Comment by zvictor** [comment]
The current workaround is to [throw the error up](https://github.com/zvictor/anthropic-chatbot/blob/e89e79eb59ec4c39fe947ab921c3e02262a0940e/lib/chat/actions.tsx#L268-L269) and then [extract info from the error message](https://github.com/zvictor/anthropic-chatbot/blob/e89e79eb59ec4c39fe947ab921c3e02262a0940e/lib/chat/actions.tsx#L205-L215).

```ts

**Comment by zvictor** [comment]
I am sorry, I closed the issue by accident 🤗

**Comment by ilovetea** [comment]
Waiting for this as well.

**Comment by lgrammel** [comment]
Please check out our new tool call repair functionality: https://sdk.vercel.ai/docs/ai-sdk-core/tools-and-tool-calling#tool-call-repair

**Comment by lgrammel** [comment]
## Identify issue type

Identified as **Feature**  
Confidence: **High**

### Rationale
This requests new observability and repair capabilities for invalid tool calls rather than reporting behavior that contradicted an existing promise.

### Evidence
- Invalid tool-call messages were handled opaquely, preventing inspection or recovery before validation errors terminated the request.
- The reporter requested logging/events, interception or modification of invalid messages, and retrying with the original tool-call data.
- A maintainer later pointed to newly added tool-call repair functionality addressing the requested recovery use case.
