### ISSUE TITLE
Azure Provider: add api version parameter

### ISSUE THREAD

**Issue by re-oka** [vercel/ai#2104]
### Feature Description

I want to add a parameter for api version in Azure Provider customization settings.  
Currently it is set to `2024-05-01-preview`. (The preview version closes early ... we want to customize api version)
- https://github.com/vercel/ai/blob/main/packages/azure/src/azure-openai-provider.ts#L99

### Use Case

Users will be able to select GA or Preview versions. It's greater convenience.

**Comment by lgrammel** [comment]
Our implementation relies on a specific API version. Making it changeable would mean you can break our implementation, and we don't expose the Azure API to begin with. What would you gain by changing the API version?

**Comment by lgrammel** [comment]
won't fix, because we rely on a specific api version and changing it could break the provider

**Comment by lgrammel** [comment]
## Identify issue type

Identified as **Feature**  
Confidence: **High**

### Rationale
This is a request for a new provider configuration capability, even though maintainers marked it as won't fix. It does not report a concrete failure in existing behavior.

### Evidence
- The requester asks for a new Azure Provider customization parameter to select GA or preview API versions.
- The current fixed API version is not described as malfunctioning or contradicting documented behavior.
- A maintainer declined the request because the provider relies on a specific API version and allowing changes could break it.
