### ISSUE TITLE
Impossible to repeatedly create new threads using useAssistant hook

### ISSUE THREAD

**Issue by rromikas** [vercel/ai#2163]
### Description

Using useAssistant hook, creating new thread works only first time. Later when you pass undefined as threadId, new messages get added to previous thread.

### Code example

 In app new thread should be created when new messages are sent and activeThreadId is set to undefined

```
const [activeThreadId, setActiveThreadId] = useState<string>();

  const { status, messages, setMessages, input, submitMessage, handleInputChange, stop, threadId } = useAssistant({
    api: "/api/assistant",
    threadId: activeThreadId,
  });
```

**Comment by jeremyphilemon** [comment]
The `useAssistant` hook does not support updating `threadId`, so you need functionality like `setThreadId` to have control over creating/updating threads you're trying to achieve

Since #1673 is tracking this feature request, I'll close this as duplicate

**Comment by lgrammel** [comment]
## Identify issue type

Identified as **Feature**  
Confidence: **High**

### Rationale
The requested ability to reset or update a thread ID is a new hook capability rather than a failure of supported behavior.

### Evidence
- The hook does not support updating `threadId` after initialization.
- A maintainer states that functionality such as `setThreadId` is needed and that issue #1673 already tracks this feature request.
