### ISSUE TITLE
Cannot pass in parts into system message

### ISSUE THREAD

**Issue by Godrules500** [vercel/ai#2174]
### Description

When using gemini 1.5 pro i have found that I have better results when passing in the text parts as the systemInstruction.  In trying to do that with @ai/vertex and streamText it is erroring because it is not handling the system instructions the way google does.

### Code example

```
          system: {
            parts: [
              {
                text: "When someone says something along the lines of 'Thank you', replace you're welcome with you are most certainly welcome. Use fewer emojis."
              }
            ]
          },
```

### Additional context

If I pass in the system instructions as system: "When someone says something along the lines of 'Thank you', replace you're welcome with you are most certainly welcome. Use fewer emojis." I get "you are most certainly welcome" pretty frequently at weird times.

I tried this with google/vertexai and did not seem to run across the issue when using parts, but did when passing in a regular string.

**Comment by lgrammel** [comment]
Can you provide an example of how you pass parts? System messages do not support parts, so they would be rendered as `Object object`. Are you using typescript?

**Comment by lgrammel** [comment]
With https://github.com/vercel/ai/pull/2259 multiple system messages in the ai sdk prompt will get converted into a system instruction with multiple parts on the vertex level.

**Comment by lgrammel** [comment]
## Identify issue type

Identified as **Feature**  
Confidence: **High**

### Rationale
This requests expanded system-message and provider behavior rather than reporting a failure of a supported API. The maintainer-confirmed solution adds a new way to produce multipart Vertex system instructions.

### Evidence
- The reporter wants Vertex/Gemini system instructions to accept structured `parts` instead of only a string.
- A maintainer states that AI SDK system messages do not support parts, so the object would be rendered as `[Object object]`.
- The linked PR adds conversion of multiple AI SDK system messages into a Vertex system instruction containing multiple parts.
