### ISSUE TITLE
 toolResults and toolCalls are always empty when maxToolRoundtrips is set higher than 0

### ISSUE THREAD

**Issue by ErkanTurut** [vercel/ai#2176]
### Description

When using the `generateText` function, I have noticed that both `toolResults` and `toolCalls` are always empty if `maxToolRoundtrips` is set to a value higher than 0. I am unsure if this behavior is expected, but it would be beneficial to have access to `toolResults` even when there is a roundtrip.

**Steps to Reproduce:**
1. Call the `generateText` function with `maxToolRoundtrips` set to a value higher than 0.
2. Observe that `toolResults` and `toolCalls` are empty.

**Expected Behavior:**
`toolResults` should still be populated with data even when there is a roundtrip.

**Environment:**
- Version: 3.2.15

Thank you 😄

**Comment by samelamin** [comment]
I am also seeing this issue. Is there a fix beside setting maxToolRoundtrips to 0?

**Comment by lgrammel** [comment]
I will add something like "calls" to the result object that will contain all llm calls. In the meantime, the information should also be included in `responseMessages` ( https://sdk.vercel.ai/docs/reference/ai-sdk-core/generate-text#response-messages ), but it would need to be extracted.

**Comment by samelamin-discovery** [comment]
@lgrammel since we are using a ui, the documentation leads me to believe we need to use `streamText`

a quick question, am I able to use `maxToolRoundtrips` with `streamText`?

**Comment by samelamin** [comment]
@lgrammel since we are using a ui, the documentation leads me to believe we need to use streamText

a quick question, am I able to use maxToolRoundtrips with streamText?

**Comment by ErkanTurut** [comment]
> @lgrammel since we are using a ui, the documentation leads me to believe we need to use streamText
> 
> a quick question, am I able to use maxToolRoundtrips with streamText?

Hi @samelamin , not yet but the enhancement is already on track you can follow this issue #1943

**Comment by lgrammel** [comment]
https://github.com/vercel/ai/pull/2283

**Comment by lgrammel** [comment]
The behavior is as expected (it only contains the information from the last call). However, you can retrieve all tool calls via the `roundtrips` property in `ai@3.2.24` (see https://sdk.vercel.ai/docs/ai-sdk-core/agents#accessing-information-from-all-roundtrips).

**Comment by lgrammel** [comment]
## Identify issue type

Identified as **Feature**  
Confidence: **High**

### Rationale
This requests expanded access to information from all tool roundtrips rather than correcting behavior that maintainers considered broken. The resulting API expansion is a feature.

### Evidence
- Maintainer states the existing result only contains information from the last model call and that this behavior is expected.
- The requested access to tool calls and results across all roundtrips required a new `roundtrips` result property, released in `ai@3.2.24`.
- A pull request implementing the expanded result capability was linked.
