### ISSUE TITLE
Nest.js support

### ISSUE THREAD

**Issue by zandko** [vercel/ai#221]

**Comment by MaxLeiter** [comment]
We have no issues supporting nestjs, pull requests welcome!

**Comment by zandko** [comment]
有相关例子吗？获取可以通过一些方式兼容进行使用，但无法在nestjs中直接使用

**Comment by zandko** [comment]
Are there any relevant examples? The acquisition can be used compatibly through some methods, but cannot be directly used in NestJS.

**Comment by g3r4n** [comment]
I manage to make it work with the following code:
```
@Post()
  async async(@Body() { messages }: {
  messages: CoreMessage[];
}, @Res() res: Response) {
    const result = await streamText({
      model: openai('gpt-3.5-turbo'),
      messages,
    });
    return result.pipeAIStreamToResponse(res);
  }
```

**Comment by dev-luizf** [comment]
> I manage to make it work with the following code:
> 
> ```
> @Post()
>   async async(@Body() { messages }: {
>   messages: CoreMessage[];
> }, @Res() res: Response) {
>     const result = await streamText({
>       model: openai('gpt-3.5-turbo'),
>       messages,
>     });
>     return result.pipeAIStreamToResponse(res);
>   }
> ```

I used this approach and had problems with my onFinish function not being called in the frontend using useChat hook. I managed to fix it by using the same version of the ai package in both my next.js app and nest.js.

**Comment by FranckPoingt** [comment]
Hi, how is the support going is there any PR to support?
I'm using a Nestjs backend with some Langchain methods, tried to pass the response using the LangchainAdapter to consume on my Nextjs frontend but need to use @Sse and return an Observable which messes up with the data format the ai sdk is expecting so happy to help figuring out a solution, or if someone has a workaround that could help, thanks

**Comment by lgrammel** [comment]
Nest.js example: https://sdk.vercel.ai/examples/api-servers/nest

**Comment by lgrammel** [comment]
## Identify issue type

Identified as **Examples**  
Confidence: **High**

### Rationale
The discussion centers on demonstrating existing NestJS compatibility through sample code rather than changing SDK behavior, and concludes with a runnable Nest.js example.

### Evidence
- The issue title requests Nest.js support but provides no concrete failure report.
- A commenter explicitly asks for relevant NestJS examples.
- A maintainer states that NestJS is supported and later links to a dedicated Nest.js API server example.
