### ISSUE TITLE
Bedrock: can't use AWS metadata service for authentication

### ISSUE THREAD

**Issue by brianprost** [vercel/ai#2216]
### Description

It seems like the only way that Bedrock can be used now is by generating access credentials, which is not the most secure nor standard way to handle permissions for workloads running on AWS.

In the legacy Bedrock provider, a deployed compute instance could still authenticate with the Bedrock API using the metadata service, but when transitioning to AI SDK 3.x / `@ai-sdk/amazon-bedrock`, deployed environments can no longer authenticate.

### Code example

Things work fine locally, where I'm authenticated with AWS SSO CLI. All of these work fine locally, but not when deployed

```typescript
const bedrock = createAmazonBedrock({
    bedrockOptions: {
      credentials: {
        accessKeyId: process.env.AWS_ACCESS_KEY_ID!,
        secretAccessKey: process.env.AWS_SECRET_ACCESS_KEY!,
        sessionToken: process.env.AWS_SESSION_TOKEN!
      }
    }
  })
```

### Additional context

My deployed environment is a NextJS `14.2.4` app in a Docker container (derived from the [official example](https://github.com/vercel/next.js/blob/canary/examples/with-docker-multi-env/docker/production/Dockerfile)) on a ECS service in `us-east-1`

**Comment by lgrammel** [comment]
@brianprost the authentication information are used as configuration options for creating a `BedrockRuntimeClient` ( https://github.com/vercel/ai/blob/main/packages/amazon-bedrock/src/bedrock-provider.ts#L47 ). You can use any authentication mechanism that works with the Bedrock SDK.

**Comment by lgrammel** [comment]
## Identify issue type

Identified as **None**  
Confidence: **Medium**

### Rationale
The maintainer indicates metadata-based authentication is already supported through the underlying AWS SDK configuration, making this primarily a configuration/support question rather than a confirmed SDK defect or new capability request.

### Evidence
- Reporter says ECS workloads no longer authenticate through AWS metadata after migrating to `@ai-sdk/amazon-bedrock`.
- The shown configuration explicitly supplies environment-based credentials, which may prevent use of the default AWS credential provider chain.
- Maintainer clarifies that `bedrockOptions` configure the AWS `BedrockRuntimeClient` and any authentication mechanism supported by the AWS Bedrock SDK can be used.
