### ISSUE TITLE
AI_TypeValidationError: Optional type validation in generateObject function. 

### ISSUE THREAD

**Issue by ashbuilds** [vercel/ai#2265]
### Feature Description

Hi, Object generation using generateObject, failed to response if the value does not match the schema, but in some cases we want to get the value even though its not according to schema. Lets say to log it for later use or debugging your prompts.

I think it would be great to have this optional by passing a boolean down to this function. It can be `disableTypeValidation` or something which defaults to `false`.

Where its happening:
https://github.com/vercel/ai/blob/4dfe0b0004cca9643024a080c038237a3abd360b/packages/provider-utils/src/parse-json.ts#L42

Issue screenshot:
<img width="884" alt="Screenshot 2024-07-12 at 19 10 15" src="https://github.com/user-attachments/assets/60ce6f12-8324-425e-bc03-70651004d7a2">

**Comment by bernaferrari** [comment]
me too... I hate that. It pollutes the console.log. I already deal with issues in the schema myself, I don't need that.

**Comment by ashbuilds** [comment]
> me too... I hate that. It pollutes the console.log. I already deal with issues in the schema myself, I don't need that. The error log here is like 100k LOC, it is endless. I even needed to increase the scrollback from 100k to unlimited to work.

💯 Going through the same trouble + lost my credits without getting any data back :crying-sunglasses-cowboy:

**Comment by ashbuilds** [comment]
I think there should be a penalty on LLM's if data is not according to your schema 👊😅

**Comment by OzeroDev** [comment]
What model are using with the generateObject function. I realized on my code how when using the gpt-3.5-turbo model, I would get the AI_TypeValidationError on like every other call, but when I switched to gpt-4o model, the error has seemed to go away (not sure if it's fully gone though).

**Comment by bernaferrari** [comment]
I'm using 4o.

**Comment by lgrammel** [comment]
a) I'll look into fixing the log pollution, this seems like a bug (not a schema validation error)
b) re schema design, I recommend: https://sdk.vercel.ai/docs/ai-sdk-core/tools-and-tool-calling#prompt-engineering-with-tools (also applies to generateObject)
c) i'll think about how to best disable the checks - this requires a little more consideration since it overlaps with the custom schema libraries feature request

**Comment by lgrammel** [comment]
Here is the relevant `generate-object` code:

```
  const parseResult = safeParseJSON({ text: result, schema });

  if (!parseResult.success) {
    throw parseResult.error;
  }

  return new GenerateObjectResult({
    object: parseResult.value,
    finishReason,
    usage: calculateCompletionTokenUsage(usage),
    warnings,
    rawResponse,
    logprobs,
  });
  ```

1) re log polution
The console.log / unhandled uncaught exception is most likely due to missing error handling. My recommended solution is a try...catch block. When the result object does not match your expected schema, you need to handle it as a separate case because you cannot rely on the structure of the returned data. You can e.g. log, ignore, or recover in that catch block.

2) re original values / objects
- `JSONParseError` contains a `text` property that you can use to get the original text
- `TypeValidationError` contains a `value` property with the parsed value that failed validation

Putting the 2 together, you can do the following:

```ts
async function example<T>(schema: z.Schema<T>): Promise<
  | {
      type: 'success';
      object: T;
    }
  | {
      type: 'parse-error';
      text: string;
    }
  | {
      type: 'validation-error';
      value: unknown;
    }
  | {
      type: 'unknown-error';
      error: unknown;
    }
> {
  try {
    const result = await generateObject({
      model: openai('gpt-4-turbo'),
      schema,
      prompt: 'Generate a lasagna recipe.',
    });

    return {
      type: 'success',
      object: result.object,
    };
  } catch (error) {
    if (TypeValidationError.isTypeValidationError(error)) {
      return {
        type: 'validation-error',
        value: error.value,
      };
    } else if (JSONParseError.isJSONParseError(error)) {
      return {
        type: 'parse-error',
        text: error.text,
      };
    } else {
      return {
        type: 'unknown-error',
        error,
      };
    }
  }
}
``` 

Please let me know if this solution works for you.

**Comment by bernaferrari** [comment]
I was expecting either onFinish (error) to not print the exception, or a
"throwIfInvalidSchema" boolean to disable the throw/catch because now I
would need to duplicate some logic and handle in two places instead of one.
This will make ai sdk much harder to use since I expect the structure to be
wrong but still valid.

**Comment by lgrammel** [comment]
`onFinish` is for `streamObject`. This issue is for `generateObject`. Would you mind opening a separate ticket for `streamObject` errors / onFinish? This smells like a bug

**Comment by bernaferrari** [comment]
Ok. I'm getting this issue on streamObject.

**Comment by lgrammel** [comment]
@bernaferrari https://github.com/vercel/ai/pull/2321

**Comment by ashbuilds** [comment]
Thanks for looking into it @lgrammel , My issue is not about that it throws a lot of logs in case result does not match. I simply want to have an option to get the data back that is generated, it can be in `catch` block with the error but having it not returned to the calling function and lost it just because it doesn't match the schema is not idea. 

Sometimes the generated data is huge and you might have a case where you can pass the mismatched data to tell ai to fix it or improve upon. 🙏

**Comment by lgrammel** [comment]
@ashbuilds please check out this guide: https://sdk.vercel.ai/docs/ai-sdk-core/generating-structured-data#error-handling

**Comment by marclelamy** [comment]
I'm getting the same issue but it's not always reproducible depending on the output. It happens to me with `streamText().toAIStream()`. I can log the toAIStream onStart callback but then it throws the error

**Comment by lgrammel** [comment]
## Identify issue type

Identified as **Feature**  
Confidence: **High**

### Rationale
The core request is an API enhancement allowing callers to bypass schema validation or avoid throwing, rather than a failure of the documented `generateObject` behavior.

### Evidence
- The issue explicitly requests a new `disableTypeValidation` or `throwIfInvalidSchema` option for `generateObject`.
- The maintainer explained that schema validation failures are currently thrown by design and that the unvalidated value is available through `TypeValidationError.value`.
- The separate `streamObject` logging/onFinish behavior was identified as a possible bug and redirected to another ticket.
