### ISSUE TITLE
Model Registry non-standard parameters

### ISSUE THREAD

**Issue by crtnx** [vercel/ai#2270]
### Feature Description

The current implementation of experimental model registry doesn't allow any parameters except a model id. There is no way to pass optional non-standard parameters to a model, like topK. The change should be simple enough (just for illustration):

```
languageModel(id: string, options: any): LanguageModel {
    const [providerId, modelId] = this.splitId(id);
    const model = this.getProvider(providerId).languageModel?.(modelId, options);

    if (model == null) {
      throw new NoSuchModelError({ modelId: id, modelType: 'language model' });
    }

    return model;
  }
```

**Comment by lgrammel** [comment]
You can now use custom providers for this purpose:
* https://sdk.vercel.ai/docs/ai-sdk-core/provider-management#custom-providers

In the future, we may add support for provider-specific options on the request level (AI functions parameter) as well.

**Comment by lgrammel** [comment]
## Identify issue type

Identified as **Feature**  
Confidence: **High**

### Rationale
This requests an API expansion for passing non-standard provider parameters rather than reporting a failure of documented behavior.

### Evidence
- The model registry currently accepts only a model ID, and the issue requests an additional options parameter for provider-specific settings such as topK.
- The maintainer points to custom providers as the current workaround and notes that request-level provider-specific options may be added in the future.
