### ISSUE TITLE
stop_sequences

### ISSUE THREAD

**Issue by FrancescoSaverioZuppichini** [vercel/ai#2285]
### Feature Description

Dear all,

Thank you for the amazing package, is there something similar to `stop_sequences` to defined when to stop the generation like in the [antropic apis](https://docs.anthropic.com/en/api/complete)? 

### Use Case

Very useful to save tokens

**Comment by lgrammel** [comment]
support landed in main https://github.com/vercel/ai/pull/2371

**Comment by lgrammel** [comment]
## Identify issue type

Identified as **Feature**  
Confidence: **High**

### Rationale
This is a request for a new generation-control capability rather than a report of broken existing behavior.

### Evidence
- The issue asks for a capability equivalent to Anthropic's `stop_sequences` to control when generation stops.
- The maintainer states that support landed in PR #2371, confirming this was implemented as new functionality.
