### ISSUE TITLE
experimental_useObject onFinish

### ISSUE THREAD

**Issue by blechatellier** [vercel/ai#2289]
Can we add an `onFinish` method to `experimental_useObject` similar to `useCompletion`?

**Comment by clasnake** [comment]
+1 Same ask here. This will be really helpful. Before that, is there any workaround that can enable performing custom logic when the call finishes? Thanks very much.

**Comment by lgrammel** [comment]
https://github.com/vercel/ai/pull/2500

**Comment by blechatellier** [comment]
@lgrammel thanks 🙏🏼

**Comment by clasnake** [comment]
Thanks @lgrammel

**Comment by lgrammel** [comment]
## Identify issue type

Identified as **Feature**  
Confidence: **High**

### Rationale
This requests a new callback capability for `experimental_useObject`, rather than reporting broken or incorrect existing behavior.

### Evidence
- The issue asks to add an `onFinish` callback to `experimental_useObject`, analogous to the existing callback in `useCompletion`.
- A commenter confirms the callback would enable custom logic after a call finishes.
- A maintainer links pull request #2500, indicating implementation of the requested capability.
