### ISSUE TITLE
Let AI use multiple times tools before answering

### ISSUE THREAD

**Issue by louis030195** [vercel/ai#2301]
### Feature Description

"Can you tell me the weather tomorrow and on thursday" 
->
Now AI would make a query and then answer the question

Would be cool if the AI could make multiple requests like one for tomorrow and one for thursday. I very often implement this use case with LLM (been using LLM since gpt-1)

example use case: https://github.com/louis030195/screen-pipe/blob/57dc0fce2f10cbd1053f2f3fac3cd69d4ae194ba/examples/ts/rag-over-your-life-in-obsidian/screenpipe.js#L118

### Use Case

see above

### Additional context

I've seen the "agent" parts in your doc. didn't get it

I understand that sometimes you want a loop with LLM to let them iterate, like here: https://github.com/llm-edge/hal-9100/blob/5acaf971309f344b6cb25572ae0f71424872ffdc/hal-9100-core/src/code_interpreter.rs#L70

but didnt understand the UX at all, think it's different than what i ask here though

**Comment by lgrammel** [comment]
There are different cases:

a) you want the llm to use tools, the tools should be executed automatically, the llm should use the tool result, and it all should be flexible. you don't need to stream to the user. then you can use `maxToolRoundtrips`: https://sdk.vercel.ai/docs/ai-sdk-core/agents

b) you have a fixed script, e.g. force the llm to generate a tool calls, then do something with it, then invoke the llm with a different structure: use generateText / generateObject and Javascript code to write out that fixed setup

c) you need to have an interactive chatbot use tools: use `streamText` + `useChat` in combination: https://sdk.vercel.ai/docs/ai-sdk-ui/chatbot-with-tool-calling

I'm not sure this covers what you are looking for. I looked at your code but didn't fully understand what you want to achieve. Would you mind writing down an example use case step by step?

**Comment by kdawgwilk** [comment]
@lgrammel unfortunately `a` is what we are going for but we are also using `streamText` which does not support `maxToolRoundtrips` 😞 Looking forward to #1943 being implemented so we don't have to hack together workarounds to support tool calling with streaming

**Comment by cosbgn** [comment]
@lgrammel this is not completed yet right? can we re-open this?

**Comment by Mnigos** [comment]
I think this should be reopened.

**Comment by aayush-kapoor** [comment]
Marking this as closed for now - if you face any regression or have a similar problem after migrating to the latest AI SDK version, please feel free to open a new issue (with possible reproduction)

**Comment by lgrammel** [comment]
## Identify issue type

Identified as **Feature**  
Confidence: **High**

### Rationale
This is a request for expanded multi-step or parallel tool-calling behavior, not a concrete failure of documented existing behavior. The workaround and later closure do not change the original enhancement request.

### Evidence
- The issue requests allowing an LLM to make multiple tool requests before producing its answer.
- A commenter notes that streaming lacked the equivalent of `maxToolRoundtrips`, requiring workarounds at that time.
- The reporter found an application-level solution using array parameters and parallel queries and stated the problem was solved for their use case.
