### ISSUE TITLE
Add `baseURL` and `apiVersion` to the Azure OpenAI Provider

### ISSUE THREAD

**Issue by karl-richter** [vercel/ai#2312]
### Feature Description

Most providers currently support a `baseURL` parameter that allows to use a custom proxy endpoint with the respective provider. For the Azure Provider this option is currently missing, as only the `resourceName` parameter is supported that is used to construct the baseURL in the background. The construction of the URL currently looks as follows:
```js
const url = ({ path, modelId }: { path: string; modelId: string }) =>
    `https://${getResourceName()}.openai.azure.com/openai/deployments/${modelId}${path}?api-version=2024-05-01-preview`;
```

I'd propose to add an alternative option to the `AzureOpenAIProviderSettings` that gives more control over how the URL is constructed. It could look something like this:
```js
const url = ({ path, modelId }: { path: string; modelId: string }) =>
    getBaseUrl()
      ? `${getBaseUrl()}/${modelId}${path}?api-version=${getApiVersion()}`
      : `https://${getResourceName()}.openai.azure.com/openai/deployments/${modelId}${path}?api-version=${getApiVersion()}`;
```

### Use Case

This would be needed to support Proxy API's to the Azure OpenAI service.

**Comment by lgrammel** [comment]
`baseURL` can be configured (change landed in main)

**Comment by lgrammel** [comment]
## Identify issue type

Identified as **Feature**  
Confidence: **High**

### Rationale
The issue requests expanded Azure OpenAI provider configuration to support custom proxy endpoints and API versions, rather than reporting a failure of promised behavior.

### Evidence
- The Azure provider constructs its endpoint from `resourceName` and a fixed API version, preventing custom proxy endpoint configuration.
- The reporter requests configurable `baseURL` and `apiVersion` settings as new provider capabilities.
- A maintainer states that configurable `baseURL` subsequently landed in `main`.
