### ISSUE TITLE
Text chunk JSON parsing error

### ISSUE THREAD

**Issue by okanasl** [vercel/ai#2319]
### Description

`SyntaxError: Unexpected non-whitespace character after JSON at X` error is thrown if the text chunk contains escaped quote mark `\"` in text when parsing a string chunk In `parseStreamPart` function [here](https://github.com/vercel/ai/blob/1bc0250478f01eb7c6a515037a6ff35041e9feaf/packages/ui-utils/src/stream-parts.ts#L429),

### Code example

In our case, it is parsing `\"(\"\"` string which results in JSON parsing error. Also encountered same with string `\" \"\"`

### Additional context

Here is screenshots from debugger in case it is useful:
Values:
![Screenshot from 2024-07-18 09-54-34](https://github.com/user-attachments/assets/7fe6451e-3071-4d11-9f9d-3a25d387689e)

Error:
![Screenshot from 2024-07-18 09-55-07](https://github.com/user-attachments/assets/eef60e06-67aa-4930-87e5-bdc15364e5f8)

**Comment by lgrammel** [comment]
How did you create the stream part that is being parsed? It looks that the formatting is wrong.

**Comment by okanasl** [comment]
Oh okay, I thought we were using unmodified LLM output but probably llama-index makes some modifications. Thanks for the reply!

**Comment by lgrammel** [comment]
## Identify issue type

Identified as **None**  
Confidence: **High**

### Rationale
The reported exception resulted from malformed or externally modified stream data rather than a confirmed AI SDK failure. The exchange concluded as a support clarification, so it does not establish a bug or request a product change.

### Evidence
- The parser received a stream part whose JSON formatting appeared invalid.
- A maintainer asked how the stream part was created and noted that its formatting looked wrong.
- The reporter acknowledged that llama-index probably modified the LLM output and thanked the maintainer for resolving the question.
