### ISSUE TITLE
set createAt timestamp for user messages when they are created

### ISSUE THREAD

**Issue by MahmoudvMarey** [vercel/ai#2326]
### Feature Description

I just found that who are making changes on the useChat ( React ), has abundantly removed the "createdAt" from user message,
and in fact the ai message that came from the useChat response "role: assistant" are having "createdAt" normally, but "role: user" don't have, that's weird  

also why you guys removed "message.ui" from Message[] ??

I didn't understand these 2 changes, since they are important

### Use Case

chat application where it shows every message date "message.createdAt", and if message have a custom UI, it shows under "message.ui"

### Additional context

I make a pull request and no one reply on the issue

**Comment by lgrammel** [comment]
a) message.ui was initial attempt at rsc and was experimental. it has been replaced with AI SDK RSC. In addition, it leads to compatibility issues when using the AI SDK without React and was therefore removed.

b) The`createdAt` timestamp should be set for new user messages. Will investigate.

**Comment by BelphegorPrime** [comment]
I also have the missing `createdAt` bug after updating the dependencies.

**Comment by lgrammel** [comment]
@BelphegorPrime from which version to which version (for `ai` and `@ai-sdk/react`)?

**Comment by lgrammel** [comment]
https://github.com/vercel/ai/pull/2342

**Comment by lgrammel** [comment]
fixed in main

**Comment by BelphegorPrime** [comment]
@lgrammel just a humble suggestion.
Maybe a some test that covers that issue so that it can help in preventing such critical problems?

**Comment by lgrammel** [comment]
yes looked into it. it would need changing the `append` behavior `handleSubmit` and there were issues with that and the test framework when i first implemented the test last year. so we postponed tests to get this in.

**Comment by BelphegorPrime** [comment]
yeah all good, just didn't want to let it fell down behind

**Comment by lgrammel** [comment]
new versions with the fix have been released

**Comment by lgrammel** [comment]
## Identify issue type

Identified as **Bug**  
Confidence: **High**

### Rationale
The primary issue is a confirmed regression in existing `useChat` behavior: newly created user messages were missing the expected `createdAt` timestamp. A fix was merged and released.

### Evidence
- After updating `ai` from 3.1.15 to 3.2.27, user messages created by `useChat` no longer had `createdAt`, while assistant messages did.
- The maintainer confirmed that `createdAt` should be set for new user messages, linked PR #2342, and stated the issue was fixed and released.
- The separate removal of experimental `message.ui` was explained as intentional and replaced by AI SDK RSC.
