### ISSUE TITLE
Encounter Runtime timeout error when returning early in server action

### ISSUE THREAD

**Issue by littledino2112** [vercel/ai#2351]
### Description

I'm having vercel timeout issue when applying ratelimit in the server action that is used to submit user message (submitUserMessage). This is actually using the ai [chatbot ](https://github.com/vercel/ai-chatbot.git )example. When returning from this function early due to ratelimit condition has been met, I encountered Vercel Runtime timeout error. What could be the issue here?

### Code example

// Inside submitUserMessage
    const { success } = await ratelimit.chat.limit(session.user.id!)
    if (!success) {
      return {
        error: 'You reach chat limit per day'
      }
    }

// In client-side code
        const responseMessage = await submitUserMessage(text, uploadedUrl)
        if ('error' in responseMessage) {
          toast.error(responseMessage.error)
        }
        setMessages(currentMessages => [...currentMessages, responseMessage])

**Comment by littledino2112** [comment]
Figured it out. It turned out I needed to close aiState.done() to properly close the stream

**Comment by littledino2112** [comment]
Close issue

**Comment by lgrammel** [comment]
## Identify issue type

Identified as **None**  
Confidence: **High**

### Rationale
This is a self-resolved support question caused by not closing the AI state stream, not a demonstrated SDK defect or request for a product change.

### Evidence
- The reporter asked why an early return caused a runtime timeout.
- The reporter determined the stream was left open because `aiState.done()` was not called.
- The reporter requested that the issue be closed after resolving it.
