### ISSUE TITLE
azure api version as env var

### ISSUE THREAD

**Issue by FrancescoSaverioZuppichini** [vercel/ai#2353]
### Feature Description

Dear all,

[In the code](https://github.com/vercel/ai/blob/cba088b29a11011d375a100cc8de1d789d58dffd/packages/azure/src/azure-openai-provider.ts#L117) api version is hardcoded, however sometimes we want to use a different one.

Thus I was thinking of having an AZURE_API_VERSION env variable.

Thanks a lot

### Use Case

Production

**Comment by lgrammel** [comment]
It is hardcoded on purpose. Switching the API version risks breaking our integration. Is there a newer API version that you need for certain features?

**Comment by FrancescoSaverioZuppichini** [comment]
> It is hardcoded on purpose. Switching the API version risks breaking our integration. Is there a newer API version that you need for certain features?

got it, what about the model version itself?

**Comment by FrancescoSaverioZuppichini** [comment]
> Don't you define your on deployments on azure and select the model there?

I deeply apology, was Monday. Thank you so much!

**Comment by lgrammel** [comment]
## Identify issue type

Identified as **None**  
Confidence: **High**

### Rationale
Although initially framed as a feature request, the comments clarify that this was a configuration/support question resolved by using Azure deployment settings, with no remaining product change requested.

### Evidence
- The reporter initially proposed an AZURE_API_VERSION environment variable because the API version is hardcoded.
- The maintainer explained that the version is intentionally fixed to avoid breaking the integration and asked which newer feature was needed.
- The reporter clarified that the actual concern was selecting a model version, which is configured through Azure deployments, and accepted the explanation.
