### ISSUE TITLE
Pass `detail` parameter to `ImagePart` in `CoreUserMessage`

### ISSUE THREAD

**Issue by yannxaver** [vercel/ai#2355]
### Feature Description

OpenAI exposes a `detail` parameter for images. (https://platform.openai.com/docs/guides/vision/low-or-high-fidelity-image-understanding)

Is it possible to set this parameter using the `ai` library?

**Comment by lgrammel** [comment]
Not currently. This is very openai specific. 

Do you have a use case that is not possible with the default `automatic` detail setting?

**Comment by yannxaver** [comment]
Sometimes it's preferable to set `detail` to `low` to reduce input tokens (costs). If it is set to `automatic` OpenAI will choose the detail level based on the image size. So I would have to resize the image instead to activate low mode which would be more complicated and slower.

**Comment by lgrammel** [comment]
When you use `detail: "low"`, do you set it for all images, or do you change this setting only for certain images?

**Comment by angelhodar** [comment]
I personally use it for all images

**Comment by lgrammel** [comment]
WIP PR: https://github.com/vercel/ai/pull/2918

**Comment by lgrammel** [comment]
## Identify issue type

Identified as **Feature**  
Confidence: **High**

### Rationale
This requests a new provider-specific capability for configuring OpenAI image detail, rather than reporting broken existing behavior.

### Evidence
- The SDK did not currently expose OpenAI's image `detail` parameter, as confirmed by the maintainer.
- Users requested explicit `detail: "low"` support to reduce token usage and avoid resizing images.
- A maintainer linked a work-in-progress implementation PR and later the provider documentation for image detail.
