### ISSUE TITLE
No object generated using perplexity with generateObject

### ISSUE THREAD

**Issue by taylor-lindores-reeves** [vercel/ai#2378]
### Description

When using the Perplexity AI LLM with Vercel AI's generateObject method, an error occurs indicating that no object is generated. The error message received is: `NoObjectGeneratedError [AI_NoObjectGeneratedError]: No object generated.`

### Code example

```
"use server";

import { createOpenAI } from "@ai-sdk/openai";
import { generateObject } from "ai";
import { z } from "zod";

const perplexity = createOpenAI({
    apiKey: "api-key",
    baseURL: "https://api.perplexity.ai/",
});

const schema = z.object({ ... });

export async function generateObjectWithPerplexity(
	props,
) {
	const { prompt } = props;
	try {
		const { object } = await generateObject({
			model: perplexity.chat("llama-3-sonar-small-32k-online"),
			messages: [
				{
					role: "user",
					content: [
						{
							type: "text",
							text: prompt,
						},
					],
				},
			],
			system: ` ... `,
			mode: "tool",
			schema,
                      });

                 return { object };
	} catch (error) {
		console.log({ error });
		return null;
	}
}
```

### Additional context

The issue seems to be specific to the integration with Perplexity AI's generateObject method. The generateText method works as expected.

The generateObject method works as expected with other models, indicating the issue might be with the Perplexity AI model configuration or response handling.

Environment:
Vercel OpenAI AI SDK version: 0.0.37
Vercel AI version: 3.2.33
Perplexity model: llama-3-sonar-small-32k-online
Node.js version: 20.14.0
OS: MacOS 14.5

**Comment by lgrammel** [comment]
@taylor-lindores-reeves can you try setting `"mode": "json"`? that **might** work, but in general perplexity is not that strong for object generation

**Comment by taylor-lindores-reeves** [comment]
> @taylor-lindores-reeves can you try setting `"mode": "json"`? that **might** work, but in general perplexity llama is not that strong for object generation

Thanks for the quick response. I tried your suggestion and it's certainly a bit better, however now it is leading to an error message. I can see the object is being generated, but the result is part of a parent object containing a text property, similar to what generateText would return:

JSONParseError [AI_JSONParseError]: JSON parsing failed: Text: ```json
  {
    "value": 123456,
  }
  ```

**Comment by lgrammel** [comment]
@taylor-lindores-reeves i suspect the model is not strong enough to support good json output

**Comment by lgrammel** [comment]
## Identify issue type

Identified as **None**  
Confidence: **High**

### Rationale
This is primarily a model compatibility/configuration support issue. The SDK errors correspond to Perplexity not returning the required tool or valid plain JSON output, and the comments provide a prompting workaround rather than identify broken SDK behavior.

### Evidence
- Perplexity fails to produce a tool call in `mode: "tool"` and returns markdown-wrapped JSON in `mode: "json"`.
- A maintainer attributed the result to the model's weak JSON/object-generation capabilities rather than an SDK defect.
- Another commenter successfully used `generateObject` with the same model through JSON mode and stricter prompt instructions.
