### ISSUE TITLE
Anthropic calls throw an error with '"Multiple assistant messages in block" functionality not supported'

### ISSUE THREAD

**Issue by AaronFriel** [vercel/ai#2420]
### Description

When adapting LLM calls from OpenAI to another provider, this error message is thrown as a result of calling the API with consecutive assistant messages.

### Code example

```ts
    const streamResult = await streamText({
        model: llm,
        messages: [
            {
                role: "assistant",
                content: "test",
            },
            {
                role: "assistant",
                content: "test",
            },
            {
                role: "user",
                content: "test",
            }
        ],
      // ...
    });
```

Strangely, this example does not throw an error if I remove the trailing user message (if the only two messages are `role: assistant`).

**Comment by mosnicholas** [comment]
I am having a similar issue.. is this an issue with anthropic ? Any remedies?

**Comment by danielzohar** [comment]
[This PR](https://github.com/vercel/ai/pull/2067) solved the problem for me. Here is the related issue https://github.com/vercel/ai/issues/2047

**Comment by lgrammel** [comment]
https://github.com/vercel/ai/pull/2518

**Comment by BrianHung** [comment]
With anthropic, 
> Messages must alternate between user and assistant, and we'll get an error if we don't follow this rule

https://github.com/anthropics/courses/blob/master/AnthropicAPIFundamentals/02_messages_format.ipynb

Workaround seems to be concatenating sequential assistant messages into one (as done in the PR above)
> content: A string or list of content dictionaries representing the actual content of the message. If a string is provided, it will be treated as a single text content block. If a list of content dictionaries is provided, each dictionary should have a "type" (e.g., "text" or "image") and the corresponding content.

**Comment by Genzo0** [comment]
I've got the similar issue with anthropic 'Multiple system messages that are separated by user/assistant messages', I try to give a new context through system role. the flow look like : 
system
user
assistant
system --> this is throw this error

but it is fine on open ai models

**Comment by lgrammel** [comment]
## Identify issue type

Identified as **Bug**  
Confidence: **High**

### Rationale
This is a concrete provider-adapter failure: the SDK does not normalize consecutive assistant messages into the format required by Anthropic, causing an API call to throw.

### Evidence
- `streamText` with an Anthropic model throws when given consecutive assistant messages, while the same message pattern works with OpenAI.
- A maintainer linked PR #2518, which addresses the problem by combining sequential assistant messages.
- Comments explain that Anthropic requires user and assistant messages to alternate, so the SDK must normalize otherwise valid cross-provider input.
