### ISSUE TITLE
useChat append doesn't work inside onFinish callback

### ISSUE THREAD

**Issue by ottozastrow** [vercel/ai#2423]
### Description

The usecase is common:
In a chat, first use a tool, then have gpt explain the results automatically. To achieve this, after a message finished generating, we'd like to add an invisible message that prompts the model to explain the previous results.

Using useChat 
` onFinish: (message: Message) => {
      if (message.toolInvocations){
        const toolResultMessage = {
          role: 'assistant',
          content: "explain the results",
        } as Message;
        append(toolResultMessage);
       }
    }
  },`
  
The problem:
The response starts loading, generates and displays the first 1-5 tokens, then stops streaming (at least in the UI). When inspecting the network tab the POST response shows the full streamed message, instead of just the first couple of tokens. Seems like the messages state is no longer updated.
(The route.ts i am using follows the usechat examples from the docs, no additional logic.)

 I am using ai@3.2.36 with bun, nextjs 14.1.3

**Comment by lgrammel** [comment]
## Identify issue type

Identified as **Bug**  
Confidence: **High**

### Rationale
This describes concrete broken behavior in the existing `useChat` API: a request initiated through `append` inside `onFinish` streams fully over the network but is not fully reflected in UI state.

### Evidence
- Calling `append` from `useChat`'s documented `onFinish` callback starts a second response but the UI stops updating after the first few tokens.
- The network response contains the complete stream, indicating a client-side message state or streaming update failure rather than an incomplete model response.
- The reporter reproduces this with the standard `useChat` route pattern on `ai@3.2.36`.
