### ISSUE TITLE
Support a simple JSON Schema Object

### ISSUE THREAD

**Issue by dosco** [vercel/ai#2435]
### Feature Description

when creating a tool entry please support just a simple object that implements a json schema in addition to zod or whatever.

### Use Case

Zod has limitations it is not easy to work with when dynamic schema's need to be generated such as with agents etc.

**Comment by lgrammel** [comment]
It is support by using the `jsonSchema` function: https://sdk.vercel.ai/docs/reference/ai-sdk-core/json-schema

**Comment by lgrammel** [comment]
## Identify issue type

Identified as **None**  
Confidence: **High**

### Rationale
The requested capability already exists, so the issue is effectively a support/discovery question rather than a bug, documentation change, or new feature request.

### Evidence
- The request asks for tool schemas to accept plain JSON Schema objects instead of requiring Zod.
- A maintainer clarified that this is already supported through the documented `jsonSchema` function.
