### ISSUE TITLE
experimental_useObject header object

### ISSUE THREAD

**Issue by jt6677** [vercel/ai#2462]
### Feature Description

please experimental_useObject header object 

### Use Case

To use any other endpoints

**Comment by lgrammel** [comment]
## Identify issue type

Identified as **Feature**  
Confidence: **High**

### Rationale
This is a request to expand `experimental_useObject` with configurable headers so it can work with additional endpoints.

### Evidence
- The issue explicitly requests header support for `experimental_useObject`.
- The stated use case is calling other endpoints, implying a desired API capability rather than a failure of documented behavior.
- No comments provide evidence of an existing regression or bug.
