### ISSUE TITLE
Streaming text inside `streamUI` isn't working in `next@15` & `react@19`

### ISSUE THREAD

**Issue by MarkLyck** [vercel/ai#2480]
### Description

The text streaming in the `text()` function no longer works in the ai-chatbot example and I can't find any updated code for getting this feature to work?

To reproduce:

1. Clone the ai-chat example: https://github.com/vercel/ai-chatbot/tree/main
2. Add required env variables
3. install dependencies
4. Run `dev` and provide a prompt that doesn't trigger a `tool` so the AI responds with text.
5. Notice that the text streams in word by word fine

6. Update next, ai, @ai-sdk/openai, react & react-dom to the latest versions.
7. run `dev` and give the same prompt. Notice that the text no longer streams in, but the response takes longer than before and then the entire message comes back at once.

I tested on the latest versions as of today:
```
"@ai-sdk/openai": "0.0.40",
"next": "15.0.0-canary.91",
"react": "19.0.0-rc-941e1b4a-20240729",
"react-dom": "19.0.0-rc-941e1b4a-20240729",
```

When downgrading to next@14 and react@18 again the text streaming example works fine.

The text streaming is a big improvement to chat UX when the responses are slow to complete.

### Additional context

It would be great if there were docs that covers this scenario for Vercel AI SDK. I imagine most people that want to use `streamUI` will also use the `text` fallback and want the text to be streaming.

**Comment by lgrammel** [comment]
Reproduced as follows:

1. Upgrade the `examples/next-openai` example to use:

    "next": "15.0.0-canary.91",
    "react": "19.0.0-rc-941e1b4a-20240729",
    "react-dom": "19.0.0-rc-941e1b4a-20240729",
    
2. Start `next dev` and go to http://localhost:3000/stream-ui

3. Enter "what is the typical weather for berlin in spring?"

Observe: result does not stream (should be streaming)

**Comment by nicoalbanese** [comment]
Hey @MarkLyck - thanks for reporting! For the time being, you can use `15.0.0-rc.0` which streams text as expected.

**Comment by MarkLyck** [comment]
@nicoalbanese Thanks for the suggestion, unfortunately there is an important fix in one of the canary versions I need, so my app is broken on the `15.0.0-rc.0` version.

But it's not a show-stopper. The chat still works, it just doesn't stream so you have to wait a while for the full result to complete.

**Comment by lgrammel** [comment]
Repository with reproduction: https://github.com/lgrammel/rsc-streaming-regression

**Comment by unstubbable** [comment]
@MarkLyck This should be fixed in Next.js 15.0.0-canary.111. Let me know in case you still notice issues with stream buffering.

**Comment by lgrammel** [comment]
## Identify issue type

Identified as **Bug**  
Confidence: **High**

### Rationale
This is a concrete regression in existing text-streaming behavior under specific Next.js 15 and React 19 versions. Although the fix appears to belong to Next.js, the reported behavior is still a reproducible failure rather than solely a documentation or feature request.

### Evidence
- After upgrading to Next.js 15 canary and React 19, `streamUI` text output is buffered and returned all at once instead of streaming incrementally.
- A maintainer reproduced the regression in `examples/next-openai` and confirmed that streaming still worked with Next.js 14 and React 18.
- A later comment states that the issue should be fixed in Next.js 15.0.0-canary.111.
