### ISSUE TITLE
`useChat?  response message ID changes during streaming when `streamMode: "text"`

### ISSUE THREAD

**Issue by Yonom** [vercel/ai#2505]
### Description

When `useChat`'s `streamMode` is set to `"text"`, the ID of the response message seems to change on each intermediate stream result.

Expectation: The message ID should be stable, since the result represents the same message. The behavior should be consistent between the two `streamMode` variants

The following is the output from the code example:
![image](https://github.com/user-attachments/assets/5d69354e-aa27-422a-b03a-257efbd8f2a3)

### Code example

```ts
const TestButton = () => {
  const chat = useChat({ streamMode: "text" });
  const handleAdd = () => {
    chat.append({
        role: "user",
        content: "hii"
      });
  };

  console.log(chat.messages);
  
  return <button onClick={handleAdd}>Add test message</button>
}
```

**Comment by lgrammel** [comment]
https://github.com/vercel/ai/pull/2515

**Comment by lgrammel** [comment]
## Identify issue type

Identified as **Bug**  
Confidence: **High**

### Rationale
This is a concrete failure in existing streaming behavior: the identity of a single assistant message changes while its text is streamed.

### Evidence
- With `useChat({ streamMode: "text" })`, the assistant response message receives a different ID on intermediate streaming updates.
- The reporter expects one stable ID because each update represents the same response message and notes inconsistent behavior between stream modes.
- A maintainer linked PR #2515 in response, indicating a code-level fix.
