### ISSUE TITLE
Generate output is giving z.input type as object type rather than z.output

### ISSUE THREAD

**Issue by Royal-lobster** [vercel/ai#2547]
### Description

Generate output is giving z.input type as object type rather than z.output, incase of needing to transform/preprocess - the zod schema type won't be equaling to the output type 

![CleanShot 2024-08-05 at 14 52 43@2x](https://github.com/user-attachments/assets/15e9f7b8-9a71-4fd8-9eaf-b3c833dc0d52)

### Code example
```ts
import { generateObject } from "ai";
import { openai } from "@ai-sdk/openai";
import { z } from "zod";


const { object } = generateObject({
  model: openai("gpt-4o"),
  schema: z.enum(["A", "B", "C"]).transform((s)=> ({id: s})),
});
```

```ts
import { generateObject } from "ai";
import { openai } from "@ai-sdk/openai";
import { z } from "zod";

const { object } = generateObject({
  model: openai("gpt-4o"),
  schema: z.preprocess(
    (val) => (typeof val === "number" ? String(val) : val),
    z.string(),
  ),
});
```

**Comment by lgrammel** [comment]
https://github.com/vercel/ai/pull/2549

**Comment by lgrammel** [comment]
Fix landed in main

**Comment by Royal-lobster** [comment]
Thats quick ! thanks!!

**Comment by lgrammel** [comment]
## Identify issue type

Identified as **Bug**  
Confidence: **High**

### Rationale
This is a concrete type-inference defect in existing `generateObject` behavior, and maintainers explicitly treated it as requiring a fix.

### Evidence
- `generateObject` inferred `object` from the Zod schema's input type instead of its transformed output type, producing an incorrect type for `transform` and `preprocess` schemas.
- The maintainer linked a corrective pull request and confirmed, “Fix landed in main.”
