### ISSUE TITLE
structuredOutput fails if schemas use `.optional()` or `.nullish()`, should be `.nullable()`.

### ISSUE THREAD

**Issue by MaxLeiter** [vercel/ai#2591]
Just a heads up for others, if you're getting errors like this with `structuredOutputs`, replace `.optional()` or `.nullish()` in your schema with `.nullable()`.

```
AI_APICallError: Invalid schema for response_format 'response': In context=(), 'required' is required to be supplied and to be an array including every key in properties. Missing 'foo'
```

_Originally posted by @brc-dd in https://github.com/vercel/ai/issues/2573#issuecomment-2273562297_

**Comment by lgrammel** [comment]
This is a limitation of the OpenAI implementation. Other providers will not have this. Therefore I don't want to put in any magic, it's imo on the user / OpenAI to solve this.

Potential solutions:
a) clear error messages
b) docs around this

**Comment by glaksmono** [comment]
> This is a limitation of the OpenAI implementation. Other providers will not have this. Therefore I don't want to put in any magic, it's imo on the user / OpenAI to solve this.
> 
> Potential solutions: a) clear error messages b) docs around this, e.g. tips & troubleshooting

This happens also for those that aren't using Vercel AI. Any advice?

**Comment by lgrammel** [comment]
## Identify issue type

Identified as **Documentation**  
Confidence: **High**

### Rationale
The discussion concludes that the SDK should document or clarify a provider-specific schema restriction rather than alter product behavior.

### Evidence
- OpenAI structured outputs reject schemas using `.optional()` or `.nullish()` because every property must appear in `required`.
- The maintainer identifies this as an OpenAI implementation limitation rather than behavior to change in the SDK.
- The proposed remedies are clearer error messages and documentation such as tips and troubleshooting, followed by a linked pull request.
