### ISSUE TITLE
Overloading error from Antrophic API doesn't seem to be handled

### ISSUE THREAD

**Issue by d3lm** [vercel/ai#2606]
### Description

It looks like `overloaded_error` (Antrophic API) is not handled correctly in that the `onError` callback of `useChat` isn't called nor is the `error` property set.

What I see in the response is the following:

```
3:"{\"type\":\"overloaded_error\",\"message\":\"Overloaded\"}"
```

Could this be a bug?

**Comment by wong2** [comment]
I found it too

**Comment by lgrammel** [comment]
https://github.com/vercel/ai/pull/2618 and https://github.com/vercel/ai/pull/2617

**Comment by lgrammel** [comment]
fixed in main

**Comment by d3lm** [comment]
Thanks a ton!

**Comment by lgrammel** [comment]
## Identify issue type

Identified as **Bug**  
Confidence: **High**

### Rationale
The report describes concrete broken error-handling behavior in the existing SDK, and the maintainer confirmed that a fix was applied.

### Evidence
- An Anthropic `overloaded_error` response did not invoke `useChat`'s `onError` callback or populate its `error` property.
- A maintainer linked corrective pull requests #2618 and #2617 and confirmed the issue was "fixed in main".
