### ISSUE TITLE
Google Gemini AI: toolChoice doesn't work

### ISSUE THREAD

**Issue by odragora** [vercel/ai#2620]
### Description

1. Call `streamText` using `google.generativeAI('models/gemini-1.5-flash')` and `toolChoice: { type: 'tool', toolName: 'yourToolName' }`

2. RetryError [AI_RetryError]: Failed after 3 attempts. Last error: An internal error has occurred. Please retry or report in https://developers.generativeai.google/guide/troubleshooting

### Additional context

Before the recent Google Gemini update toolChoice has been just completely ignored, and the model just didn't call the tool most of the time, even when configured to always call the tool.
Now it fails with the AI_RetryError.

**Comment by lgrammel** [comment]
a) it is a 500 on the google side, not an issue with the ai sdk
b) it works with 'models/gemini-1.5-pro-latest'

**Comment by odragora** [comment]
a) I think there is an issue with AI SDK and Gemini, since toolChoice has been ignored even before the recent Gemini update.
b) It doesn't work with Gemini Flash, including latest.

**Comment by lgrammel** [comment]
## Identify issue type

Identified as **Bug**  
Confidence: **Medium**

### Rationale
The issue reports concrete broken behavior for an existing AI SDK option with a supported provider/model: forced tool choice is ignored or fails. Although the maintainer suggests the immediate 500 is upstream, the reported SDK-facing behavior is still a specific failure rather than a request for new capability.

### Evidence
- Using `toolChoice: { type: 'tool', ... }` with Gemini 1.5 Flash reportedly results in `AI_RetryError` after repeated Google 500 responses.
- The reporter says `toolChoice` was previously ignored rather than forcing the configured tool call.
- A maintainer attributes the current 500 error to Google and notes that Gemini 1.5 Pro works, while the reporter confirms the failure is specific to Flash.
