### ISSUE TITLE
Support prompt caching 

### ISSUE THREAD

**Issue by kdawgwilk** [vercel/ai#2689]
### Feature Description

Add support for setting `cache_control` on `CoreMessage` to support new Anthropic feature https://www.anthropic.com/news/prompt-caching

### Use Case

Cost savings when reusing prompt context

**Comment by lgrammel** [comment]
Cache control needs to be on message parts. Prototype is available here but requires large changes: https://github.com/vercel/ai/pull/2678

**Comment by lgrammel** [comment]
https://github.com/vercel/ai/pull/2697

**Comment by lgrammel** [comment]
## Identify issue type

Identified as **Feature**  
Confidence: **High**

### Rationale
This requests a new provider capability rather than reporting broken existing behavior, so it is a feature.

### Evidence
- The issue requests adding `cache_control` support for Anthropic prompt caching.
- The stated use case is cost savings from reusing prompt context.
- A maintainer clarified that cache control belongs on message parts and linked the implementation PR, later confirming it landed in main.
