### ISSUE TITLE
generateText: provide roundtrip status

### ISSUE THREAD

**Issue by hinderberg** [vercel/ai#2724]
### Feature Description

We would love if you can expose readStreamableValue on the server. Any reason it is a .tsx file now? Also, the types expose it, but you get a runtime error because the import is undefined. 

### Use Case

We have agents using createStreamableValue, but want to merge their responses into one stream with readStreamableValue.

**Comment by lgrammel** [comment]
`createStreamableValue` is intended for RSC backends. Why are you using it in agents?

**Comment by hinderberg** [comment]
Our setup is like this:

client -> handler -> agent

What we want is to have the agent return both a streamable value which the handler can stream to the client, and a resolveable promise so the handler can store the response of the agent. 

This is easy with streamText, as it already returns AsyncIterableStream and a Promise<string>. But for agents using for example generateText, we need a way to create an AsyncIterableStream. Which we have not found a good solution for. 

We want to stream content from all our agent, since it can take time to execute their actions. Meaning using generateText we would mainly stream status updates while running roundtrips. 

Any suggestions on how to solve this?

**Comment by hinderberg** [comment]
While trying to solve this we though maybe readStreamableValue could be a solution, but if you have other ways you think will work better, I would love some suggestions <3.

**Comment by hinderberg** [comment]
What we consider is to let the agents return generator functions instead, since streams are not very useful here.

**Comment by lgrammel** [comment]
would having roundtrips on streamText solve this? or a callback on generateText for each roundtrip?

**Comment by hinderberg** [comment]
Having roundtrips would have solved it, but we think we've found a type that works better for us. 

Regarding callback per roundtrip on generateText is high on our wishlist anyway, since it would help us create better updates from the agents.

This is what we ended up with:

```ts
export interface StepSolutionAgent {
  name: string;
  description: string;
  run(arg: AgentInput): Promise<{
    userMessage: CoreMessage;
    partialResult: AsyncIterable<{
      action: 'append' | 'update';
      value: string;
    }>;
    endResult: Promise<string>;
  }>;
}
```

**Comment by lgrammel** [comment]
`streamText` now supports multi-step calls: https://sdk.vercel.ai/docs/ai-sdk-core/tools-and-tool-calling#multi-step-calls

**Comment by hinderberg** [comment]
Thank you! We are already using it! 🤩

**Comment by lgrammel** [comment]
## Identify issue type

Identified as **Feature**  
Confidence: **High**

### Rationale
The issue primarily requests a new way to expose and stream agent roundtrip status. The later resolution through newly added multi-step support confirms it was a capability enhancement rather than a current-behavior defect.

### Evidence
- The reporter asks for server-side access to `readStreamableValue` to merge agent responses into one stream.
- Comments clarify the desired capability is exposing roundtrip progress from `generateText` or supporting multi-step roundtrips in `streamText`.
- A maintainer later notes that `streamText` now supports multi-step calls, and the reporter confirms they are using it.
