### ISSUE TITLE
Using experimental_attachments with empty input doesn't append the message

### ISSUE THREAD

**Issue by blechatellier** [vercel/ai#2725]
### Description

When using `useChat`, if the input is empty but a list of `experimental_attachments` is passed to `handleSubmit` with `allowEmptySubmit` set to `true`, no new message is appended to the list sent to the server.

https://github.com/vercel/ai/blob/f95c4b41525257d5494127bf141317044312feff/packages/react/src/use-chat.ts#L607

**Comment by lgrammel** [comment]
Fixed in main

**Comment by blechatellier** [comment]
Awesome thanks @lgrammel

**Comment by lgrammel** [comment]
## Identify issue type

Identified as **Bug**  
Confidence: **High**

### Rationale
The report describes concrete existing behavior that incorrectly ignores an allowed attachment-only submission, and the maintainer confirmed a fix.

### Evidence
- `useChat` fails to append a message when the input is empty and `experimental_attachments` are submitted with `allowEmptySubmit: true`.
- A maintainer stated that the issue was “Fixed in main,” confirming it was treated as a defect.
