### ISSUE TITLE
Submit useChat messages as core messages

### ISSUE THREAD

**Issue by blechatellier** [vercel/ai#2727]
### Feature Description

Instead of using `convertToCoreMessages` on the server, can we add an option to convert messages as core in the `useChat` `handleSubmit` method?

**Comment by lgrammel** [comment]
The messages on the client are different in nature than the core messages that are passed into the AI functions (streamText etc). They can contain additional information, and a conversion is necessary.

If you want to move the `convertToCoreMessages` call to the client, you can already do so by using `prepareRequestBody`: https://sdk.vercel.ai/docs/reference/ai-sdk-ui/use-chat#experimental_prepare-request-body

**Comment by blechatellier** [comment]
Thanks @lgrammel - this is what I was looking for 👍

**Comment by lgrammel** [comment]
## Identify issue type

Identified as **None**  
Confidence: **High**

### Rationale
This was resolved as a usage question using an existing API, with no product or documentation change requested after clarification.

### Evidence
- The request asks whether `useChat` can submit core messages instead of converting them on the server.
- A maintainer explained that client and core messages differ and that conversion can already be moved client-side with `experimental_prepareRequestBody`.
- The reporter confirmed that the existing option met their need.
