### ISSUE TITLE
Module not found: Can't resolve '@google-cloud/vertexai'

### ISSUE THREAD

**Issue by rossanodr** [vercel/ai#2773]
### Description

installed the package using the following command:

yarn add @ai-sdk/google-vertex
I followed the instructions from [this link](https://sdk.vercel.ai/providers/ai-sdk-providers/google-vertex), but I encountered the following error:
⨯ ./node_modules/@ai-sdk/google-vertex/dist/index.mjs:3:1
Module not found: Can't resolve '@google-cloud/vertexai'

### Code example

```
import { vertex } from "@ai-sdk/google-vertex";
import {
    StreamData,
    streamText
} from "ai";
export default async function POST(req: Request) {

    const model = vertex("gemini-1.5-pro", {
     useSearchGrounding:true
    });
    const data = new StreamData();
    const result = await streamText({
        model: model,
        system: systemPrompt,
        messages: message,
           onFinish() {
            data.close();
        },
    });
    return result.toDataStreamResponse();

}

```

### Additional context

I tried setting the config with 'export const runtime = 'nodejs';
and modifying the auth settings.

**Comment by lgrammel** [comment]
The `@ai-sdk/google-vertex` package has a peer dependency: `"@google-cloud/vertexai": "^1.4.0"`

It seems that yarn does not automatically install the peer, so you need to add it manually.

**Comment by lgrammel** [comment]
## Identify issue type

Identified as **Documentation**  
Confidence: **High**

### Rationale
The package requires an additional peer dependency that was not communicated by the referenced installation instructions. The resolution is to clarify the required installation steps rather than change SDK behavior.

### Evidence
- Following the provider installation instructions with `yarn add @ai-sdk/google-vertex` results in a missing `@google-cloud/vertexai` module.
- The maintainer clarified that `@google-cloud/vertexai` is a peer dependency that Yarn may not install automatically and must be added manually.
