### ISSUE TITLE
Type error when using model map

### ISSUE THREAD

**Issue by AnzeKop** [vercel/ai#2791]
### Description

```
Exported variable 'models' has or is using name 'OpenAIChatSettings' from external module "/node_modules/@ai-sdk/openai/dist/index" but cannot be named.ts(4023)
```

Gives a type error when trying to create a type of the map keys where the return type is OpenAIChatSettings. Example code to reproduce below.

### Code example

```ts
//Exported variable 'models' has or is using name 'OpenAIChatSettings' from external module "/node_modules/@ai-sdk/openai/dist/index" but cannot be named.ts(4023)
const models = {
  "gpt-4": openai("gpt-4", { structuredOutputs: true }),
  "gpt-4o": openai("gpt-4o", { structuredOutputs: true }),
  "gpt-4o-mini": openai("gpt-4o-mini", { structuredOutputs: true }),
} as const;

type ModelName = keyof typeof models

export function getModel(
  modelName: ModelName
): ReturnType<typeof openai> {
  const model = models[modelName];
  if (!model) {
    throw new Error(`Model ${modelName} not found`);
  }

  return model;
}

```

**Comment by lgrammel** [comment]
You can use `LanguageModel` from the `ai` package:

```
import { openai } from '@ai-sdk/openai';
import { LanguageModel } from 'ai';

const models: Record<string, LanguageModel> = {
  'gpt-4': openai('gpt-4', { structuredOutputs: true }),
  'gpt-4o': openai('gpt-4o', { structuredOutputs: true }),
  'gpt-4o-mini': openai('gpt-4o-mini', { structuredOutputs: true }),
} as const;

type ModelName = keyof typeof models;

export function getModel(modelName: ModelName): LanguageModel {
  const model = models[modelName];
  if (!model) {
    throw new Error(`Model ${modelName} not found`);
  }

  return model;
}
```

**Comment by lgrammel** [comment]
In `v3.3.18` we introduce custom providers to make this easier: https://sdk.vercel.ai/docs/ai-sdk-core/provider-management#custom-providers

**Comment by lgrammel** [comment]
## Identify issue type

Identified as **Bug**  
Confidence: **High**

### Rationale
The issue reports a concrete TypeScript declaration/inference failure when using existing OpenAI models in a map. The workaround and later ergonomic API do not change that the reported current behavior fails to compile as written.

### Evidence
- The reproduced model map triggers TypeScript error TS4023 because its inferred type references `OpenAIChatSettings` from `@ai-sdk/openai` but cannot name it.
- A maintainer provided an explicit `LanguageModel` annotation as a workaround and later pointed to custom providers introduced in v3.3.18.
