### ISSUE TITLE
experimental_useObject to include attachments

### ISSUE THREAD

**Issue by sahanatvessel** [vercel/ai#2811]
### Feature Description

experimental_useObject hook to accept file attachments

### Use Case

A user can upload images/txt to generate structured data

### Additional context

https://github.com/vercel/ai/discussions/2808

**Comment by lgrammel** [comment]
Thought about it more, with `useObject` you have full flexibility what you send and how you parse it out on the server. So it should already be possible?

**Comment by sahanatvessel** [comment]
yeah makes sense!

**Comment by valstu** [comment]
FYI for others, `submit` method returned by `useObject` takes in only json serialisable values. In case you need to send Files to backend you need to implement custom fetch logic.

**Comment by JulianKingman** [comment]
@lgrammel can this be reopened? Would love to see this functionality added, and it seems to not be possible at the moment.

**Comment by lgrammel** [comment]
## Identify issue type

Identified as **Feature**  
Confidence: **High**

### Rationale
This requests a new attachment-upload capability for `useObject`; it does not establish that file support was existing or documented behavior that regressed or broke.

### Evidence
- The issue explicitly requests that `experimental_useObject` accept file attachments for structured-data generation.
- A commenter reports that `useObject.submit` only accepts JSON-serializable values and overwrites the request body, preventing files from being sent through the hook.
- The latest comment asks for this functionality to be added because it is not currently possible.
