### ISSUE TITLE
Provide provider chat id and timestamp

### ISSUE THREAD

**Issue by castortech** [vercel/ai#2842]
### Feature Description

OpenAI (and most if not all other provider) provide a unique id to identify a chat.

Taking OpenAI as an example we have:
- id string A unique identifier for the chat completion.
- created integer The Unix timestamp (in seconds) of when the chat completion was created.

These provide strong correlation to identify chats and their messages.

### Use Case

Necessary for any tracking, billing and other mode of observability.

### Additional context

As discussed [here](https://github.com/vercel/ai/discussions/2841)

**Comment by lgrammel** [comment]
WIP PR: https://github.com/vercel/ai/pull/2893

**Comment by lgrammel** [comment]
## Identify issue type

Identified as **Feature**  
Confidence: **High**

### Rationale
This requests new provider metadata exposure rather than reporting broken or undocumented existing behavior.

### Evidence
- The request asks the SDK to expose provider-generated chat completion IDs and creation timestamps.
- The stated use case is correlation for tracking, billing, and observability.
- A maintainer linked a work-in-progress implementation PR, indicating a planned capability addition.
