### ISSUE TITLE
Prompt Token Usage not accurate when using Anthropic Prompt Caching

### ISSUE THREAD

**Issue by ghardin1314** [vercel/ai#2845]
### Description

When using the `experimental_providerMetadata` property for caching prompts with Anthropic provider, the token usage that is reported is inaccurate. The prompt tokens reported are only counting the non-cached part of the prompt, even though there is still (smaller) costs with using the cached section of the prompt.

### Code example

```typescript
import { createAnthropic } from "@ai-sdk/anthropic";
import { createOpenAI } from "@ai-sdk/openai";
import { generateObject } from "ai";


  const anthropicProvider = createAnthropic({
      apiKey: env.ANTHROPIC_API_KEY,
    });

  const model = anthropicProvider.languageModel("...", { cacheControl: true })
  
  await generateObject({
                       model,
                       schema: ...,
                       messages: [
                       {
                         role: "system",
                         content: ...,
                       },
                       {
                         role: "user",
                         content: ...,
                         experimental_providerMetadata: {
                           anthropic: { cacheControl: { type: "ephemeral" } },
                         },
                       },
                       // Prompt tokens above here are not reported in the usage
                       {
                         role: "user",
                         content: ...
                       },
                      ]
```

**Comment by lgrammel** [comment]
@ghardin1314 the additional information about the cached tokens is returned as well (provider specific): https://sdk.vercel.ai/providers/ai-sdk-providers/anthropic#example-cache-control

**Comment by lgrammel** [comment]
## Identify issue type

Identified as **None**  
Confidence: **Medium**

### Rationale
The maintainer indicates this is expected provider-specific accounting rather than a broken SDK behavior. The issue is primarily a usage clarification, with no explicit documentation or product change requested.

### Evidence
- The report says generic prompt token usage excludes the cached portion when Anthropic prompt caching is enabled.
- A maintainer clarified that cached-token usage is returned separately through Anthropic-specific provider metadata and linked the existing cache-control documentation.
- No further evidence establishes that generic prompt-token usage was intended to include cached tokens.
