### ISSUE TITLE
infer correct return types when using `output: 'array'` with `experimental_useObject`

### ISSUE THREAD

**Issue by sahanatvessel** [vercel/ai#2858]
### Feature Description

if the `streamObject` config is set to `output: 'array'` it'd be great to infer this on the frontend when using the `experimental_useObject` hook

Otherwise the objects are wrapped in `elements: []`

### Use Case

https://github.com/vercel-labs/ai-sdk-preview-use-object

If I want to be returned a list of expenses from the api

**Comment by lgrammel** [comment]
This is a bug - the `elements` wrapping should be removed.

**Comment by lgrammel** [comment]
Fix: https://github.com/vercel/ai/pull/2861

**Comment by lgrammel** [comment]
Fixed in `ai@3.3.23`

**Comment by sahanatvessel** [comment]
Awesome work!

**Comment by lgrammel** [comment]
## Identify issue type

Identified as **Bug**  
Confidence: **High**

### Rationale
The hook's existing array-output behavior and inferred return type were incorrect, and the maintainer confirmed and fixed it as a bug.

### Evidence
- Using `streamObject` with `output: 'array'` caused `experimental_useObject` to return objects wrapped in `elements: []` instead of inferring the array result.
- A maintainer explicitly identified this as a bug and stated that the `elements` wrapper should be removed.
- The issue was fixed by PR #2861 and released in `ai@3.3.23`.
