### ISSUE TITLE
Expose `PartialObject` type

### ISSUE THREAD

**Issue by mishushakov** [vercel/ai#2870]
### Feature Description

Need this for type-safety

**Comment by lgrammel** [comment]
`PartialObject` is intended to be an internal type. Can you share the use case, ideally with example code so I can see if there is another solution?

**Comment by mishushakov** [comment]
I want to pass it around as prop?

**Comment by mishushakov** [comment]
code:

```ts
const { object, submit, isLoading, stop, error } = useObject({
    api: '/api/chat',
    schema,
  })
```

**Comment by lgrammel** [comment]
Does `DeepPartial<T>` not work for you?

**Comment by mishushakov** [comment]
Is it exported?

**Comment by lgrammel** [comment]
Yes.

**Comment by lgrammel** [comment]
## Identify issue type

Identified as **Feature**  
Confidence: **High**

### Rationale
This requests an API/type export expansion. Although an existing alternative may satisfy the use case, the original request is for a new public capability rather than a bug.

### Evidence
- The title and description request exposing the currently internal `PartialObject` type for type safety.
- The maintainer confirmed `PartialObject` is intentionally internal and suggested the already-exported `DeepPartial<T>` as an alternative.
- No broken or contradictory existing behavior is reported.
