### ISSUE TITLE
Vertex Provider supporting embeddings

### ISSUE THREAD

**Issue by Godrules500** [vercel/ai#2907]
### Feature Description

I am beginning to include internal data, and some static documents, but I need the ability to use embeddings with the vertex provider via Vercel. I see that it has been added to the google provider, so if it could be added to the vertex ai provider, that would be awesome!

### Use Case

I'm open to better methods for using this, but at first I'm going to include some static handbook documents and use them for answering questions if a user has a question for that.  Then we are going to expand to additional data sources, in which we are going to attempt to use the search api. The results that come back, I was thinking of using the embeddings to help assist with the user's questioning.

If embeddings doesn't seem a like a good use here, let me know!

**Comment by lgrammel** [comment]
https://github.com/vercel/ai/pull/3426

**Comment by lgrammel** [comment]
https://github.com/vercel/ai/pull/3428

**Comment by lgrammel** [comment]
## Identify issue type

Identified as **Feature**  
Confidence: **High**

### Rationale
This is a request for a new provider capability—embedding support for Vertex AI—rather than a failure of existing promised behavior.

### Evidence
- The issue explicitly requests adding embeddings support to the Vertex AI provider.
- It notes that embeddings are available in the Google provider but does not claim Vertex embeddings were already supported or documented.
- The maintainer links pull request #3428, indicating implementation work for the requested capability.
