### ISSUE TITLE
Add input management support to useObject hook

### ISSUE THREAD

**Issue by Aaryan6** [vercel/ai#2910]
### Feature Description

```
const { object, submit } = useObject({
    api: '/api/use-object',
    schema: z.object({ content: z.string() }),
    initailMessages: ??
  });
```
Implement support for initialMessages in the useObject hook within the AI SDK. This feature would allow developers to pre-populate the conversation history when initializing the useObject hook, similar to how initialMessages works in other hooks like useChat.

### Use Case

To continue the history of conversation

**Comment by lgrammel** [comment]
`useObject` does not manage messages or input in any way. You can use `initialValue` to set the input value: https://sdk.vercel.ai/docs/reference/ai-sdk-ui/use-object#initial-value?

**Comment by lgrammel** [comment]
My bad, initial value is the result. Input is currently not managed in `useObject`, you would use your own `useState` and then use that when you submit.

**Comment by Aaryan6** [comment]
Would you be able to integrate this in the future?

**Comment by lgrammel** [comment]
@Aaryan6 I want to keep it as is because it's very easy to have your own `useState` and it keeps things more flexible for the cases where you don't need it.

**Comment by vincentjflorio** [comment]
I know this is marked completed but if others interpreted it the way I did initially -- providing additional to ride piggyback on the prompt -- I submit a stringified object (one key of which is the original user-provided prompt) and parse it back on the back end.

Just sharing in case that's helpful.

**Comment by lgrammel** [comment]
## Identify issue type

Identified as **Feature**  
Confidence: **High**

### Rationale
This is a request to expand `useObject` with managed input or initial-message functionality, rather than a report of incorrect existing behavior.

### Evidence
- The issue requests new input/history management support in `useObject`, analogous to `initialMessages` in `useChat`.
- A maintainer confirms that `useObject` currently does not manage input and recommends external `useState`.
- The maintainer states the current behavior is intentional to preserve flexibility, so no existing promised behavior is broken.
