### ISSUE TITLE
The server example in `node-http-server` uses a deprecated API method

### ISSUE THREAD

**Issue by sebastiansandqvist** [vercel/ai#2920]
### Description

There is a plain Node.js HTTP server example [here](https://github.com/vercel/ai/blob/main/examples/node-http-server/src/server.ts) that makes use of the `StreamTextResult.toAIStream` method. Using the latest version of the Vercel AI SDK, this method is deprecated and should be replaced by a call to `toDataStreamResponse`. That recommended alternative method isn't a drop-in replacement for `.toAIStream`, though, so it'd be great to see the example updated to reflect the current recommended way to stream an AI response in a plain HTTP server.

<img width="573" alt="Screenshot 2024-09-06 at 12 17 25 PM" src="https://github.com/user-attachments/assets/64c01d2d-876e-4e71-b94f-28a4d3c415df">

**Comment by lgrammel** [comment]
Improved support: https://github.com/vercel/ai/pull/2934

**Comment by lgrammel** [comment]
## Identify issue type

Identified as **Examples**  
Confidence: **High**

### Rationale
The issue specifically requests correction of a runnable repository example that demonstrates a deprecated API, rather than reporting broken SDK behavior.

### Evidence
- The `examples/node-http-server` project uses the deprecated `StreamTextResult.toAIStream` method.
- The reporter asks to update the plain Node.js HTTP server example to demonstrate the recommended streaming approach.
- A maintainer links PR #2934 as providing improved support.
