### ISSUE TITLE
Add Support for Custom AI Model in StreamUI

### ISSUE THREAD

**Issue by zohairhadi** [vercel/ai#2955]
### Feature Description

streamUI only allows a preset types of models that can be used for streaming.
We should add support for adding a custom model or an api which can be called instead of the prebuilt model prop.

### Use Case

This can be used when we have a custom LLM and want to stream its responses.

**Comment by lgrammel** [comment]
## Identify issue type

Identified as **None**  
Confidence: **Medium**

### Rationale
The request appears to be based on an unclear assumption about existing model restrictions. Since the claimed capability may already exist and no specific unsupported behavior is demonstrated, this is best treated as an unresolved support/clarification request.

### Evidence
- The reporter requests custom-model or custom-API support for `streamUI` but does not describe a concrete failure.
- A maintainer states that `streamUI` already supports any model with proper tool-calling capability and asks for clarification.
- No follow-up clarifies what capability is missing.
