### ISSUE TITLE
Cannot destructure property 'sendMessage' of 'useActions(...)' as it is null.

### ISSUE THREAD

**Issue by ajaykrupalk** [vercel/ai#3010]
### Description

I am trying to use useActions in React 18.3.1 but getting this error when running the application. Any help would be appreciated.

### Code example

import { useActions } from "ai/rsc";

export default function Home() {
  const { sendMessage } = useActions();
  .......
}

**Comment by ajaykrupalk** [comment]
I believe this is because I am using React, will try in Next.JS

**Comment by lgrammel** [comment]
## Identify issue type

Identified as **None**  
Confidence: **Medium**

### Rationale
This is primarily a support question involving a likely framework or setup mismatch, without enough evidence of a defect in supported AI SDK behavior.

### Evidence
- The report asks for help with `useActions()` returning `null` in a React application.
- The author later suggests the problem may be due to using React rather than Next.js and plans to try Next.js.
- No supported-behavior expectation, reproducible setup, or confirmed SDK defect is established.
