### ISSUE TITLE
Support image input in Mistral provider

### ISSUE THREAD

**Issue by alex4671** [vercel/ai#3042]
### Feature Description

Mistral now have model with image input capabilities https://mistral.ai/news/pixtral-12b/
current convertToMistralChatMessages prevent from using it, please add support

**Comment by lgrammel** [comment]
https://github.com/vercel/ai/pull/3048

**Comment by lgrammel** [comment]
## Identify issue type

Identified as **Feature**  
Confidence: **High**

### Rationale
This requests new provider/model capability for image inputs rather than reporting a failure of previously supported behavior.

### Evidence
- The issue explicitly requests image-input support for Mistral's new Pixtral multimodal model.
- The existing Mistral message conversion does not support this newly introduced capability.
- A maintainer linked pull request #3048 as the related implementation.
