### ISSUE TITLE
Invalid Type Checking on Tool Call Result

### ISSUE THREAD

**Issue by haifeng-amaysim** [vercel/ai#3044]
### Description

Accidentally getting error message like: AI_InvalidPromptError: Invalid prompt: messages must be an array of CoreMessage

Due to the zod validation on the coreMessage type one of the issue is in the Tool Call Result literal checking the type name

The issue is introduced by the code in 
`packages/ai/core/prompt/content-part.ts`

`export const toolResultPartSchema: z.ZodType<ToolResultPart> = z.object({
  type: z.literal('tool-result'),
  toolCallId: z.string(),
  toolName: z.string(),
  result: z.unknown(),
  isError: z.boolean().optional(),
  experimental_providerMetadata: providerMetadataSchema.optional(),
}) as z.ZodType<ToolResultPart>; // necessary bc result is optional on Zod type`

In GPT Model or your default response never show a type: z.literal('tool-result'), why adding this type checking while the response do not include that? And you forcing the type checking but did not check your exact response output.

### Code example

{
      "role": "tool",
      "content": [
          {
              "toolCallId": "call_4tChcmmeReCA0pGLKK6A2NeJ",
              "toolName": "getProducts",
              "args": {
                  "type": "someproduct"
              },
              "result": { }
          }
        ]
}
This type will not pass the Zod validation as some one checking the type type: z.literal('tool-result'), but OpenAI model never return this literal string, so pls make it optional as role = "tool" already indicate it is tool result

**Comment by lgrammel** [comment]
The type is required for typescript discriminated union checks and future extensions. The tool response is never generated by an LLM or OpenAI.

You can use `responseMessages` (available for both `generateText` or `streamText`) to simplify keeping a consistent message history: https://sdk.vercel.ai/docs/ai-sdk-core/tools-and-tool-calling#response-messages

**Comment by lgrammel** [comment]
## Identify issue type

Identified as **None**  
Confidence: **High**

### Rationale
This is a support request based on manually constructing a message that does not match the SDK's intended schema, rather than a confirmed defect or requested documentation change.

### Evidence
- The supplied tool-result message omits the required `type: "tool-result"` discriminator.
- The maintainer states that the discriminator is intentional for TypeScript unions and future extensions, and that tool responses are not generated directly by OpenAI.
- The maintainer recommends using `responseMessages` to maintain correctly structured message history.
