### ISSUE TITLE
experimental_useObject is not supporting `headers` parameter

### ISSUE THREAD

**Issue by RafalWilinski** [vercel/ai#3080]
### Feature Description

Currently, https://github.com/vercel/ai/blob/0f50dade95391dee044398da915dd6e1e856a367/packages/react/src/use-object.ts#L20 is not supporting all properties like `headers`, `credentials` that are supported in https://github.com/vercel/ai/blob/0f50dade95391dee044398da915dd6e1e856a367/packages/react/src/use-chat.ts

It would be nice to have that there.

### Use Case

E.g. Authentication of endpoints returning streams of structured objects

**Comment by lgrammel** [comment]
Fixed in `ai@3.4.1`

**Comment by lgrammel** [comment]
## Identify issue type

Identified as **Feature**  
Confidence: **High**

### Rationale
This requests an API capability expansion for `experimental_useObject`, rather than reporting a violation of documented behavior.

### Evidence
- `experimental_useObject` lacked `headers` and `credentials` options available in `useChat`.
- The requested capability was needed to authenticate endpoints that stream structured objects.
- A maintainer stated it was added in `ai@3.4.1`.
