### ISSUE TITLE
Claude Prompt Caching for System Message broken

### ISSUE THREAD

**Issue by nafetswirth** [vercel/ai#3085]
### Description

This code, from the [example docs](https://sdk.vercel.ai/providers/ai-sdk-providers/anthropic#example-cache-control), doesn't actually work.

It produces the following error:
```
- error node_modules/@ai-sdk/provider-utils/dist/index.mjs (431:13) @ eval
- error messages: first message must use the "user" role
```

### Code example

```js
const result = await generateText({
  model: anthropic('claude-3-5-sonnet-20240620', {
    cacheControl: true,
  }),
  messages: [
    {
      role: 'system',
      content: 'Cached system message part',
      experimental_providerMetadata: {
        anthropic: { cacheControl: { type: 'ephemeral' } },
      },
    },
    {
      role: 'system',
      content: 'Uncached system message part',
    },
    {
      role: 'user',
      content: 'User prompt',
    },
  ],
});
```

### Additional context

This makes sense given that the official SDK also excepts this but I would think the library should give one interface for all providers and it works with `openai`

**Comment by nafetswirth** [comment]
My bad, it works, it was one of the other message that was 'assistant' as the first message 💀

**Comment by lgrammel** [comment]
## Identify issue type

Identified as **None**  
Confidence: **High**

### Rationale
The reporter determined the SDK behavior was not broken; the error resulted from their message ordering. This is therefore a resolved support/user-error report rather than a bug or requested change.

### Evidence
- The original report claimed system-message prompt caching failed with a “first message must use the user role” error.
- The reporter later confirmed that the example works and that another message incorrectly used the assistant role as the first message.
