### ISSUE TITLE
Add additional google search grounding features

### ISSUE THREAD

**Issue by Godrules500** [vercel/ai#3127]
### Feature Description

With google vertex grounding, it returns the sources it used to gather its information. That is something google requires to be displayed and I would like for these to be added. 

Thanks!

### Use Case

When someone searches real-time information, google requires me to display the sources and the google search html they send to me.

**Comment by lgrammel** [comment]
https://github.com/vercel/ai/pull/3426

**Comment by lgrammel** [comment]
## Identify issue type

Identified as **Feature**  
Confidence: **High**

### Rationale
This requests expanded Google Vertex grounding support rather than reporting a failure of existing documented behavior.

### Evidence
- The issue requests exposing Google Vertex grounding sources and Google Search HTML.
- The requested data is described as an additional capability needed to meet Google's display requirements.
- A maintainer linked pull request #3426, indicating implementation work for the requested enhancement.
