### ISSUE TITLE
`FilePart` interface not exported

### ISSUE THREAD

**Issue by Saran33** [vercel/ai#3171]
### Description

The newly added `FilePart` interface is not exported as are the other content parts.

### Code example

```ts
import type {
  CoreMessage,
  FilePart,
  ImagePart,
  TextPart,
  ToolCallPart,
  ToolResultPart,
} from 'ai';
// Module '"ai"' declares 'FilePart' locally, but it is not exported.ts(2459)
```

**Comment by MISTYKITTY** [comment]
Show full conversación

Le mar. 1 oct. 2024 à 4:39 PM, Saran Connolly ***@***.***> a
écrit :

**Comment by lgrammel** [comment]
## Identify issue type

Identified as **Bug**  
Confidence: **High**

### Rationale
This is a concrete API export omission causing an existing type import to fail, so it is a bug rather than a request for a new capability.

### Evidence
- `FilePart` is declared within the `ai` module but cannot be imported because it is not exported.
- Other comparable content-part interfaces such as `ImagePart`, `TextPart`, `ToolCallPart`, and `ToolResultPart` are exported.
- The provided TypeScript example fails with TS2459 when importing `FilePart`.
