### ISSUE TITLE
OpenAI imageDetail not working with streamText

### ISSUE THREAD

**Issue by crisemcon** [vercel/ai#3175]
### Description

Adding the experimental_providerMetadata to set the imageDetail to low in streamText instead of generateText is not working properly. I get the same tokens attaching the same image with and without the setting.

Example with providerMetadata imageDetail low:
    experimental_providerMetadata: {
      openai: { imageDetail: 'low' },
    },

web:dev: onFinish {
web:dev:   text: "I'm unable to assist with that.",
web:dev:   toolCalls: [],
web:dev:   toolResults: [],
web:dev:   finishReason: 'stop',
web:dev:   usage: { promptTokens: 26673, completionTokens: 8, totalTokens: 26681 }
web:dev: }

Example with no provider metadata:
    // experimental_providerMetadata: {
    //   openai: { imageDetail: 'low' },
    // },
    
web:dev: onFinish {
web:dev:   text: "I'm unable to assist with that.",
web:dev:   toolCalls: [],
web:dev:   toolResults: [],
web:dev:   finishReason: 'stop',
web:dev:   usage: { promptTokens: 26673, completionTokens: 8, totalTokens: 26681 }
web:dev: }

### Code example

```
import { openai } from '@ai-sdk/openai';
import { convertToCoreMessages, streamText } from 'ai';
// ...
export async function POST(request: Request) {
  const { messages } = await request.json();
  const stream = await streamText({
    model: openai('gpt-4o-mini'),
    // ...
    messages: convertToCoreMessages(messages),
    maxToolRoundtrips: 2,
    experimental_providerMetadata: {
      openai: { imageDetail: 'low' },
    },
    async onFinish({ text, toolCalls, toolResults, finishReason, usage }) {
      console.log('onFinish', { text, toolCalls, toolResults, finishReason, usage });
    },
  });
```

### Additional context

[Docs](https://sdk.vercel.ai/providers/ai-sdk-providers/openai#image-detail) reference uses generateText, so is this just not available for streamText?

**Comment by lgrammel** [comment]
You need to set the detail on the image content part of your message, not on the overall request.

**Comment by p3droml** [comment]
I read the docs and understand that certain provider-specific options require configuration at the message part level, but having providerOptions both as a generateText/generateObject argument and as part of messages is very confusing.

**Comment by lgrammel** [comment]
## Identify issue type

Identified as **None**  
Confidence: **High**

### Rationale
This is primarily a usage/support question caused by configuring the option at the wrong level, not evidence of broken SDK behavior or a concrete request for a change.

### Evidence
- The report applies `imageDetail` as top-level request metadata and asks whether it is unavailable for `streamText`.
- A maintainer clarified that image detail must be configured on the image content part of the message, not on the overall request.
- The later comment describes the placement of provider options as confusing but does not request a specific behavior or documentation change.
