### ISSUE TITLE
Issue receiving response from gemini-1.5-pro-002 (Google Generative AI)

### ISSUE THREAD

**Issue by corixdean** [vercel/ai#3180]
### Description

Hello. We are trying to upgrade our used model from `models/gemini-1.5-pro-001` to `models/gemini-1.5-pro-002`.

Upon updating the model, we get the following error back from the SDK:

`
LLM error: AI_TypeValidationError: Type validation failed: Value: {"candidates":[{"content":{"parts":[{"text":"```"}],"role":"model"}}],"usageMetadata":{"promptTokenCount":395,"totalTokenCount":395}}.
Error message: [
  {
    "code": "invalid_type",
    "expected": "number",
    "received": "undefined",
    "path": [
      "usageMetadata",
      "candidatesTokenCount"
    ],
    "message": "Required"
  }
]
`

Calling streamText with identical payload, only difference is 001 -> 002 in the model name.

We are able to use 002 in the Google Generative AI Studio and colab notebooks using the same provider key so does not seem to be an access issue.

Reading the error it seems like possibly some required properties are not being returned and schema parsing is failing. 

### Code example

import { CoreMessage, streamObject, streamText } from "ai";

// this works
result = await streamText({
    model: "models/gemini-1.5-pro-001",
    systemMessage: "Please send a test response"
});

// this gives the aforementioned error
result = await streamText({
    model: "models/gemini-1.5-pro-002",
    systemMessage: "Please send a test response"
});

**Comment by lgrammel** [comment]
Please try updating to the latest version of ai-sdk/google

**Comment by lgrammel** [comment]
## Identify issue type

Identified as **Bug**  
Confidence: **High**

### Rationale
The issue reports a concrete SDK validation failure when handling a response from a supported Google model, rather than requesting a new capability.

### Evidence
- Switching only the model from `gemini-1.5-pro-001` to `gemini-1.5-pro-002` causes `streamText` to throw `AI_TypeValidationError`.
- The provider response omits `usageMetadata.candidatesTokenCount`, but the SDK schema treats it as a required number.
- A maintainer advised updating to the latest `ai-sdk/google`, suggesting the compatibility issue may already have been fixed.
