### ISSUE TITLE
OnStepFinish types not available

### ISSUE THREAD

**Issue by samelamin-discovery** [vercel/ai#3181]
### Description

I cant seem to look at the toolResults type definitions

### Additional context

Saw the documentation and the pr here https://github.com/vercel/ai/pull/3024

But for some reason I can see the definitions of `onFinish` but not for `onStepFinish`

I am using the latest packages so I am not sure why I cant see types for `onStepFinish`

**Comment by lgrammel** [comment]
https://github.com/vercel/ai/pull/3243

**Comment by lgrammel** [comment]
## Identify issue type

Identified as **Bug**  
Confidence: **High**

### Rationale
Documented type definitions are missing or inaccessible in the released SDK, which is a concrete failure of existing behavior rather than a request for a new capability.

### Evidence
- The reporter cannot access the documented `onStepFinish`/`toolResults` type definitions in the latest packages, while `onFinish` definitions are available.
- A maintainer linked PR #3243, indicating a code-level correction related to the report.
