### ISSUE TITLE
Add support for Amazon Bedrock embeddings

### ISSUE THREAD

**Issue by kopertop** [vercel/ai#3202]
### Feature Description

Add support for using Amazon Bedrock for Embeddings. Currently the provider just tosses an error for any string passed in:

```
  provider.textEmbeddingModel = (modelId: string) => {
    throw new NoSuchModelError({ modelId, modelType: 'textEmbeddingModel' });
  };
  ```

There are currently 4 different models (including Amazon Titan models) that support Embeddings outputs.

### Use Case

This adds another provider that can generate Embeddings. Since Amazon Bedrock can generate short lived tokens using STS, this also allows generating embeddings securely.

### Additional context

There is some information https://cloudnature.net/blog/amazon-bedrock-for-javascript-and-typescript-developers on how to generate embeddings, but it looks like just invoking with one of the supported models will work.

**Comment by lgrammel** [comment]
https://github.com/vercel/ai/pull/3219

**Comment by lgrammel** [comment]
## Identify issue type

Identified as **Feature**  
Confidence: **High**

### Rationale
This requests a new provider capability—embedding model support for Amazon Bedrock—not a failure of existing promised behavior.

### Evidence
- The title and description explicitly request adding Amazon Bedrock embedding support.
- The current provider intentionally throws `NoSuchModelError` for `textEmbeddingModel`, indicating the capability is not yet implemented rather than malfunctioning.
- The maintainer comment links PR #3219, apparently addressing the requested addition.
