### ISSUE TITLE
Expose `maxRetries` and `timeout` for embedding functions

### ISSUE THREAD

**Issue by kevin-vanta** [vercel/ai#3216]
### Feature Description

OpenAI SDK allows to pass `requestOptions: { timeout?: number; maxRetries?: number }` along side the model and text to embed. This is not currently available and it would be awesome to also migrate the embedding generation to Vercel's SDK!

**Comment by kevin-vanta** [comment]
(`maxRetries` is [documented here](https://sdk.vercel.ai/docs/reference/ai-sdk-core/embed))

**Comment by lgrammel** [comment]
- `embed` and `embedMany` support max retries
- timeouts can be achieved through `AbortSignal.timeout` (`abortSignal` property)

**Comment by lgrammel** [comment]
## Identify issue type

Identified as **None**  
Confidence: **High**

### Rationale
The requested capabilities already exist, so this is effectively a usage/support clarification rather than a product change or concrete failure.

### Evidence
- The request asks to expose `maxRetries` and `timeout` for embedding functions.
- A commenter notes that `maxRetries` is already documented for `embed`.
- A maintainer clarifies that `embed` and `embedMany` support retries and that timeouts are available through the `abortSignal` property using `AbortSignal.timeout`.
