### ISSUE TITLE
Support supplying a custom tracer in telemetry settings

### ISSUE THREAD

**Issue by mshick** [vercel/ai#3226]
### Feature Description

The ability to supply a custom OpenTelemetry `Tracer` in the telemetry settings defined in `experimental_telemetry`.

### Use Case

This would be useful in situations where you would like to use a separate `TracerProvider` to generate traces in `ai`. A separate `TracerProvider` can configure different resources, sampling rules, and processors distinct from the `TracerProvider` used by the `@opentelemetry/api` singleton. 

### Additional context

Very specifically, if using the Arize AI tracing service you are required to provide the `model_id` in the immutable `Resource` supplied when creating a `NodeTracerProvider`. If you wanted to report on multiple, distinct models in your application using the `ai` sdk, you may create separate `NodeTracerProviders` for those models, but since `ai` will only use the global singleton, you would be unable to use tracers from those distinct TracerProviders in the `ai` telemetry.

I have a PR prepared to add this feature.

**Comment by lgrammel** [comment]
## Identify issue type

Identified as **Feature**  
Confidence: **High**

### Rationale
This is an API capability expansion to support custom tracers and distinct tracer providers, rather than a failure of existing promised behavior.

### Evidence
- The issue explicitly requests the ability to provide a custom OpenTelemetry `Tracer` through `experimental_telemetry`.
- The current API uses the global OpenTelemetry singleton; the requested change would support separate `TracerProvider` configurations for resources, sampling, and processors.
- No existing documented behavior is described as broken or regressed.
