### ISSUE TITLE
streamText onFinish event usage NaN values

### ISSUE THREAD

**Issue by kdawgwilk** [vercel/ai#3268]
### Description

When calling `streamText` and passing `onFinish` the usage is null/NaN

### Code example

```ts
import { createOpenAI } from '@ai-sdk/openai';
import { streamText } from 'ai';

try {
  const openai = createOpenAI();

  const openaiResponse = await streamText({
    model: openai('gpt-4o'),
    prompt: 'Tell a joke',
    onFinish(event) {
      console.log('onFinish', event.usage);
    },
  });
  for await (const chunk of openaiResponse.fullStream) {
  }
} catch (e) {
  console.error(e);
}
```

### Output:

```
onFinish { promptTokens: NaN, completionTokens: NaN, totalTokens: NaN }
```

### Additional context

SDK Versions

```
"@ai-sdk/openai": "^0.0.67",
"ai": "^3.4.10",
```

**Comment by lgrammel** [comment]
You need to set compatibility to `strict` when using `createOpenAI()` (vs `openai`): https://sdk.vercel.ai/providers/ai-sdk-providers/openai#provider-instance

**Comment by kdawgwilk** [comment]
How would i get token usage for providers utilizing openai compatibility such as groq?

**Comment by lgrammel** [comment]
soon there'll be a dedicated groq provider since they are sending streaming token usage in a non-standard way: https://github.com/vercel/ai/pull/3291

**Comment by lgrammel** [comment]
## Identify issue type

Identified as **None**  
Confidence: **Medium**

### Rationale
The comments frame the reported behavior as a configuration and provider-compatibility support issue rather than a confirmed defect in the SDK.

### Evidence
- The reported NaN usage occurs when calling `createOpenAI()` without `compatibility: 'strict'`.
- A maintainer states that strict compatibility is required for this configuration and links to the provider documentation.
- The follow-up asks how to obtain usage from OpenAI-compatible providers such as Groq; the maintainer notes that a dedicated Groq provider is forthcoming.
