### ISSUE TITLE
Support Cohere v2 API

### ISSUE THREAD

**Issue by Gdewilde** [vercel/ai#3331]
### Feature Description

Cohere recently released [v2 of their API ](https://cohere.com/blog/new-api-v2), which includes support to define tools in JSON schema instead of Python types.

### Use Case

Supporting v2 enables complex tool definitions, which are now limited to primitive types, as mentioned in the docs https://sdk.vercel.ai/providers/ai-sdk-providers/cohere#model-capabilities. 

### Additional context

https://docs.cohere.com/v2/docs/migrating-v1-to-v2

**Comment by lgrammel** [comment]
## Identify issue type

Identified as **Feature**  
Confidence: **High**

### Rationale
This is a provider/API enhancement request rather than a failure of existing documented AI SDK behavior.

### Evidence
- The issue explicitly requests support for Cohere's newly released v2 API.
- It seeks a new capability: defining Cohere tools with JSON Schema to enable more complex tool definitions.
