### ISSUE TITLE
Don't pin exact versions of 3rd party dependencies

### ISSUE THREAD

**Issue by jfirebaugh** [vercel/ai#3337]
### Description

* Add a `@ai-sdk/ui-utils` dependency to a project that has its own dependency on `"zod-to-json-schema": "^3.23.3"`
* `npm install` / `pnpm install` / `yarn install`

Expected result: zod-to-json-schema is deduplicated; node_modules tree contains only the 3.23.3 version (or other semver-compatible version).

Actual result: multiple versions of zod-to-json-schema are installed, 3.23.3 and 3.23.2.

### Additional context

The cause is the exact version dependencies here:

https://github.com/vercel/ai/blob/a2fbb041a84fa756f1c102d8cf171111895feb26/packages/ui-utils/package.json#L42-L44

These should be `^` dependencies.

**Comment by lgrammel** [comment]
https://github.com/vercel/ai/pull/3341

**Comment by jfirebaugh** [comment]
Thank you for the quick fix! ❤️

**Comment by lgrammel** [comment]
## Identify issue type

Identified as **Bug**  
Confidence: **High**

### Rationale
This is a concrete dependency-management defect in the existing package that produces an unnecessary duplicate dependency installation, and it was addressed with a fix PR.

### Evidence
- `@ai-sdk/ui-utils` pins an exact `zod-to-json-schema` version, causing multiple semver-compatible versions to be installed instead of deduplicated.
- The reporter identifies the package dependency declarations as the cause and requests caret ranges.
- A maintainer linked PR #3341 as the fix.
