### ISSUE TITLE
Peer dependency issue

### ISSUE THREAD

**Issue by willredington** [vercel/ai#3381]
### Description

Create a new nextjs project with app router
`npx create-next-app@latest`

Add the dependnecies specified in the docs (https://sdk.vercel.ai/docs/getting-started/nextjs-app-router)
`npm install ai @ai-sdk/openai zod`

<img width="573" alt="Screenshot 2024-10-28 at 5 07 26 AM" src="https://github.com/user-attachments/assets/93dac3fb-fa4d-4f74-b13a-a69cf7959689">

**Comment by lgrammel** [comment]
https://github.com/vercel/ai/pull/3382

**Comment by lgrammel** [comment]
## Identify issue type

Identified as **Bug**  
Confidence: **High**

### Rationale
The documented installation flow fails in a newly created Next.js project because the package peer dependencies cannot be resolved, which is a concrete failure of existing behavior.

### Evidence
- Following the documented Next.js App Router setup causes `npm install ai @ai-sdk/openai zod` to fail with `ERESOLVE`.
- The screenshot shows a peer dependency conflict involving the new project's React 19 release candidate and the AI SDK's React peer range.
- A maintainer linked PR #3382, indicating a code-level fix.
