### ISSUE TITLE
anthropic model doesn't stream the response when used with useObject

### ISSUE THREAD

**Issue by sahanatvessel** [vercel/ai#3395]
### Description

Clone the following:
https://github.com/vercel-labs/ai-sdk-preview-array-output-mode

Replace the OpenAI model with `anthropic("claude-3-5-sonnet-20241022")` to see the bug happening

### Additional context

@lgrammel @nicoalbanese any help would be much appreciated

**Comment by sahanatvessel** [comment]
maybe related: https://github.com/anthropics/anthropic-sdk-typescript/issues/529

**Comment by lgrammel** [comment]
This is a long standing issue. I've explored it several times. Afaik Anthropic does "fake" streaming, i.e. stream all chunks at once after a significant delay.

**Comment by sahanatvessel** [comment]
Is there anything that can be done? Cursor and other tools are using
Anyhropic and doesn’t seem to have this issue… Any recommendations that I
could/should try?

**Comment by lgrammel** [comment]
This is not regular streaming, it's tool call streaming.

**Comment by sahanatvessel** [comment]
Have escalated this with the anthropic team 🤞

**Comment by lgrammel** [comment]
## Identify issue type

Identified as **None**  
Confidence: **High**

### Rationale
The reported behavior is attributed to an Anthropic API limitation rather than a broken AI SDK implementation, making this primarily a support/upstream-provider issue.

### Evidence
- The reporter observes that Anthropic responses arrive all at once when using `useObject`.
- A maintainer explains that object generation falls back to tool-call mode because Anthropic does not support structured outputs, and Anthropic delays tool-call chunks rather than genuinely streaming them.
- The reporter asks for recommendations and escalates the limitation to Anthropic; no AI SDK behavior change is identified.
