### ISSUE TITLE
[google-vertex] gemini-pro-experimental model not working

### ISSUE THREAD

**Issue by rovnyart** [vercel/ai#3412]
### Description

We've just switched from @google-cloud/vertexai to @ai-sdk/google-vertex and it seems like for some reason model `gemini-pro-experimental` is not working, but it worked fine with @google-cloud/vertexai. This is a huge problem for our product, can you please check it out? When I run my code (provided below) I get kinda confusing error:

```
{"name":"ClientError","stackTrace":{"code":404,"status":"NOT_FOUND"}}
```

PS flash-002 and pro-002 models work fine, the problem is only with gemini-pro-experimental

Thanks in advance!

### Code example

    const model = this.client('gemini-pro-experimental');

    const { text, usage } = await generateText({
      model,
      maxRetries: 5,
      messages: [
        {
          role: 'user',
          content: [
            { type: 'text', text: prompt },
            ...objectIds.map((objectId) => ({
              type: 'file' as const,
              data: `gs://${bucket}/${objectId}`,
              mimeType: 'audio/mpeg',
            })),
          ],
        },
      ],
      experimental_telemetry: {
        isEnabled: true,
        functionId: 'phone-call-analysis',
        metadata: {
          files: objectIds,
        },
      },
    });

### Additional context

we use file parts with gs:// objects, if it helps

versions:
"@ai-sdk/google-vertex": "0.0.42",
"ai": "3.4.25",

**Comment by lgrammel** [comment]
Can you try

```
data: new URL(`gs://${bucket}/${objectId}`)
```

**Comment by rovnyart** [comment]
Tried, didn't help, still getting:
```
{"name":"ClientError","stackTrace":{"code":404,"status":"NOT_FOUND"}}
```
Again, other models work fine with se same code, e.g. gemini-1.5-pro-002

**Comment by lgrammel** [comment]
If other models work fine, it's unlikely that the reason for this behavior is on the AI SDK side. We use the vertexai library under the hood, so things should match.

**Comment by kylefmohr** [comment]
On my end, it appears that the experimental model is no longer accessible - not from Google AI Studio or any of the APIs. I'm thinking they've removed everybody's access to the experimental models ahead of the launch of their new model which is rumored to be coming soon.

**Comment by lgrammel** [comment]
## Identify issue type

Identified as **None**  
Confidence: **High**

### Rationale
The available evidence points to external model availability rather than broken AI SDK behavior. The issue is therefore primarily a provider-access/support matter.

### Evidence
- The reported 404 occurs only for `gemini-pro-experimental`; other Vertex models work with the same AI SDK code.
- A maintainer noted that the provider uses the Vertex AI library underneath, making an SDK-specific discrepancy unlikely.
- A commenter confirmed the experimental model was also inaccessible through Google AI Studio and other APIs, suggesting Google removed access.
