### ISSUE TITLE
3+ Continue Steps do not work on bedrock

### ISSUE THREAD

**Issue by IdoPesok** [vercel/ai#3462]
### Description

Continue steps seems to break > 2 messages, or if you pass your own assistant message as the last message.

`"ai": "^3.4.32"`
`"@ai-sdk/amazon-bedrock": "^0.0.34"`

### Code example

```tsx
import { streamText } from "ai";
import { bedrock } from "@ai-sdk/amazon-bedrock";

const main = async () => {
  try {
    const { textStream } = await streamText({
      model: bedrock("anthropic.claude-3-5-sonnet-20240620-v1:0"),
      maxTokens: 10,
      experimental_continueSteps: true,
      maxSteps: 4,
      messages: [
        {
          role: "user",
          content: "write a poem",
        },
        {
          role: "assistant",
          content: "okay, here is a long poem. on a cold December",
        },
      ],
    });

    for await (const v of textStream) {
      console.log(v);
    }
  } catch (e) {
    console.log("got error", e);
  }
};

main();
```

### Additional context

got error ValidationException: A conversation must alternate between user and assistant roles. Make sure the conversation alternates between user and assistant roles and try again.
    at de_ValidationExceptionRes

**Comment by minpeter** [comment]
This is the intention of the Claude Chat template.
This can be solved by changing the last message in the input to User.
(or changing the order of the messages between the assistant and the user)

**Comment by minpeter** [comment]
```
import { streamText } from "ai";
import { bedrock } from "@ai-sdk/amazon-bedrock";

const main = async () => {
  try {
    const { textStream } = await streamText({
      model: bedrock("anthropic.claude-3-5-sonnet-20240620-v1:0"),
      maxTokens: 10,
      experimental_continueSteps: true,
      maxSteps: 4,
      messages: [
        {
          role: "assistant",
          content: "okay, here is a long poem. on a cold December",
        },
        {
          role: "user",
          content: "write a poem",
        },
      ],
    });

    for await (const v of textStream) {
      console.log(v);
    }
  } catch (e) {
    console.log("got error", e);
  }
};

main();
```

**Comment by lgrammel** [comment]
Also Anthropic: trailing whitespace issue.

**Comment by lgrammel** [comment]
Same for Bedrock.

**Comment by lgrammel** [comment]
## Identify issue type

Identified as **Bug**  
Confidence: **High**

### Rationale
The report demonstrates a concrete failure in the existing continuation-step behavior for the Bedrock provider, rather than requesting a new capability.

### Evidence
- With `experimental_continueSteps: true` and `maxSteps: 4`, Bedrock throws a `ValidationException` requiring alternating user and assistant roles.
- The failure occurs when continuing from a trailing assistant message or after multiple continuation steps.
- A maintainer confirmed the related Anthropic trailing-whitespace issue also applies to Bedrock.
