### ISSUE TITLE
Experimental Wrap Language Model is not exporting from 'ai' module

### ISSUE THREAD

**Issue by thisdotLolu** [vercel/ai#3585]
### Description

in the vercel ai codebase for nextjs
/ai/index.ts

`import { openai } from '@ai-sdk/openai';
import { experimental_wrapLanguageModel as wrapLanguageModel } from 'ai';

import { customMiddleware } from './custom-middleware';

export const customModel = (apiIdentifier: string) => {
  return wrapLanguageModel({
    model: openai(apiIdentifier),
    middleware: customMiddleware,
  });
};
`

2nd line, i can't exit the error as well

### Code example

```
import { openai } from '@ai-sdk/openai';
import { experimental_wrapLanguageModel as wrapLanguageModel } from 'ai';

import { customMiddleware } from './custom-middleware';


export const customModel = (apiIdentifier: string) => {
  return wrapLanguageModel({
    model: openai(apiIdentifier),
    middleware: customMiddleware,
  });
};
```

### Additional context

I have been using the codebase since sunday and it was all good, then suddenly faced with this error today, i have also deleted node_modules,package-lock and re installed again.
Still the same

**Comment by tillmbecker** [comment]
@thisdotLolu Hi there, I am facing the same issue. How have you fixed this?

**Comment by thisdotLolu** [comment]
Apologies for the late reply, if you haven't fixed it, i simply deleted my existing codebase and cloned the latest version of the code and used pnpm to install the packages, it's an update issue.

If you have existing work you can just back it up before deleting

**Comment by lgrammel** [comment]
## Identify issue type

Identified as **Bug**  
Confidence: **Medium**

### Rationale
The issue reports a concrete failure of an existing exported API that had previously worked, apparently caused by incompatible or inconsistent package updates.

### Evidence
- The import `experimental_wrapLanguageModel` from `ai` fails even after reinstalling dependencies.
- The reporter says the same code previously worked and then suddenly began erroring, indicating a regression or package update incompatibility.
- Another user reproduced the issue; the reporter resolved it by cloning the latest codebase and installing with pnpm, describing it as an update issue.
