### ISSUE TITLE
addToolResult / return in onToolCall in useChat does not change state on toolInvocations to from 'call' to 'result'

### ISSUE THREAD

**Issue by hinderberg** [vercel/ai#3601]
### Description

use useChat in react with client side toolCalls and return results on callback or add result with `addToolResult`.

**Comment by hinderberg** [comment]
Update, looking trough package code, it seems like the onToolCall updates state to "result" as it should. Leaving addToolResult the one that has the bug.

**Comment by mauricekleine** [comment]
@hinderberg are you using Google Vertex by chance? I've encountered this issue as well when using Google Vertex and I was able to solve it by returning objects from my tools instead of plain text, e.g. `return { text: "Success!" }` instead of `return "Success!"`

**Comment by jaspersorrio** [comment]
I can verify that i am observing the same as @hinderberg

In my case, we let user select an option from a list the llm provided. 

Observe the json of `toolInvocation` after calling `addToolResult`,  

Expected: since `toolInvocation.results` exist, `toolInvocation.state` should be "result"
Observed: `toolInvocation.results` exist but `toolInvocation.state` is still "call"

<img width="471" alt="Screenshot 2024-11-26 at 11 50 14 AM" src="https://github.com/user-attachments/assets/4dd6fd6a-aeed-43aa-9712-de4662681a49">

# Consequence
Resulting in UI not updating to reflect that the tool has been "called" and the results are in.

<img width="766" alt="Screenshot 2024-11-26 at 12 02 38 PM" src="https://github.com/user-attachments/assets/b5616336-4748-4804-948b-79dd4c0d42db">

**Comment by lgrammel** [comment]
## Identify issue type

Identified as **Bug**  
Confidence: **High**

### Rationale
This describes a concrete failure in existing `useChat`/`addToolResult` behavior, with expected versus observed state and a reproducible UI consequence.

### Evidence
- The reporter clarifies that `onToolCall` updates the state correctly, but `addToolResult` does not.
- Another user reproduces the issue: after `addToolResult`, `toolInvocation.result` exists while `toolInvocation.state` remains `"call"` instead of the expected `"result"`.
- The stale state prevents the UI from reflecting that tool execution has completed.
