### ISSUE TITLE
xAI Provider documentation results in `'name' does not exist in type 'OpenAIProviderSettings'.`

### ISSUE THREAD

**Issue by adriangalilea** [vercel/ai#3602]
### Description

Following the docs [here](https://sdk.vercel.ai/providers/openai-compatible-providers/xai)

Results in:

```
Object literal may only specify known properties, and 'name' does not exist in type 'OpenAIProviderSettings'.ts(2353)
```

### Code example

```
import { createOpenAI } from '@ai-sdk/openai';

const xai = createOpenAI({
  name: 'xai',
  baseURL: 'https://api.x.ai/v1',
  apiKey: process.env.XAI_API_KEY ?? '',
});
```

**Comment by adriangalilea** [comment]
Not sure if relevant, trying to fit xAI to the nextjs-ai-chatbot project gave me that issue, but now that I look deeper into it, it may not be an issue with this library, will see.

**Comment by lgrammel** [comment]
## Identify issue type

Identified as **Documentation**  
Confidence: **Medium**

### Rationale
The issue reports that a documentation code snippet is incompatible with the current TypeScript API, indicating the docs should be corrected or clarified rather than requesting new SDK behavior.

### Evidence
- The documented xAI configuration passes `name: 'xai'` to `createOpenAI`.
- TypeScript reports that `name` is not a valid `OpenAIProviderSettings` property.
- The reporter later expressed uncertainty but did not identify a product behavior defect.
