### ISSUE TITLE
Support streaming for o1-mini and o1-preview

### ISSUE THREAD

**Issue by dmtran-g** [vercel/ai#3761]
### Feature Description

According to https://x.com/OpenAIDevs/status/1858609150999359559?t=0blNt5lRwqHcLd6nIO1WXg&s=19, o1-mini and o1-preview now support streaming

**Comment by egoist** [comment]
For anyone who wants to enable it now, you can use pnpm patch to update this line:

![CleanShot 2024-11-19 at 14 48 18@2x](https://github.com/user-attachments/assets/f1138bbe-f46f-4d41-a3f3-aaa428ff9e50)

**Comment by lgrammel** [comment]
Supported in `@ai-sdk/openai@1.0.1`

**Comment by dmtran-g** [comment]
That was fast! Thank you!

**Comment by lgrammel** [comment]
## Identify issue type

Identified as **Feature**  
Confidence: **High**

### Rationale
This is support for a newly available provider capability rather than a failure of previously promised SDK behavior.

### Evidence
- The request asks to enable newly announced streaming support for OpenAI's o1-mini and o1-preview models.
- A workaround patches the SDK's reasoning-model streaming restriction.
- The maintainer confirms support was added in @ai-sdk/openai@1.0.1.
