### ISSUE TITLE
with ai-sdk/vue on v4.0 I can't edit the body anymore

### ISSUE THREAD

**Issue by cosbgn** [vercel/ai#3763]
### Description

I used to do something like this:

```js
const { messages, input, handleSubmit } = useChat()
const callApi = async(e, chatRequestOptions) => { 
	const new_opt = {
			...chatRequestOptions?.options,
			body: { ...chatRequestOptions?.options?.body, model: ai_model.value }
	}
	return handleSubmit(e, { ...chatRequestOptions, options: new_opt }) 
}

```

This was working perfectly until v4. It allowed me to dynamically edit the body ( and pass new properties like ai_model.value).
I can't use the useChat() body option directly because that won't be reactive, i.e. it will be set on first load an never change. 

### Code example

```js
const { messages, input, handleSubmit } = useChat()
const callApi = async(e, chatRequestOptions) => { 
	const new_opt = {
			...chatRequestOptions?.options,
			body: { ...chatRequestOptions?.options?.body, model: ai_model.value }
	}
	return handleSubmit(e, { ...chatRequestOptions, options: new_opt }) 
}

```

### AI provider

ai sdk v4.0 (VUE)

**Comment by cosbgn** [comment]
fixed with:

```js
const callApi = async (e, chatRequestOptions) => {
  const updatedRequestOptions = {
    ...chatRequestOptions,
    body: {
      ...chatRequestOptions?.body,
      model: ai_model.value,
      tags: tagSelectTemplateRef?.value?.selectedTags
    }
  }
  return handleSubmit(e, updatedRequestOptions)
}
```

**Comment by lgrammel** [comment]
## Identify issue type

Identified as **None**  
Confidence: **High**

### Rationale
This was resolved by updating the call to the v4 request-options shape, so it is primarily a usage/support issue rather than a confirmed SDK bug.

### Evidence
- The reporter’s v4 code placed `body` under an `options` property.
- The reporter later confirmed it works by passing `body` directly in the request options to `handleSubmit`.
- No remaining SDK failure or requested documentation/product change is identified.
