### ISSUE TITLE
Support grok vision capabilities

### ISSUE THREAD

**Issue by Lantianyou** [vercel/ai#3765]
### Feature Description

grok-vision-beta is live

![CleanShot 2024-11-19 at 17 03 52@2x](https://github.com/user-attachments/assets/f5598358-2ed3-46fa-bcc1-96563664bb06)

**Comment by lgrammel** [comment]
Supported in `@ai-sdk/xai@1.0.1`

**Comment by Lantianyou** [comment]
Thanks man

**Comment by lgrammel** [comment]
## Identify issue type

Identified as **Feature**  
Confidence: **High**

### Rationale
This requests new vision-model capability in the xAI provider rather than reporting a regression or violation of existing documented behavior.

### Evidence
- The issue requests support for the newly available `grok-vision-beta` model and its image inputs.
- The screenshot shows `@ai-sdk/xai@1.0.0` explicitly did not support image content parts.
- A maintainer confirmed the capability was added in `@ai-sdk/xai@1.0.1`.
