### ISSUE TITLE
Unable to generate an structured output using Gemini and an image

### ISSUE THREAD

**Issue by focux** [vercel/ai#3776]
### Description

When using `generateObject` with `gemini-1.5-flash-002` and passing an image url in the messages, I get this error:

```
"AI_APICallError: Unable to submit request because it must have a text parameter. Add a text parameter and try again. Learn more: https://cloud.google.com/vertex-ai/generative-ai/docs/model-reference/gemini"
```

This seems to have break 5 days ago because the code that I've been using for weeks, it's now not working and just throwing the error above, so I'm not sure if something changed in gemini side.

### Code example

```typescript
generateObject({
  model: googleai("gemini-1.5-flash-002"),
  schema: z.object({
    altText: z.string(),
    keywords: z.string().array(),
    name: z
      .string()
      .describe("The name of the image with a maximum of 2 words"),
  }),
  messages: [
    {
      role: "user",
      content: [
        { type: "image", image: imageUrl }
      ],
    },
  ],
});
```

If I add this item, next to the image message, then it works good:
```typescript
        { type: "image", image: imageUrl },
        {
          text: "Get the alt text, keywords, and name of the image",
          type: "text",
        },
```

### AI provider

@ai-sdk/google v1.0.0

### Additional context

It's been working for weeks and suddenly this stopped working ~5 days ago. It works if I add another message with text.

**Comment by lgrammel** [comment]
You need to actually supply an instruction for gemini when you submit images. It's how their api works.

**Comment by lgrammel** [comment]
Did this break with an AI SDK update (new version) or did this break suddenly (Google API change)?

**Comment by focux** [comment]
> Did this break with an AI SDK update (new version) or did this break suddenly (Google API change)?

It didn't break with an SDK update, it had been working for weeks in production and it suddenly broke 5 days ago, so I guess that it was due to some recent changes in gemini's API.

It would be good to make the text required in the types when using gemini with images if possible.

**Comment by lgrammel** [comment]
It throws an error now from the Gemini API when it's missing and required. Changing the types the way you describe is not possible, since it would depend on the models and that dependency is unknown.

**Comment by lgrammel** [comment]
## Identify issue type

Identified as **Bug**  
Confidence: **High**

### Rationale
This is a concrete regression in an existing `generateObject` workflow, even though the available context indicates the triggering change was likely in Gemini's API rather than an AI SDK release.

### Evidence
- `generateObject` with Gemini and an image-only user message now fails with an `AI_APICallError` requiring a text parameter.
- The same production code had worked for weeks and then regressed without an AI SDK update.
- Adding a text content part makes the request succeed; the maintainer confirmed Gemini now errors when required text is missing.
