### ISSUE TITLE
[ERR_REQUIRE_ESM]: require() of ES Module when using AI SDK 4.0

### ISSUE THREAD

**Issue by kevsjh** [vercel/ai#3794]
### Description

Running vercel ai sdk on Firebase function. Upgraded to v4.0 and facing esm issue

Error message below 

Error [ERR_REQUIRE_ESM]: require() of ES Module .../node_modules/nanoid/non-secure/index.js from .../node_modules/@ai-sdk/provider-utils/dist/index.js not supported.
Instead change the require of .../node_modules/nanoid/non-secure/index.js in .../node_modules/@ai-sdk/provider-utils/dist/index.js to a dynamic import() which is available in all CommonJS modules.

### AI provider

ai": "^4.0.1

**Comment by lgrammel** [comment]
https://github.com/vercel/ai/pull/3795

**Comment by lgrammel** [comment]
Most likely caused by upgrading nanoid to v5. I've downgraded. Please try using the updated packages when they become available.

https://github.com/vercel/ai/pull/3796

If the issue persists, pls reopen.

**Comment by kevsjh** [comment]
fixed on 4.0.2, thanks

**Comment by lgrammel** [comment]
## Identify issue type

Identified as **Bug**  
Confidence: **High**

### Rationale
This was a concrete runtime regression in AI SDK 4.0.1, confirmed and fixed by changing a dependency version.

### Evidence
- Upgrading to AI SDK 4.0.1 caused Firebase Functions to throw ERR_REQUIRE_ESM because CommonJS provider-utils required nanoid v5's ES module.
- A maintainer identified the nanoid v5 upgrade as the likely cause and downgraded it in a fix.
- The reporter confirmed the problem was fixed in version 4.0.2.
