### ISSUE TITLE
Tool results no longer being streamed to client in v4

### ISSUE THREAD

**Issue by ian-pascoe** [vercel/ai#3797]
### Description

1. Set up a streaming AI agent using SolidStart
2. Have the agent invoke a tool.
3. Observe as no tool results are streamed in

### Code example

My repository is here: https://github.com/spirit-led-software/theaistudybible

See:
1. apps/www/src/server/api/secure/chat.ts for the api
2. apps/www/src/hooks/use-chat.ts for the client

### AI provider

@ai-sdk/solid 1.0.1

**Comment by lgrammel** [comment]
Hi! I just tried this solid js example and it works for me:

https://github.com/vercel/ai/blob/main/examples/solidstart-openai/src/routes/use-chat-tools/index.tsx

Can you inspect the data that's being transferred to the client in the chrome network tab?

**Comment by lgrammel** [comment]
Feel free to submit a PR that changes this behavior in our solid implementation.

**Comment by ian-pascoe** [comment]
@lgrammel please review the PR attached

**Comment by lgrammel** [comment]
## Identify issue type

Identified as **Bug**  
Confidence: **High**

### Rationale
This describes incorrect reactive updates in the existing Solid integration, affecting streamed tool invocations and annotations. Although the standard example worked for the maintainer, the follow-up identifies a concrete implementation failure rather than merely requesting a new capability.

### Evidence
- In AI SDK v4 with @ai-sdk/solid 1.0.1, tool results reportedly do not appear on the client.
- The reporter found that converting the SDK's messages signal to a Solid store or keyed list prevents message annotations and tool invocations from updating, although message content updates.
- A maintainer invited a PR to change the Solid implementation, and the reporter submitted one.
