### ISSUE TITLE
Duplicate Responses When Using Tool Calling

### ISSUE THREAD

**Issue by jamiebytebender** [vercel/ai#3798]
### Description

I created a repository based on this example: [ai-sdk-preview-roundtrips](https://github.com/jamiebytebender/ai-sdk-preview-roundtrips). In the repo, I added a simple dummy tool to generate descriptions.

**Here's the issue I'm experiencing:**
When I initiate an action and the tool is called, I expect to receive only the tool's response, and the conversation should stop there. However, what actually happens is that I get the tool response, followed by a chat message restating the same content.

**Why this is problematic:**
My use case involves different cards for different tools, each with specific actions (e.g., printing the card content or navigating in different page). I need the tool's response only, without the redundant chat message. This duplication causes confusion and interferes with the expected behavior.

**How to reproduce:**
- Run the example from the repo.
- Click the "Generate description" suggestion.

**Expected behavior:**
Only the tool response is returned.

**Actual behavior:**
Both the tool response and a chat message with the same content are returned.

Let me know if you need more details or clarification!

### AI provider

@ai-sdk/openai 1.0.2

**Comment by lgrammel** [comment]
That is the behavior of how tools with multi-steps work. The LLM consumes the tool results and then generates a text (see e.g. ChatGPT behavior). You could do the following:

a) suppress tool output in the UI
b) or: suppress the assistant output after tool executions in the UI ( this is prob what you want )
c) or: turn of maxSteps on the server side and inject empty assistant msgs before responding

**Comment by jamiebytebender** [comment]
a) I can't do this because the tool output is essential for handling different actions on the card.

b) I've tried suppressing the assistant's output after tool execution, but sometimes the assistant provides valuable messages, like asking the user for more information when something is missing. Suppressing this would mean losing that entirely.

For now, what seems to work most of the time is tweaking the system message to instruct the LLM not to restate the tool response. It's not perfect, but it works better than the other options I've explored.

Thanks for your help!

**Comment by lgrammel** [comment]
## Identify issue type

Identified as **None**  
Confidence: **High**

### Rationale
This is primarily a support discussion about expected multi-step tool behavior, not a confirmed SDK bug or a clearly specified feature request.

### Evidence
- Maintainer explains that the follow-up assistant text is expected behavior for multi-step tool calls: the model consumes the tool result and generates a response.
- The maintainer suggests UI suppression or disabling `maxSteps` rather than identifying an SDK defect.
- The reporter accepts the explanation and describes using a system-message workaround without making a concrete SDK capability request.
