### ISSUE TITLE
assistant message with function_call followed by assistant message with content

### ISSUE THREAD

**Issue by junhongwang418** [vercel/ai#384]
When I receive an assistant message with `function_call` followed by assistant message with `content`, `OpenAIStream` and `useChat` seem to just concatenate the 2 messages as one.

**message**

```
<first assistant message ...>{"function_call": {"name": "<function name ...>", "arguments": "<function arguments ...>"}}
```

I expect `useChat` to handle them as two messages:

**message 1**

```
<first assistant message ...>
```

**message 2**

```
{"function_call": {"name": "<function name ...>", "arguments": "<function arguments ...>"}}
```

**Comment by MaxLeiter** [comment]
are you passing an `experimental_functionHandler` to the client or server?

**Comment by junhongwang418** [comment]
I'm passing `experimental_onFunctionCall` on the client. The callback returns:

```ts
{
  messages: [
    ...chatMessages, // messages so far
    { id: '...', role: 'function', name: '<function name>' content: '<result of function call>' }
  ]
}
```

**Comment by MaxLeiter** [comment]
https://github.com/vercel-labs/ai/pull/425 will resolve this

**Comment by woodbridge** [comment]
@MaxLeiter could you clarify how to use the new experimental streamdata to fix this? running into the same issue as this thread. thank you!

**Comment by lgrammel** [comment]
Please check out our new tool calling with AI SDK Core and `useChat`: https://sdk.vercel.ai/docs/ai-sdk-ui/chatbot-with-tool-calling#example-server-side-tool-execution-with-roundtrips

**Comment by lgrammel** [comment]
## Identify issue type

Identified as **Bug**  
Confidence: **High**

### Rationale
The issue reports concrete incorrect message handling in the existing streaming and tool-calling flow, rather than requesting a new capability.

### Evidence
- `OpenAIStream` and `useChat` concatenate an assistant content message and a subsequent `function_call` instead of preserving them as separate messages.
- The reporter reproduced the behavior while using client-side `experimental_onFunctionCall` and identified the streaming boundary where the function call begins.
- A maintainer stated that PR #425 would resolve the issue, confirming it as behavior requiring a fix.
