### ISSUE TITLE
Tools support for generateObject

### ISSUE THREAD

**Issue by kvz** [vercel/ai#3866]
### Feature Description

With some individual modules by LLM vendors, you can call tools, and get structured output back, validated with Zod helpers, in TypeScript.

I just wanted to try switching to this Vercel AI abstraction, but I cannot, because for some reason, tool use, or safe outputs, are mutually exclusive.

That's too bad, would have loved to use this throughout my projects, as it looks really neat otherwise.

### Use Cases

Someone else also pointed it out here I found: https://github.com/vercel/ai/discussions/1395#discussioncomment-11057195

In a nutshell, there calling tools is useful for integrating LLMs and actually have them make useful contributions. But when they do, you don't want to parse their output manually, as this degrades how reliable you can integrate them. 

With typesafe structured outputs, and tool use, LLMs become really really useful.

Example: chat bot in Slack that processes a thread where it was mentioned, and mark people as absent or present for a call, answer questions, search support tickets, open github tickets, etc. You need the tool use for these integrations. You need the structured outputs so it can safely add emjois, reactions, reply to the correct places, and add any meta conversation about how hard the task was, its confidence, etc, separately.

**Comment by lgrammel** [comment]
We have added a `experimental_output` feature to `generateText` that allows you to create structured information while calling (openai) tools.

https://sdk.vercel.ai/docs/ai-sdk-core/generating-structured-data#structured-output-with-generatetext

**Comment by kvz** [comment]
Very nice @lgrammel!

I noticed only Open AI is supported. I used it with Claude Sonnet 3.5 October 22 and it indeed exploded on returning invalid JSON deep inside the Vercel module.

In the documentation, they mention you can use tools to still make them adhere to structured outputs. They'd call a dummy function that requires a certain schema, and when you capture that call, you basically have the data structure that adheres to a schema. 

Would this be a workaround that Vercel could abstract away under this same interface, while they don't natively support it yet?

**Comment by lgrammel** [comment]
## Identify issue type

Identified as **Feature**  
Confidence: **High**

### Rationale
This asks for expanded structured-output and tool-calling capability, particularly for providers such as Claude, rather than reporting a failure of a documented supported behavior.

### Evidence
- The issue requests combining tool calling with type-safe structured output, which was not supported by `generateObject`.
- A maintainer points to `experimental_output` in `generateText` as partial support when calling OpenAI tools.
- The reporter then asks for equivalent Claude support or an SDK abstraction using a schema-constrained dummy tool as a fallback.
