### ISSUE TITLE
A tool is being called multiple times while using Groq model

### ISSUE THREAD

**Issue by ajaykrupalk** [vercel/ai#3872]
### Description

For one prompt using groq, the tool is show the results multiple times when the tool result should have been just once just like in the below google gemini image. I have tried this with other providers like Mistral, and I am seeing this happen with Groq. I have tried remove maxSteps also, but that didn't help. Using AI SDK 3.3 and GROQ SDK 1.0.3

### IMAGE OF USING GROQ LLAMA 3.1 70B
![image](https://github.com/user-attachments/assets/f00cffc3-497a-4aae-860c-09156d6fd274)

### MAGE OF USING GOOGLE GEMINI 1.5 FLASH 002
![image](https://github.com/user-attachments/assets/c113aa36-e10a-4b68-938a-859ac63f5060)

### AI provider

@ai-sdk/groq 1.0.3

### Additional context

Using AI SDK 3.3 and GROQ SDK 1.0.3, Next.JS

**Comment by lgrammel** [comment]
Can you try with https://github.com/vercel/ai/releases/tag/%40ai-sdk%2Freact%401.0.3 and the latest AI SDK 4.0.5 ? we fixed a bug today that might impact this

**Comment by ajaykrupalk** [comment]
@lgrammel this might break existing code right?

**Comment by ajaykrupalk** [comment]
Oh okay. Just wanted to confirm if it would break things at my end. Thank you.

**Comment by lgrammel** [comment]
## Identify issue type

Identified as **Bug**  
Confidence: **High**

### Rationale
This describes concrete incorrect existing behavior—duplicate tool calls/results—and the maintainer explicitly treats the relevant behavior as a verified bug.

### Evidence
- The report says a single prompt with Groq causes the same tool result to be shown multiple times instead of once.
- The screenshots contrast repeated Groq output with the expected single Gemini output.
- A maintainer states that a potentially related verified bug was fixed and recommends testing updated AI SDK packages.
