### ISSUE TITLE
🐞 Model tried to call unavailable tool 'multi_tool_use.parallel' | Data stream has already been closed.

### ISSUE THREAD

**Issue by oalexdoda** [vercel/ai#3876]
### Description

This is an inconsistent bug, but it triggers around 10% of the time. First, there's no error being thrown (maybe due to this https://github.com/vercel/ai/issues/3875). And if you add a console.error in that dist, here's the error being thrown server-side: 

![image](https://github.com/user-attachments/assets/1baf57da-e229-46d0-9989-8687a5e6e60c)

### Code example

![image](https://github.com/user-attachments/assets/2173c761-2e75-40a0-a19e-27f7bc2aa733)

### AI provider

"@ai-sdk/openai": "^1.0.4",

### Additional context

It seems to happen when using a bunch of tools & streaming to useChat.

**Comment by lgrammel** [comment]
@oalexdoda you can turn off parallel tool calls for openai models in the model settings: https://sdk.vercel.ai/providers/ai-sdk-providers/openai#chat-models

**Comment by oalexdoda** [comment]
> @oalexdoda you can turn off parallel tool calls for openai models in the model settings: https://sdk.vercel.ai/providers/ai-sdk-providers/openai#chat-models

Perfect, thanks @lgrammel - will try that asap.

**Comment by oalexdoda** [comment]
Hey @lgrammel , what's the best way to do that when using the azure wrapper?

![image](https://github.com/user-attachments/assets/b3d09adf-6042-4800-8594-92c6bada5c46)

**Comment by lgrammel** [comment]
## Identify issue type

Identified as **None**  
Confidence: **Medium**

### Rationale
The discussion resolves into a configuration/support question caused by model output rather than a confirmed AI SDK defect or request for new behavior.

### Evidence
- The failure occurs when the model emits an unavailable `multi_tool_use.parallel` tool call.
- The reporter reframed the issue as asking how to disable parallel tool calls.
- A maintainer pointed to the existing OpenAI model setting for disabling parallel tool calls, and the reporter accepted that guidance.
