### ISSUE TITLE
调用streamObject时出现超时问题

### ISSUE THREAD

**Issue by Arthus-wyk** [vercel/ai#3885]
### Description

 lastError: APICallError [AI_APICallError]: Cannot connect to API: Connect Timeout Error (attempted addresses: 172.217.14.202:443, 142.251.33.74:443, 142.250.217.106:443, 142.251.33.106:443, 142.250.69.202:443, 142.251.215.234:443, 172.217.14.234:443, 142.250.217.74:443, 142.251.211.234:443)

### Code example

 const { model: modelNameString, apiKey: modelApiKey, ...modelParams } = config
  const client = createGoogleGenerativeAI({ apiKey : 'xxx'})
  ('models/gemini-1.5-flash-latest')

  try{
    const stream = await streamObject({
      model: client as LanguageModel,
      schema,
      system: toPrompt(template),
      messages,
      mode: getDefaultMode(model),
      ...modelParams,
    })
    return stream.toTextStreamResponse()
  }
  catch(error)
  {
    console.log("error",error)
    return new Response('error.!!'+error, {
      status: 500,
    })
  }

**Comment by lgrammel** [comment]
It looks as if Gemini is not available / reachable in your environment (e.g. because of firewalls or geo ip restrictions).

**Comment by lgrammel** [comment]
## Identify issue type

Identified as **None**  
Confidence: **High**

### Rationale
This is an environment/network connectivity support issue, not a confirmed AI SDK bug, documentation request, example change, or feature request.

### Evidence
- The error is a connection timeout to Google API addresses rather than an SDK processing failure.
- The maintainer states that Gemini is likely unavailable or unreachable due to firewall or geographic restrictions.
- No incorrect AI SDK behavior or requested product change is identified.
