### ISSUE TITLE
UI change between dropdown changes in Cookbook page.

### ISSUE THREAD

**Issue by patelvivekdev** [vercel/ai#3909]
### Description

Hey @jeremyphilemon, I just found this in https://sdk.vercel.ai/cookbook

I tested with Chrome and Firefox.

https://github.com/user-attachments/assets/54333cd4-11d2-46a8-9cfd-714797124078

**Comment by lgrammel** [comment]
## Identify issue type

Identified as **Bug**  
Confidence: **Medium**

### Rationale
This describes a concrete cross-browser UI malfunction on an existing Cookbook page rather than a request to change its written content or add an example.

### Evidence
- Reports an unintended UI change when switching dropdown selections on the AI SDK Cookbook page.
- The behavior was reproduced in both Chrome and Firefox and accompanied by a screen recording.
