### ISSUE TITLE
No results from model with tools config

### ISSUE THREAD

**Issue by dprosper** [vercel/ai#3957]
### Description

Using the guide: https://sdk.vercel.ai/docs/guides/rag-chatbot

Follow the steps above to build the OpenAI example to the end and validate that it works. 

Replace openai with ollama in the api/chat/route.ts 

```sh
import { createOllama } from 'ollama-ai-provider';
....
const ollama = createOllama({
  baseURL: 'http://localhost:11434/api',
})

.....

 const result = streamText({
    model: ollama(`llama3.2:latest`), 
    messages,

....
```

If you remove the tools config in the streamText you can see an output from the model, once you add the tools config back you get no response from the model.

### AI provider

ollama-ai-provider 1.0.0 and ai 4.0.10

**Comment by MaximeNoulin** [comment]
I think this might be due to the bug: https://github.com/vercel/ai/issues/3953

I could get this bug too

**Comment by edisonLzy** [comment]
me too , but generateText API work well 🤔

**Comment by MaximeNoulin** [comment]
@edisonLzy it would be normal with this issue https://github.com/vercel/ai/issues/3953 because in case of generateText, the model would have provided a full answer for the tool-call before it gets executed

**Comment by edisonLzy** [comment]
@MaximeNoulin Thanks for your explanation 😄

**Comment by lgrammel** [comment]
This is an issue with the Ollama provider, which is maintained in a separate repository: https://github.com/sgomez/ollama-ai-provider/tree/main/packages/ollama

Please file a bug report there.

CC @sgomez

**Comment by lgrammel** [comment]
Also it is unlikely to be related to #3953 since it's a different provider and not duplicating any tool calls.

**Comment by lgrammel** [comment]
## Identify issue type

Identified as **None**  
Confidence: **High**

### Rationale
Although a concrete failure is reported, the maintainer identifies it as an issue in a third-party provider rather than in the vercel/ai repository. For this repository, it is therefore not a supported bug classification.

### Evidence
- `streamText` produces no response when tools are enabled with `ollama-ai-provider`, while removing tools or using `generateText` works.
- A maintainer states that the problem is in the separately maintained Ollama provider and asks for the bug to be filed in that repository.
- The maintainer also rejects the suggested connection to AI SDK issue #3953.
