### ISSUE TITLE
Distinguish tool-error in the stream

### ISSUE THREAD

**Issue by punkpeye** [vercel/ai#3975]
### Feature Description

At the moment, errors that happen during tool invocation are indistinguishable from those that happened for other reasons.

For logging purposes, I need a method to associate errors with tool invocations.

**Comment by lgrammel** [comment]
https://github.com/vercel/ai/pull/3984

**Comment by lgrammel** [comment]
## Identify issue type

Identified as **Feature**  
Confidence: **High**

### Rationale
This asks for new error-classification capability in streamed tool invocation handling, rather than reporting a failure of documented existing behavior.

### Evidence
- The issue explicitly requests a way to distinguish errors arising during tool invocation from other stream errors.
- The requested capability is motivated by associating logged errors with tool invocations.
- A maintainer linked PR #3984, indicating implementation work for the requested enhancement.
