### ISSUE TITLE
Gemini model throws error: "Penalty is not enabled for models/gemini-exp-1206"

### ISSUE THREAD

**Issue by p971607** [vercel/ai#4022]
### Description

When using `gemini-exp-1206` model with penalty parameters, it throws an error. However, the same configuration works fine with `gemini-1.5-flash-002`. This suggests that penalty parameters support varies between different Gemini model versions.

Reproduction steps:
1. Install the latest version of AI SDK and Google provider:
{
"dependencies": {
"ai": "^4.0.13",
"@ai-sdk/google": "^1.0.3",
"@ai-sdk/google-vertex": "^2.0.1"
}
}
2. Try to use Gemini model with penalty parameters:
const result = await generateObject({
model: provider,
schema: titleSchema,
schemaName: 'BookTitles',
system: systemPrompt,
prompt: userPrompt,
maxTokens: 8100,
temperature: 0.82,
presencePenalty: 0.65, // This causes error
frequencyPenalty: 0.65, // This causes error
topP: 0.88
});

### Code example

import { generateObject } from 'ai';
import { createGoogleGenerativeAI } from '@ai-sdk/google';
const provider = createGoogleGenerativeAI({ apiKey })(modelName);

const result = await generateObject({
model: provider,
schema: tiSchema,
schemaName: '',
system: systemPrompt,
prompt: userPrompt,
maxTokens: 8100,
temperature: 0.82,
presencePenalty: 0.65, // This causes error
frequencyPenalty: 0.65, // This causes error
topP: 0.88
});

### AI provider

@ai-sdk/google v1.0.3

### Additional context

Additional context:
The error suggests that Gemini models don't support penalty parameters, but the SDK doesn't handle this gracefully or document this limitation. It would be helpful :
Automatically remove unsupported parameters for specific models

**Comment by lgrammel** [comment]
## Identify issue type

Identified as **Feature**  
Confidence: **High**

### Rationale
The current error forwarding is confirmed as expected behavior; automatically filtering unsupported parameters would be a new model-specific capability rather than a fix to broken behavior.

### Evidence
- The error occurs when unsupported penalty parameters are sent to the experimental `gemini-exp-1206` model.
- The reporter requests that the SDK automatically remove parameters unsupported by specific models.
- A maintainer states that the provider error is forwarded as expected and that model-specific handling will not be added for this experimental model.
