### ISSUE TITLE
Optionally pass server-side function calls back to client

### ISSUE THREAD

**Issue by juliuslipp** [vercel/ai#404]
Currently, the execution of server-side functions remains hidden from the client, with only the model response relayed back to the client-side. Would be nice to be able to display a function call loading state, the finished results and of course the model response similiar to ChatGPT

**Comment by valstu** [comment]
Facing the same problem, I want to run functions on server side but relay the function call messages back to UI. Is there any docs (or implementation code) about the experimental data API?

**Comment by MaxLeiter** [comment]
Sorry for the late follow-up; docs were written a while ago but I missed this issue.

https://sdk.vercel.ai/docs/api-reference/stream-data

**Comment by lgrammel** [comment]
## Identify issue type

Identified as **Examples**  
Confidence: **High**

### Rationale
The remaining requested work is to provide a runnable example showing how to relay server-side function-call state and results to the client, rather than add new SDK behavior.

### Evidence
- The requested server-to-client function-call data can already be sent using the experimental data API.
- A maintainer stated that an example was needed to demonstrate this workflow.
- Existing API documentation was later linked, indicating the capability itself was already implemented.
