### ISSUE TITLE
Claude 3.5 Sonnet streaming super laggy in AI SDK

### ISSUE THREAD

**Issue by Nazariy995** [vercel/ai#4057]
### Description

We have been using AI SDK for a while and it has been amazing, but using vercel SDK with Claude 3.5 sonnet is super choppy.

The streaming seems so choppy like almost unusable!

Even in the playground you guys have, it is super. choppy.

Here is an example in our app 👇
![CleanShot 2024-12-09 at 23 51 06](https://github.com/user-attachments/assets/2010b425-44b3-4bb6-a86e-1313cb499658)

Now when you compare to AI SDK GPT-4o it is super smooth streaming and very pleasant to the eyes. 

When you start to see big blocks of text appear randomly and then pause and then resume, it doesn't make for a smooth experience, and I am not sure what to really do here

I just don't understand why, when streaming in claude.ai is so smooth. 

It only happens with Claude 3.5 sonnet. 

What can we do?

### AI provider

"@ai-sdk/anthropic": "^0.0.51",

**Comment by lgrammel** [comment]
We added stream transformations and a stream smoothing helper in AI SDK `4.0.15`: https://sdk.vercel.ai/docs/ai-sdk-core/generating-text#stream-transformation

Please give it a try.

**Comment by lgrammel** [comment]
## Identify issue type

Identified as **Bug**  
Confidence: **High**

### Rationale
The issue reports a concrete usability/performance problem in existing Claude streaming behavior rather than merely requesting a new capability. The later smoothing helper provides a workaround for the reported failure.

### Evidence
- Claude 3.5 Sonnet reportedly streams text in large, intermittent chunks and pauses, making output unusually choppy in both the reporter’s app and the AI SDK playground.
- The reporter contrasts this with smooth GPT-4o and claude.ai streaming, indicating a provider-specific failure in current behavior.
- A maintainer recommended the stream smoothing helper added in AI SDK 4.0.15 as mitigation.
