### ISSUE TITLE
Getting an error trying to use o1 with the latest 1.0.9 openai sdk

### ISSUE THREAD

**Issue by spullara** [vercel/ai#4144]
### Description

Calling streamText with simulatedStreaming: true

AI_APICallError: Unsupported parameter: 'temperature' is not supported with this model.

### Code example

// We don't set temperature anywhere

const stream = streamText({
  model,
  ...(system ? { system } : {}),
  ...(tools ? { tools } : {}),
  messages: chatMessages,
  maxSteps: 50,
  experimental_toolCallStreaming: true,
  onFinish: async () => {
  if (cache_markers.length > 0) {
	  streamingData.writeData({ cache_markers });
  }
  }
});

### AI provider

@ai-sdk/openai 1.0.9

**Comment by lgrammel** [comment]
Thanks for the bug report. Can you try with `@ai-sdk/openai@1.0.10`?

**Comment by spullara** [comment]
fixed in 1.0.10

**Comment by lgrammel** [comment]
## Identify issue type

Identified as **Bug**  
Confidence: **High**

### Rationale
This was a concrete provider behavior defect in `@ai-sdk/openai@1.0.9` that caused an unexpected API error and was corrected in the next patch release.

### Evidence
- `streamText` with an o1 model failed because the provider sent the unsupported `temperature` parameter even though the caller did not set it.
- A maintainer explicitly called it a bug report and asked the reporter to test `@ai-sdk/openai@1.0.10`.
- The reporter confirmed the issue was fixed in version 1.0.10.
