### ISSUE TITLE
type: 'tool-result' is missing in toolResults array

### ISSUE THREAD

**Issue by hopkins385** [vercel/ai#4165]
### Description

I was wondering why I get the following error:

``` AI_InvalidPromptError: Invalid prompt: messages must be an array of CoreMessage or UIMessage```

### Code example

After a longer debug session, I was able to figure out that ` "type": "tool-result" ` is missing in the toolResults response array

```js
const { text, steps, finishReason, toolCalls, toolResults } =
   await generateText({
   model,
   maxTokens: payload.maxTokens,
   temperature: payload.temperature,
   messages: initialMessages,
   tools: availableTools,
   maxSteps: 1,
 });

console.log(toolResults)
 ```
This is how the array looks like:
```
[
  {
    "toolCallId": "toolu_01MS2kwPbcjubBfCX9Sy6HEH",
    "toolName": "website",
    "args": {
      "url": "https://someurl.com"
    },
    "result": {
      "meta": null,
      "body": "some response"
    }
  }
]
```
But the array should look like

```
[
  {
     "type": "tool-result",
    "toolCallId": "toolu_01MS2kwPbcjubBfCX9Sy6HEH",
    "toolName": "website",
    "args": {
      "url": "https://someurl.com"
    },
    "result": {
      "meta": null,
      "body": "some response"
    }
  }
]
```

Temporarily fix:
``` 
 const newToolResults = toolResults.map((toolResult) => {
      return {
        ...toolResult,
        type: "tool-result",
      };
    });
```

### AI provider

@ai-sdk/anthropic v1.0.5

### Additional context

"@ai-sdk/anthropic": "^1.0.5",
"@ai-sdk/google": "^1.0.11",
 "@ai-sdk/mistral": "^1.0.5",
"@ai-sdk/openai": "^1.0.10",
"ai": "^4.0.20",

**Comment by lgrammel** [comment]
Reproduced.

**Comment by lgrammel** [comment]
## Identify issue type

Identified as **Bug**  
Confidence: **High**

### Rationale
This is a concrete, reproducible failure in existing AI SDK output: returned tool results omit a discriminator required for valid prompt messages.

### Evidence
- `generateText` returns `toolResults` entries without the required `type: "tool-result"` field.
- Using the returned array as prompt messages triggers `AI_InvalidPromptError`.
- The reporter provides a workaround that manually adds the missing field.
- A maintainer confirmed the issue was reproduced.
