### ISSUE TITLE
AI don't ask for the required parameters if the user didn't put any ?

### ISSUE THREAD

**Issue by risqiikhsani** [vercel/ai#4169]
### Description

I tried to use tools to make user easier to subscribe to company,
but when user say I want to subscribe to company, the AI generates random parameters and execute the tool right away.
how do I make the AI asks for the users input before proceeding, if user didn't specify any ?
I did write the prompt to make AI asks for user input but didn't work.
I did write it to parameter's description as well, didn't work.

![Screenshot from 2024-12-20 20-16-13](https://github.com/user-attachments/assets/e248fa66-409f-42ec-a35f-97a53beb299a)

what am I missing here?

### Code example

      subscribeToCompany: tool({
        description:"User subscribe to company using their email address",
        parameters:z.object({
          email:z.string().email().describe("Email address from user input")
        }),
        execute: async({email}) => {
          try {
            const data = {
              type:"subscribers",
              id:email,
              createdAt: new Date().toISOString(),
            }
            await CreateItem(data);
            return { message: "Successfully subscribe to company." };
          } catch (error) {
            console.error("Failed subscribe to company. ", error);
          }
        }
      })

### AI provider

@ai-sdk/amazon-bedrock

**Comment by lgrammel** [comment]
LLMs will make up information unless you give them an escape hatch and clear instructions. This issue commonly called "hallucination". You need to describe how LLMs need to behave in the prompt (ideally with examples) and support asking questions in the structure that you generate. Alternatively you could introduce separate LLM validation steps (checking if the information from the structure is actually present in the user request).

**Comment by nicoalbanese** [comment]
Also worth mentioning that smaller models can be less effective with tools.

**Comment by lgrammel** [comment]
## Identify issue type

Identified as **None**  
Confidence: **High**

### Rationale
This is primarily a usage/support question about controlling model behavior, not a demonstrated defect or request for a specific SDK capability.

### Evidence
- The model supplied a fabricated email address when invoking a tool after the user omitted that required information.
- The reporter asks how to make the model request missing input rather than identifying a documented SDK guarantee that failed.
- Maintainers characterize this as LLM hallucination and recommend clearer prompting, question-supporting output structure, examples, or a separate validation step.
