### ISSUE TITLE
Question about mocking the input `res` arg to the `OpenAIStream` function

### ISSUE THREAD

**Issue by madooei** [vercel/ai#453]
For mocking API calls to OpenAI, can I send a regular `ReadableStream` inside a `Response` object to the `OpenAIStream` function https://github.com/vercel/ai/blob/9316842ec2224ac7adb916131c862020baef56a5/packages/core/streams/openai-stream.ts#L261-L264

Here is a contrived example: 

```ts
async function mock (query: string): Promise<Response> {
    const response = `Received: ${query}`

    const stream = new ReadableStream({
      start(controller) {
        const utf8Encoder = new TextEncoder()
        const data = utf8Encoder.encode(response)
        controller.enqueue(data)
        controller.close()
      },
    })

    return new Response(stream, {
      headers: { "Content-Type": "text/plain" },
      status: 200,
    })
}

async function chat(response: Response) : Promise<StreamingTextResponse> {
    const readableStream = OpenAIStream(response, {
      onStart: async () => { },
      onToken: async (token: string) => { },
      onCompletion: async (completion: string) => { },
    })
    return new StreamingTextResponse(readableStream)
}
```

If I call the `mock` function and pass the returned `Response` object to the `chat` function, I will end up with an empty stream!

**Comment by MaxLeiter** [comment]
Take a look at `parseOpenAIStream()` and `chunkToText()` in `openai-stream`: https://github.com/vercel/ai/blob/7b389a7370c65b3e9254f7d9696f7f95d06af305/packages/core/streams/openai-stream.ts#L179

If you make your response model that it should work.

**Comment by pranjal1006** [comment]
@madooei were you able to make progress. Could you please share some working snippets if it's not too much trouble. Thanks

**Comment by lgrammel** [comment]
## Identify issue type

Identified as **None**  
Confidence: **High**

### Rationale
This is primarily a usage and support question about constructing a compatible mock OpenAI response, rather than a confirmed bug or requested enhancement.

### Evidence
- The reporter asks how to mock the `Response` input to `OpenAIStream` after a plain-text stream produces no output.
- A maintainer explains that the mock response must follow the format expected by `parseOpenAIStream()` and `chunkToText()`.
- No SDK defect or requested product/documentation change is established in the comments.
