### ISSUE TITLE
experimental_onFunctionCall on the frontend

### ISSUE THREAD

**Issue by cosbgn** [vercel/ai#465]
I like the `experimental_onFunctionCall` it works very well in the backend, however it would be a better UX, if I could send the function_response_json to the frontend and then make a second request to my backend to have the AI analyze the data and respond. This would immediately show the API response to the user, and then wait for the AI stream.

This could be easy done if we could have `experimental_onFunctionCall` as a callback for both `OpenAIStream` in the backedn and `useChat()` in the frontend.

**Comment by cosbgn** [comment]
The current workaround is to try to parse onFinish and try to guess if it's a function call or not.

**Comment by MaxLeiter** [comment]
Please see https://sdk.vercel.ai/docs/guides/providers/openai-functions#handling-function-calls-on-the-client

**Comment by cosbgn** [comment]
@MaxLeiter this is not available on `ai/vue` right?

**Comment by MaxLeiter** [comment]
I assumed you were using react, sorry. The message will still be returned to the client, but it won't be handled by the hook, you are right. You should be able to manually handle it in `messages`.

**Comment by cosbgn** [comment]
Thanks a lot for letting me know!

**Comment by lgrammel** [comment]
## Identify issue type

Identified as **Feature**  
Confidence: **High**

### Rationale
This requests adding function-call handling capability to the Vue frontend hook rather than reporting a failure of documented existing behavior.

### Evidence
- The requester asks for an `experimental_onFunctionCall` callback in the frontend hook to support a two-step function-call flow.
- A maintainer confirms React supports client-side handling but the Vue hook does not, and says the implementations are intended to be unified.
