### ISSUE TITLE
eval_code_in_browser function does not get executed in next-openai example anymore

### ISSUE THREAD

**Issue by carlojoerges** [vercel/ai#467]
repro:
1. install example via npx create-next-app --example https://github.com/vercel/ai/tree/main/examples/next-openai next-openai-app
2. create local env file with openai credentials
3. npm run dev
4. navigate to http://localhost:3000/function-calling
5. send message: execute javascript alert('bla')
6. you get an empty function: and assistant: response back 

calling the weather function that is handled on the server still works fine. but it appears that the experimental_onFunctionCall handler in the client never gets called

**Comment by odysseaspapadimas** [comment]
I noticed this on my application as well when migrating to the latest ai/openai versions. Code inside the client `functionCallHandler` runs but this for example won't trigger a response from the ai
```tsx
    if (functionCall.name === "get_current_time") {
      const time = new Date().toLocaleTimeString();

      const functionResponse: ChatRequest = {
        messages: [
          ...chatMessages,
          {
            id: nanoid(),
            name: "get_current_time",
            role: "function" as const,
            content: JSON.stringify({ time }),
          },
        ],
      };

      return functionResponse;
    } 
```
Server side function handling works fine

**Comment by lgrammel** [comment]
## Identify issue type

Identified as **Bug**  
Confidence: **High**

### Rationale
This reports a concrete regression in existing client-side function-calling behavior, with reproducible steps and corroboration after upgrading SDK versions.

### Evidence
- The `next-openai` function-calling example returns an empty function/assistant response instead of executing the browser-side `eval_code_in_browser` function.
- The reporter states that `experimental_onFunctionCall` on the client is never called, while server-side weather function handling still works.
- A commenter reproduced related behavior after upgrading: the client handler runs, but its returned function response does not trigger a subsequent AI response.
