### ISSUE TITLE
[feature] agents.js template

### ISSUE THREAD

**Issue by deboboy** [vercel/ai#485]
Add a template with Hugging Face agents.js

- App router based
- Default tools support 
- agent.run disabled by default; i.e. use generateCode and evaluateCode

**Comment by lgrammel** [comment]
## Identify issue type

Identified as **Feature**  
Confidence: **High**

### Rationale
This requests a new template and associated capabilities rather than reporting broken existing behavior. Although it concerns a template, it is framed as adding a new product capability, not correcting an existing runnable example.

### Evidence
- The issue explicitly requests adding a new template using Hugging Face agents.js.
- It specifies desired template capabilities: App Router, default tools, and use of generateCode/evaluateCode instead of agent.run.
