### ISSUE TITLE
experimental_onFunctionCall should accept a second argument to the callback signifying success

### ISSUE THREAD

**Issue by alii** [vercel/ai#505]
On the line below, the messages array for the next function call is mutated. This is great in almost every situation, but in the case that we want to retry the last function call (while reusing the history for previous messages), we need to mutate the `newFunctionCallMessages` array directly inside of the callback.

https://github.com/vercel/ai/blob/f8964d946480c4c3c5f31ecb83fd067180c731ff/packages/core/streams/openai-stream.ts#L461

Currently, this is how I've worked around the issue. Unfortunately we still need to call `createFunctionCallMessages` to get the most recent messages, otherwise it's impossible to access them inside of the callbacks.

```typescript
const newFunctionCallMessages = createFunctionCallMessages(null);

// Mutate the internal array so that we don't reuse them in future retries
// TODO(@alii): Find a better way to do this (this may include submitting an issue to vercel/ai)
// See here it mutates the messages for the next call as well as returns them:
// https://github.com/vercel/ai/blob/f8964d946480c4c3c5f31ecb83fd067180c731ff/packages/core/streams/openai-stream.ts#L461
newFunctionCallMessages.splice(-2, 2);

return getNextStream(newFunctionCallMessages);
```

I propose two solutions. The first being that `createFunctionCallMessages` can accept a second argument, a boolean, indicating if we should mutate the array or not, and have it true by default (so not to be a breaking change). The other solution would be to introduce a third parameter to `experimental_onFunctionCall`, which would be an array of all current messages (including the most recent function call). We could then simply slice off the last two to execute a retry, and not have to call `createFunctionCallMessages` and therefore not mutating the array.

Fwiw, the reason I wanted retrying in the first place is because the models do actually hallucinate arguments/function names sometimes. It happens so rarely, but for a reliable system I wanted to make sure that the calls never fail. It happens so rarely that happening more than once in a row is exceptionally improbable.

If a decision is made on which solution to go with (or indeed any other alternative solution) I'd be more than happy to contribute a PR also.

Thank you! 🫶

**Comment by lgrammel** [comment]
## Identify issue type

Identified as **Feature**  
Confidence: **High**

### Rationale
This requests an API enhancement to support retries and control or avoid message mutation; it does not establish that existing promised behavior is broken.

### Evidence
- The callback currently mutates the message array used for the next function call, which makes retrying the latest call while preserving earlier history difficult.
- The reporter proposes expanding the API with a mutation-control boolean or an additional callback parameter containing all current messages.
- The request is framed as support for a new retry workflow rather than a violation of documented behavior.
