### ISSUE TITLE
nanoid seems to prevent build on sveltekit

### ISSUE THREAD

**Issue by jurb** [vercel/ai#507]
When I build my project using this library with sveltekit using `pnpm run build`, I get the following error message:

```
Error [ERR_UNSUPPORTED_DIR_IMPORT]: Directory import '/Users/jur/repos/node_modules/nanoid/non-secure' is not supported resolving ES modules imported from /Users/jur/repos/gpt/.svelte-kit/output/server/entries/endpoints/api/chat/_server.ts.js
Did you mean to import nanoid/non-secure/index.js?
```

I don't exactly understand the problem but this nanoid issue might help: https://github.com/ai/nanoid/issues/365.

**Comment by MaxLeiter** [comment]
Our package uses `nanoid@3.3.6`, so I think this is an upstream problem. 

Running `pnpm -r why nanoid` in the `ai` root I see `nanoid 4.0.2` only under `nuxt/telemetry`, not under any of the sveltekit packages.

**Comment by jurb** [comment]
You are right, a bare app from the example does build. My apologies!

**Comment by lgrammel** [comment]
## Identify issue type

Identified as **None**  
Confidence: **High**

### Rationale
The follow-up indicates the failure was specific to the reporter's dependency setup rather than a reproducible AI SDK defect, making this a resolved support report rather than a bug.

### Evidence
- The reported SvelteKit build failed on an unsupported `nanoid/non-secure` directory import.
- A maintainer noted the SDK uses `nanoid@3.3.6` and suggested the conflicting version was from another dependency.
- The reporter confirmed that a bare app based on the example builds successfully and apologized for the report.
