### ISSUE TITLE
Add Hono.js example

### ISSUE THREAD

**Issue by yutakobayashidev** [vercel/ai#516]
Hono.js is a web framework for the Edge environment. Works with Cloudflare Workers, Deno, Bun, Fastly, Vercel, Netlify, Lagon, AWS, Node.js.

Now that the Vercel AI SDK runs in Hono.js and the OpenAI package runs in Edge, you can build the backend of your AI application in a few dozen lines of code.

https://twitter.com/ogtimothymiller/status/1694208003346407722

https://hono.dev/

**Comment by MaxLeiter** [comment]
A PR with docs and/or an example would be accepted if you'd like to submit one

**Comment by lgrammel** [comment]
Node http server example: https://github.com/vercel/ai/tree/main/examples/node-http-server

**Comment by yutakobayashidev** [comment]
Hono also runs in Node.js, but the core is web-standard and optimized for the Edge environment.

Recently, Hono maintainers created an Example:

https://github.com/yusukebe/hono-with-vercel-ai

**Comment by lgrammel** [comment]
@yutakobayashidev sadly their example is outdated. I'll send a PR to update it to AI SDK 3.1 when I find the time

**Comment by KorigamiK** [comment]
> @yutakobayashidev sadly their example is outdated. I'll send a PR to update it to AI SDK 3.1 when I find the time

would appreciate this so much!

**Comment by KorigamiK** [comment]
If you're trying this out on bun it's currently not supported. https://github.com/oven-sh/bun/issues/5648

**Comment by ansh** [comment]
Did you update it? @lgrammel

**Comment by n1ckoates** [comment]
Submitted a PR to update Hono's example to AI SDK Core: https://github.com/yusukebe/hono-with-vercel-ai/pull/1

**Comment by lgrammel** [comment]
## Identify issue type

Identified as **Examples**  
Confidence: **High**

### Rationale
The issue requests a runnable integration example for using the AI SDK with Hono.js, rather than a change to SDK behavior.

### Evidence
- The title explicitly requests adding a Hono.js example.
- A maintainer said a PR with documentation and/or an example would be accepted.
- The discussion tracks creation and updating of Hono sample code, ending with a link to the published Hono API-server example.
