### ISSUE TITLE
useChat calls the onFinish callback function, but the messages have not been updated.

### ISSUE THREAD

**Issue by ZeusFunk** [vercel/ai#525]
const { messages, input, handleInputChange, setMessages, handleSubmit } =
    useChat({
      api: "/api/***",
      onFinish: () => {
        console.log(messages);
    });

As shown in the code above, after completing the first streaming response, the 'message' is an empty array; after completing the second streaming response, the 'message' is an array with a length of two, displaying the message of the first conversation.

How can I solve this? Is it because of the timing of the onFinish callback function being called?

**Comment by ExLineP** [comment]
same here

**Comment by ZeusFunk** [comment]
thanks

**Comment by lgrammel** [comment]
## Identify issue type

Identified as **None**  
Confidence: **High**

### Rationale
This is a usage/support question caused by React render timing and closure state, with an existing callback parameter providing the needed message. It does not establish a bug or request a product or documentation change.

### Evidence
- The reporter asks how to access the completed response because the captured `messages` value is stale inside `onFinish`.
- A maintainer explains that `messages` updates after a re-render and recommends using the `Message` argument passed to `onFinish`.
- The reporter acknowledges the solution without identifying broken SDK behavior.
