### ISSUE TITLE
Please remove openai-edge as dependencies

### ISSUE THREAD

**Issue by lucasjinreal** [vercel/ai#533]
I tried using official OpenAI with my custom url, it was like a charm, the openai-edge from someone's third party work just didn't response.

**Please using official openAI-node lib, since it was already using fetch**.

```
const stream = await openai.chat.completions.create({
    model: 'gpt-3.5-turbo',
    messages,
    temperature: 0.7,
    stream: true
  })

  for await (const part of stream) {
    console.log(part.choices[0]?.delta?.content || '')
  }
```

It works very good.

The only thing is that, how does the stream covert to your SDK: `StreamingTextResponse` ?

**Comment by MaxLeiter** [comment]
We don’t have openai-edge as a dependency anymore. Please update to a newer version.

**Comment by lgrammel** [comment]
## Identify issue type

Identified as **None**  
Confidence: **High**

### Rationale
The requested dependency change had already been completed, and the remaining content is a usage/support question rather than a current bug or new feature request.

### Evidence
- The request is to remove `openai-edge` and use the official OpenAI Node library.
- The maintainer states that `openai-edge` is no longer a dependency and advises updating to a newer version.
- The remaining question asks how to convert the OpenAI stream for use with `StreamingTextResponse`.
