### ISSUE TITLE
Typo in API Code Example on AI SDK Chat Playground Website

### ISSUE THREAD

**Issue by ashraymallesh** [vercel/ai#540]
**Small Typo on the Website**

<img width="531" alt="Screenshot 2023-09-05 at 6 23 30 PM" src="https://github.com/vercel/ai/assets/28895464/e8fa70e0-fbaf-49f5-8c4c-a864ba80b43c">

`const openai = new OpenAI({apiKey: process.env.OPENAI_API_KEY!)}`
should be
` const openai = new OpenAI({apiKey: process.env.OPENAI_API_KEY!})` 

**The order of the closing ) and } brackets need to be reversed**

**Comment by MaxLeiter** [comment]
Thank you!

**Comment by lgrammel** [comment]
## Identify issue type

Identified as **Documentation**  
Confidence: **High**

### Rationale
This is a typo in a website code example, requiring correction of documentation/sample content rather than SDK behavior.

### Evidence
- The website’s API code sample has mismatched closing delimiters: `new OpenAI({apiKey: process.env.OPENAI_API_KEY!)}` instead of `new OpenAI({apiKey: process.env.OPENAI_API_KEY!})`.
- The requested change is a correction to displayed sample code on the AI SDK Chat Playground website.
