### ISSUE TITLE
useChat onFinish accesses an old state of messages

### ISSUE THREAD

**Issue by dilanustek** [vercel/ai#550]
When I console.log(messages) within the onFinish callback, I get the previous state of messages from when the user last interacted. If I log messages after the useChat hook's definition, I get the correct messages printed. There seems to be a bug here and it seems related to [this issue](https://github.com/vercel/ai/issues/548). 

For example:
- lets start with initial message A. 
- the user sends message B.
- the console.log(messages) in the component prints A,B,C as we receive tokens from openAI for message C.
- the console.log(messages) within the onFinish callback only prints A once it is called at the end.

**Comment by davit-b** [comment]
Yes, https://github.com/vercel/ai/issues/548 and this are related if not the same.

**Comment by davit-b** [comment]
This may be intentional. It follows the TanStack Query's design patterns for forcing a user to avoid using `onFinish` or `onComplete` to trigger side-effects. 

I remember the creators of TanStack were very unhappy with users continually attempting to trigger client-side side effects on the `onFinish` of a mutation. I was one of those users, and this is where I first discovered that my first-instinct was considered an anti-pattern.

**Comment by ctate** [comment]
@dilanustek `messages` is updated after `onFinish` in the lifecycle.

You can access the latest message via the `message` param in `onFinish`:

```ts
const {
  handleInputChange,
  handleSubmit,
  input,
  messages,
  setMessages
} = useChat({
  onFinish: (message) => {
    // user prompt
    console.log(input);

    // ai response
    console.log(message);

    // previous messages (minus user prompt and ai response)
    console.log(messages);
  },
});
```

You can possibly use these to forgo the need of handling any side effects depending on your use case.

**Comment by dilanustek** [comment]
Hello,

Thank you so much for your quick reply! However, using "input" to grab the user input didn't work me as we do not use the setInput to set the message. We use the handleSubmit function instead. So the input string is actually an empty string in this case. Is there any way to go around that? 

Thanks!

**Comment by egold** [comment]
> @dilanustek `messages` is updated after `onFinish` in the lifecycle.
> 
> You can access the latest message via the `message` param in `onFinish`:
> 
> ```ts
> const {
>   handleInputChange,
>   handleSubmit,
>   input,
>   messages,
>   setMessages
> } = useChat({
>   onFinish: (message) => {
>     // user prompt
>     console.log(input);
> 
>     // ai response
>     console.log(message);
> 
>     // previous messages (minus user prompt and ai response)
>     console.log(messages);
>   },
> });
> ```
> 
> You can possibly use these to forgo the need of handling any side effects depending on your use case.

The issue with this workaround is you don't get access to the entire latest user message. For things like the `id` property. My use case is I'm saving conversation history to the database, and this would be a convenient place to store the messages because 

1. I know they're done streaming
2. I ostensibly would have access to the Message objects' `id` property for some idempotency

My use case must be fairly standard for people streaming conversational messages and wanting them to persist between page loads / app sessions I'd think?

**Comment by kblizeck** [comment]
@dilanustek @egold Can I inquire as to what you did to solve this? Facing the same issue and running in circles trying to determine the best way to save these messages to a db.

**Comment by avradip** [comment]
I think this should work for saving to the db use case, slight modification of @ilyakam 's example

```
  React.useEffect(() => {
    // All messages have id populated
    console.log('latest messages', messages);
    // Save the last one to db, along with list of previous msg ids
  }, [messages?.length]);
```

**Comment by satyaborg** [comment]
@avradip the above would not work as `messages?.length` would change right when streaming begins, appending the `messages` array with incomplete tokens. Instead try:
```
import { useChat } from "ai/react";
import { customAlphabet } from "nanoid/non-secure";

// default 7-character random string generator for chat ids
export const nanoid = customAlphabet(
  "0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz",
  7
);

const { messages, input, handleInputChange, handleSubmit, isLoading } =
  useChat({
    onFinish: (message) => {
      const payload = [
        { id: nanoid(), role: "user", content: input, createdAt: new Date() },
        { ...message },
      ];
      console.log("payload", payload);
    },
  });
```

**Comment by moyezr** [comment]
All these examples won't work if you want to store the toolInvocations also.

**Comment by lgrammel** [comment]
## Identify issue type

Identified as **Bug**  
Confidence: **Medium**

### Rationale
The issue reports a concrete stale-state problem in an existing callback lifecycle: consumers cannot access the complete current messages when completion is signaled. Although one comment suggests the ordering may be intentional, the observed behavior is presented as broken and materially limits standard persistence use cases.

### Evidence
- `useChat`'s `onFinish` callback observes the previous `messages` state rather than the completed conversation visible in the component.
- A commenter confirms that `messages` is updated only after `onFinish` runs.
- Reported workarounds do not provide the full latest message objects, including IDs and tool invocations needed for persistence.
