### ISSUE TITLE
Feedback for “StreamingTextResponse”

### ISSUE THREAD

**Issue by brentreilly** [vercel/ai#559]
This works perfectly in dev but I can't get it to work in production. See [this issue](https://github.com/withastro/astro/issues/8521) for details and reproduction. Any help would be greatly appreciated!

**Comment by pangao66** [comment]
I have the  similar  question  
https://github.com/vercel/ai/issues/239
Even until now, this issue has not been resolved.

**Comment by lgrammel** [comment]
## Identify issue type

Identified as **Bug**  
Confidence: **Medium**

### Rationale
The issue reports an environment-dependent failure of existing streaming behavior, although the available details do not establish whether the cause is the AI SDK, Astro, or deployment configuration.

### Evidence
- `StreamingTextResponse` reportedly works in development but not in production.
- Another user reports a similar problem and suggests enabling the edge runtime and response streaming configuration.
