### ISSUE TITLE
Object literal may only specify known properties, and 'experimental_onFunctionCall' does not exist in type 'UseCompletionOptions'

### ISSUE THREAD

**Issue by mr-chandan** [vercel/ai#560]
![image](https://github.com/vercel/ai/assets/106821717/5e5ed3ac-f640-4f45-8cea-5473b2025e22)
Object literal may only specify known properties, and 'experimental_onFunctionCall' does not exist in type 'UseCompletionOptions' error on using experimental_onFunctionCall: functionCallHandler,

**Comment by lgrammel** [comment]
## Identify issue type

Identified as **None**  
Confidence: **Medium**

### Rationale
This is an unclear usage/support report rather than a demonstrated failure of promised behavior or an explicit feature request.

### Evidence
- TypeScript reports that `experimental_onFunctionCall` is not a member of `UseCompletionOptions`.
- The issue does not establish that `useCompletion` is documented or intended to support this option, nor explicitly request that support be added.
- There are no comments clarifying whether this is a product defect, unsupported usage, or a version mismatch.
