### ISSUE TITLE
Flush UseChat ChatHelper error on new handleSubmit

### ISSUE THREAD

**Issue by peterdresslar** [vercel/ai#567]
Using UseChat ChatHelper `error` would be more intuitive if the error was cleared on a new handleSubmit. I believe it is not currently.

For instance, this would be an intuitive use of `error`:

``` typescript
{error ?
        <div className="text-red-500">Error: {error.message}</div> 
        : null}
 ``` 
 
But the div sticks around forever, even if the next submit is successful. Right now, we can use the helper callbacks to wrap handleSubmit with a flag, making this workaround possible:
 
 ``` typescript
 {error && !successFlag ? // Right now, error does not get cleared on a successful submit. So we use a helper flag to know when to show it.
        <div className="text-red-500">Error: {error.message}</div> 
        : null}
 ```       
  ...but I think it would be more intuitive to have new submissions simply nullify our `error`.

**Comment by ctate** [comment]
Hey @peterdresslar - I created a PR as an attempt to fix this: https://github.com/vercel/ai/pull/568

Please let me know if this helps. Thank you!

**Comment by lgrammel** [comment]
## Identify issue type

Identified as **Bug**  
Confidence: **High**

### Rationale
This describes stale, incorrect state in existing `useChat` behavior after a successful retry, rather than a request for a separate new capability.

### Evidence
- The `useChat` helper's `error` state remains set after a later submission succeeds, leaving stale error UI visible indefinitely.
- The reporter expects a new `handleSubmit` to clear the prior error and currently needs a separate success flag as a workaround.
- A contributor opened PR #568 as an attempted fix.
