### ISSUE TITLE
Function calls not parsing correctly

### ISSUE THREAD

**Issue by woodbridge** [vercel/ai#578]
I'm noticing that function calls are seemingly intermittently not parsed correctly into their own messages, and instead concatenated towards the end of a response of a regular assisant message body.  Here's example of a message:

> Once the dragon is inserted and properly scaled, I'll summarize the scene for you, and if there's anything you'd like to adjust, we can proceed from there.
> 
> Let's find that dragon!{"function_call": {"name": "search_asset_library", "arguments": "{\n "queries": ["dragon"]\n}"}}

I'm running the same conversation against the raw openai node api [(based on this example)](https://github.com/openai/openai-node/blob/master/examples/function-call-stream.ts):

```
   const stream = await openai.chat.completions.create({
      model: "gpt-4",
      messages,
      functions: functions,
      stream: true,
    });

    let writeLine = lineRewriter();
    let message = {} as ChatCompletionMessage;
    for await (const chunk of stream) {
      // console.log("chunk", chunk);
      message = messageReducer(message, chunk);
      writeLine(message);
    }
    console.log();
    messages.push(message);
```
And i'm unable to reproduce the behavior -- the function_calls are always parsed correctly into standalone messages.

I'm working on a minimal example and will update the ticket.

**Comment by woodbridge** [comment]
Opened up a PR here: https://github.com/vercel/ai/pull/605

**Comment by lgrammel** [comment]
@woodbridge have you tried the [experiment stream data API](https://sdk.vercel.ai/docs/api-reference/stream-data)? it might resolve your issue

**Comment by lgrammel** [comment]
## Identify issue type

Identified as **Bug**  
Confidence: **High**

### Rationale
The report describes incorrect existing SDK streaming/parsing behavior that produces malformed assistant messages instead of structured function calls.

### Evidence
- Function calls are intermittently emitted as JSON appended to assistant text instead of being parsed into standalone function-call messages.
- The reporter could not reproduce the problem using OpenAI's raw Node streaming API with the same conversation.
- A pull request was opened to address the issue; a maintainer later suggested the experimental Stream Data API as a possible workaround.
