### ISSUE TITLE
experimental_streamdata cannot be reset/cleared from the useChat hook 

### ISSUE THREAD

**Issue by dilanustek** [vercel/ai#586]
We use the experimental_streamdata to generate dynamic user response options to each chat message. So when the user manually clears chat history, we would like to be able to clear the streamed data and reset everything. If there is no way to do that now, could we have a setData function so that we can reset data?

**Comment by matannahmani** [comment]
@dilanustek for a temporary hotfix i think you can manually mutate the useSWR hook

**Comment by lgrammel** [comment]
https://github.com/vercel/ai/pull/3271

**Comment by lgrammel** [comment]
## Identify issue type

Identified as **Feature**  
Confidence: **High**

### Rationale
This requests an API expansion for resetting streamed data rather than identifying behavior that violates an existing documented guarantee.

### Evidence
- The reporter requests a `setData` function to reset `experimental_streamdata` when chat history is cleared.
- A commenter provides a workaround by exposing SWR's `mutateStreamData`, indicating the reset API was not currently available.
- A later comment links to pull request #3271, apparently addressing the requested capability.
