### ISSUE TITLE
Using custom id creation function for messages

### ISSUE THREAD

**Issue by aberezkin** [vercel/ai#591]
Hi! It'd be nice to be able to generate an id for messages (and chat as well) in a way that my backend natively supports. I'm storing the messages in a Postgres database and ids are of type `UUID` which has some performance improvements compared to strings. So what I would imagine is param passed to the `useChat` hook that, if provided, creates an id instead of using `nanoid`.

I can also create a PR implementing something like that.

**Comment by MaxLeiter** [comment]
Fixed by #733. Thanks!

**Comment by Kirchen99** [comment]
I saw this change has been reverted. Is there any reason?

**Comment by lgrammel** [comment]
## Identify issue type

Identified as **Feature**  
Confidence: **High**

### Rationale
This is an API customization enhancement rather than a failure of existing documented behavior.

### Evidence
- The issue requests a new `useChat` parameter for supplying a custom message/chat ID generator instead of the built-in `nanoid`.
- The motivation is compatibility with backend-native PostgreSQL UUID identifiers.
- A maintainer states the request was implemented by PR #733.
