### ISSUE TITLE
`gpt-3.5-turbo-instruct` model is missing

### ISSUE THREAD

**Issue by evanlong0926** [vercel/ai#603]

**Comment by shuding** [comment]
Could you be more specific? You can pass any allowed model to OpenAI's SDK e.g.:

![CleanShot-2023-09-27-duhb8oSA@2x](https://github.com/vercel/ai/assets/3676859/9d7c7548-01c8-4449-8c0f-8622764e5aed)

https://sdk.vercel.ai/docs/guides/providers/openai

**Comment by evanlong0926** [comment]
I want to express the ts type.

**Comment by MaxLeiter** [comment]
gpt-3.5-turbo-instruct is a completion API, not a chat API. You'll need to use `useCompletion`: https://sdk.vercel.ai/docs/api-reference/use-completion

See this guide: https://sdk.vercel.ai/docs/guides/providers/openai#guide-text-completion

**Comment by lgrammel** [comment]
## Identify issue type

Identified as **None**  
Confidence: **High**

### Rationale
This is a usage/support question caused by selecting the wrong OpenAI endpoint, not a missing AI SDK capability or broken documented behavior.

### Evidence
- The reporter passed `gpt-3.5-turbo-instruct` to OpenAI's chat-completions endpoint and received a 404 explaining that it is not a chat model.
- A maintainer clarified that this model uses the completion API and should be used with `useCompletion`, linking the relevant guide.
