### ISSUE TITLE
Support streaming server actions

### ISSUE THREAD

**Issue by codinginflow** [vercel/ai#617]
### Feature Description

Would be nice to have a way to stream AI responses from server actions.

### Use Case

Whenever you use server actions instead of API routes.

**Comment by MaxLeiter** [comment]
This is now supported: https://sdk.vercel.ai/docs/api-reference/streaming-react-response

**Comment by lgrammel** [comment]
## Identify issue type

Identified as **Feature**  
Confidence: **High**

### Rationale
This is a request for new streaming support rather than a report that existing documented behavior was broken.

### Evidence
- The issue requests the ability to stream AI responses from server actions, which was a new capability at the time.
- A maintainer later confirmed that server-action streaming is supported and linked to an example.
