### ISSUE TITLE
Type errors when installing starter in WebStorm

### ISSUE THREAD

**Issue by AnimeAllstar** [vercel/ai#622]
### Description

- run `npx create-next-app --example https://github.com/vercel/ai/tree/main/examples/next-openai next-openai-app`
- open WebStorm 2023.2.2
- open a .tsx file

```
Vue: Type  Element[] | null  is not assignable to type  ReactNode 
Type  Element[]  is not assignable to type  ReactNode 
```

<img width="1512" alt="Screenshot 2023-10-05 at 9 27 21 PM" src="https://github.com/vercel/ai/assets/39626451/514d3c66-03f9-4978-831d-f8130ab3153b">

This is probably a WebStorm bug due to `vue` being a dependency of `swrv` in a Next.js project but I wanted to know if other people are having this issue and if there are any fixes.

**Comment by AnimeAllstar** [comment]
Fixed by disabling the vue language server. The default is automatically

<img width="1094" alt="Screenshot 2023-10-05 at 9 51 27 PM" src="https://github.com/vercel/ai/assets/39626451/f600519b-7753-48c8-8996-f2b5d1c1b66c">

**Comment by lgrammel** [comment]
## Identify issue type

Identified as **None**  
Confidence: **High**

### Rationale
This is a resolved IDE-specific support question rather than a demonstrated defect in the AI SDK or its example.

### Evidence
- The reported type diagnostics occur specifically in WebStorm when its Vue language server processes the Next.js starter.
- The reporter attributes the behavior to WebStorm and asks whether others have encountered it or know a fix.
- The reporter later confirms it was fixed by disabling WebStorm's Vue language server.
