### ISSUE TITLE
"Argument of type 'Stream<Completion>' is not assignable to parameter of type 'Response | AsyncIterableOpenAIStreamReturnTypes'

### ISSUE THREAD

**Issue by Cloudreview** [vercel/ai#637]
### Description

Issue:
Creating a text stream from the response received from the OpenAI API. still errors out.

Whilst this issue was previously closed, it seem to still persist with the following **version**
"openai": "4.12.1"
"ai": "2.2.15",

### Code example

  // Convert the response into a friendly text-stream
  const stream = OpenAIStream(response);
  // Respond with the stream
  return new StreamingTextResponse(stream);
}

**Comment by MaxLeiter** [comment]
Perhaps something changed in `openai@4.12`; `4.11` works with our examples

**Comment by peterdresslar** [comment]
At first glance, `openai@4.12.1` and `ai@2.2.15` seem to work together for chat and completions. I can't reproduce this error.

**Comment by Cloudreview** [comment]
Chat works well. I can reproduce it with completions

**Comment by peterdresslar** [comment]
Ah, apologies @Cloudreview , I notice now that I have a completion typecast as `any` in my working example. I can reproduce it with completions.

**Comment by MaxLeiter** [comment]
Fixed by #639.

Thanks for reporting @Cloudreview, and thanks @peterdresslar for the fix!

**Comment by lgrammel** [comment]
## Identify issue type

Identified as **Bug**  
Confidence: **High**

### Rationale
This is a confirmed type compatibility failure in existing completion-stream behavior, and maintainers implemented a fix.

### Evidence
- Using `OpenAIStream(response)` with completion responses from `openai@4.12.1` and `ai@2.2.15` produces a TypeScript assignability error.
- A maintainer reproduced the failure specifically for completions after removing an `any` typecast.
- The issue was resolved by fix PR #639.
