### ISSUE TITLE
experimental_StreamData does not persist state correctly

### ISSUE THREAD

**Issue by Yoha485** [vercel/ai#647]
### Description

I store objects of structure `{ type: string }` inside experimental_StreamData. And sometimes when I append an object to experimental_StreamData I lose another.

What I expect is:
1) I append `{ type: 'TYPE_1' }` to experimental_StreamData --> on client I have  `[ { type: 'TYPE_1' } ]`
2) On next requestI append `{ type: 'TYPE_2' }` to experimental_StreamData --> on client I have  `[ { type: 'TYPE_1' }, { type: 'TYPE_2 } ]`
3) On next requestI append `{ type: 'TYPE_3' }` to experimental_StreamData --> on client I have  `[ { type: 'TYPE_1' }, { type: 'TYPE_2 }, { type: 'TYPE_3 } ]`

What actually happening:
1) I append `{ type: 'TYPE_1' }` to experimental_StreamData --> on client I have  `[ { type: 'TYPE_1' } ]`
2) On next requestI append `{ type: 'TYPE_2' }` to experimental_StreamData --> on client I have  `[ { type: 'TYPE_1' }, { type: 'TYPE_2 } ]`
3) On next requestI append `{ type: 'TYPE_3' }` to experimental_StreamData --> on client I have  `[ { type: 'TYPE_1' }, { type: 'TYPE_3 } ]`

So on step 3 I lose TYPE_2

**Comment by peterdresslar** [comment]
Hi there, if you check out the discussion at https://github.com/vercel/ai/discussions/665, I hope to address this. I am having pretty good luck with sending data to the front end in sequence, but it can be tricky to access. If that sample code doesn't help, maybe you could post your code example that is not working?

**Comment by lgrammel** [comment]
@Yoha485 I've attempted to reproduce your issue using the next-openai example:

https://github.com/lgrammel/vercel-ai/commit/a0d6fa1634cb5d222dd23a67d5d787cd823aa8e9

However, it works correctly when I try it:

![image](https://github.com/vercel/ai/assets/205036/6d8b0de4-9dec-4137-8c63-0ce50ae5df64)

Most likely I'm missing some context. Could you share an example that reproduces this error?

**Comment by lgrammel** [comment]
Could not reproduce. Please re-open if you are still encountering this issue.

**Comment by lgrammel** [comment]
## Identify issue type

Identified as **Bug**  
Confidence: **Medium**

### Rationale
This is framed as incorrect existing behavior and data loss, so it is a bug report, although the lack of a reproduction lowers confidence.

### Evidence
- Reporter says previously appended StreamData entries disappear after a later request, producing `[TYPE_1, TYPE_3]` instead of retaining `TYPE_2`.
- The maintainer’s attempted reproduction retained all entries correctly and the reporter provided no reproducible code.
- The issue was closed as not reproducible, with an invitation to reopen if it persisted.
