### ISSUE TITLE
has no exported member named 'BytesOutputParser'

### ISSUE THREAD

**Issue by sytpb** [vercel/ai#660]
### Description

got the error , from the code as https://sdk.vercel.ai/docs/guides/providers/langchain

`'"langchain/schema/output_parser"' has no exported member named 'BytesOutputParser'. Did you mean 'BaseOutputParse`

### Code example

import { NextRequest } from 'next/server';
import { Message as VercelChatMessage, StreamingTextResponse } from 'ai';
 
import { ChatOpenAI } from 'langchain/chat_models/openai';
import { BytesOutputParser } from 'langchain/schema/output_parser';
import { PromptTemplate } from 'langchain/prompts';
 
export const runtime = 'edge';
 
/**
 * Basic memory formatter that stringifies and passes
 * message history directly into the model.
 */
const formatMessage = (message: VercelChatMessage) => {
  return `${message.role}: ${message.content}`;
};
 
const TEMPLATE = `You are a pirate named Patchy. All responses must be extremely verbose and in pirate dialect.
 
Current conversation:
{chat_history}
 
User: {input}
AI:`;
 
/*
 * This handler initializes and calls a simple chain with a prompt,
 * chat model, and output parser. See the docs for more information:
 *
 * https://js.langchain.com/docs/guides/expression_language/cookbook#prompttemplate--llm--outputparser
 */
export async function POST(req: NextRequest) {
  const body = await req.json();
  const messages = body.messages ?? [];
  const formattedPreviousMessages = messages.slice(0, -1).map(formatMessage);
  const currentMessageContent = messages[messages.length - 1].content;
 
  const prompt = PromptTemplate.fromTemplate(TEMPLATE);
  /**
   * See a full list of supported models at:
   * https://js.langchain.com/docs/modules/model_io/models/
   */
  const model = new ChatOpenAI({
    temperature: 0.8,
  });
 
  /**
   * Chat models stream message chunks rather than bytes, so this
   * output parser handles serialization and encoding.
   */
  const outputParser = new BytesOutputParser();
 
  /*
   * Can also initialize as:
   *
   * import { RunnableSequence } from "langchain/schema/runnable";
   * const chain = RunnableSequence.from([prompt, model, outputParser]);
   */
  const chain = prompt.pipe(model).pipe(outputParser);
 
  const stream = await chain.stream({
    chat_history: formattedPreviousMessages.join('\n'),
    input: currentMessageContent,
  });
 
  return new StreamingTextResponse(stream);
}

**Comment by peterdresslar** [comment]
@sytpb I wonder what versions of `ai` and `langchain` you are using?  

The example, as it is, works for me, but is slightly dated as documented. It could be updated.

[Here is a working example online](https://vercel-ai-sdk-examples-lbw097img-peterdresslar.vercel.app/): (choose the langchain-example)

https://vercel-ai-sdk-examples-lbw097img-peterdresslar.vercel.app/

[And here is the code ](https://github.com/peterdresslar/vercel-ai-sdk-examples) backing that. (in the branch, `langchain-example`)

**Comment by sytpb** [comment]
"ai": "^2.1.6",
"langchain": "^0.0.83",

**Comment by peterdresslar** [comment]
FWIW, I would try updating to the latest of both, as these are both a bit out of date.  `pnpm upgrade` should work. I suspect that might fix your import.

However, either way, I don't think this is necessarily an issue with `ai` since the code seems to work from the example in the docs. You might follow up in the langchain-js community if it still isn't working.

**Comment by lgrammel** [comment]
## Identify issue type

Identified as **None**  
Confidence: **High**

### Rationale
This is primarily a dependency-version support issue rather than a confirmed AI SDK bug or a concrete documentation change request.

### Evidence
- The missing export comes from `langchain/schema/output_parser`, not directly from the AI SDK.
- The reporter was using outdated versions: `ai` 2.1.6 and `langchain` 0.0.83.
- A commenter confirmed the documented example worked and advised upgrading both packages or contacting the LangChain community.
