### ISSUE TITLE
Incorrect link and command in examples/next-anthropic

### ISSUE THREAD

**Issue by ocss884** [vercel/ai#674]
### Description

In the current anthropic example, the deploy link and commands are directed to the replicate example, not anthropic.

### Code example

In the [README.md](https://github.com/vercel/ai/blob/f238beb1fd369ac2d674be7728b972946ba4d3ec/examples/next-anthropic/README.md)

### Additional context

I will open a PR to fix it.

**Comment by lgrammel** [comment]
## Identify issue type

Identified as **Documentation**  
Confidence: **High**

### Rationale
This is an error in written setup and deployment instructions, not a failure of SDK runtime behavior or the runnable example implementation.

### Evidence
- The `examples/next-anthropic/README.md` deploy link and commands incorrectly point to the Replicate example instead of Anthropic.
- The requested fix is specifically to README content within an example project.
