### ISSUE TITLE
Langchain with Google PaLM ai doesnt work with streaming

### ISSUE THREAD

**Issue by rin-yato** [vercel/ai#682]
### Description

I followed the langchain stream example from the documentation. My code look sth like this

### Code Example
```ts
const palm = new ChatGooglePaLM({
    apiKey: "...",
    temperature: 1,
    verbose: true,
  });

const outputParser = new BytesOutputParser();

const chain = promptTemplate.pipe(palm).pipe(outputParser);

const stream = await chain.stream({
  ai_prompt: prompt || "What is the answer to the question?",
  no_answer: noAnswer || "I don't know",
  word_count: "100",
  chat_history,
  documents: "",
  question,
});

return new StreamingTextResponse(stream, {
  headers: {
    "Access-Control-Allow-Origin": "*",
    "Access-Control-Allow-Methods": "POST, OPTIONS",
  },
});
```

### Result
It response but not streaming, it waits and response with everything.

### Expect
It to stream the result

**Comment by lgrammel** [comment]
## Identify issue type

Identified as **Bug**  
Confidence: **High**

### Rationale
This reports a concrete failure of existing streaming behavior: output is returned only after generation completes rather than being streamed.

### Evidence
- The LangChain chain using ChatGooglePaLM and BytesOutputParser returns successfully but buffers the entire response instead of streaming it.
- The reporter followed the documented LangChain streaming pattern and expected StreamingTextResponse to deliver incremental output.
