### ISSUE TITLE
When using GPT4 on mobile device, messages end abruptly and `onFinish` is invoked, but works properly when using GPT3.5 Turbo 

### ISSUE THREAD

**Issue by dosstx** [vercel/ai#705]
### Description

I am building a story generation app that generates about 10-15 short paragraphs in a single story as a one-time process. **On a mobile device**, when the assistant creates the story and the model is `gpt-4`, the story terminates around the halfway point in the generation process and the `onFinish` callback of `useChat` is fired. However, when using the `gpt-3.5-turbo` model, the entire story is correctly finished. 

### Code example

```
const { messages, isLoading, append, stop, setMessages, reload } =
	useChat({
		api: "/api/generate-story",
		headers: { "Content-Type": "application/json" },
		onFinish: async (message) => {
			alert('finished') //<--- fires on GPT-4 and halfway through story generation.
		}
	})
```

 Additional context

1. This issue **does not happen** when using the OpenAI Playground with the same OpenAI settings applied (temperature, max tokens, etc)
2. This only happens on mobile devices (ie, I only tested on iOS iPhone (safari, chrome, edge) using iPhone 14
3. The problem seems to happen more on Netlify Edge vs Vercel Edge.

**Comment by lgrammel** [comment]
I have tried reproducing this with the next/openai example ( https://github.com/vercel/ai/tree/main/examples/next-openai ) and GPT-4, but it worked without issues.

I suspect it is caused by some sort of timeout, since GPT-4 is slower than GPT-3.5. In which setup/environment do you encounter this issue?

**Comment by dosstx** [comment]
> I suspect it is caused by some sort of timeout, since GPT-4 is slower than GPT-3.5. In which setup/environment do you encounter this issue?

Something like that seems to be what it is. However, isn't the `useChat` utility slightly different between React and Vue?

Here is my setup and code that returns the response:

------------------------------
- Operating System: Windows_NT
- Node Version:     v18.17.1
- Nuxt Version:     3.8.0
- CLI Version:      3.9.1
- Nitro Version:    2.7.0
- Package Manager:  npm@10.2.2
- Builder:          -
- User Config:      nitro, experimental, typescript, devtools, modules, colorMode, runtimeConfig
- Runtime Modules:  @nuxt/ui@2.10.0, @vueuse/nuxt@10.5.0
- Build Modules:    -
------------------------------

`/api/generate-story.ts`:

```
    try {
      // Create a chat completion request with the system prompts and messages
      const request = {
        // model: 'gpt-3.5-turbo',
        model: 'gpt-4',
        stream: true,
        messages: [
          {
            role: 'system',
            content:
              "...my system message here..."
          },
          {
            role: messages[0].role,
            content: messages[0].content
          }
        ],
        temperature: 1,
        max_tokens: 1663,
        top_p: 0.82,
        frequency_penalty: 0,
        presence_penalty: 0
      }
      // Send the request to OpenAI and get a response stream
      const response = await openai.chat.completions.create(request)
      // Return an OpenAIStream object that wraps the response stream
      return OpenAIStream(response)
    }

**Comment by dosstx** [comment]
This seems to only happen on mobile devices. That was a key point I forgot to mention above.

**Comment by dosstx** [comment]
Update: It seems to be a little better when I deploy to Vercel Edge vs Netlify Edge. I did see the problem happen once on Vercel, but 90% of the time it is fine. I think that's good enough for now.

**Comment by MaxLeiter** [comment]
Closing as this doesn't seem like an `ai` specific issue -- the model chosen shouldn't affect us. Hope it works well, @dosstx!

**Comment by dosstx** [comment]
It has been working great. Now it's  non-issue with new gpt 4 turbo release.

**Comment by lgrammel** [comment]
## Identify issue type

Identified as **None**  
Confidence: **High**

### Rationale
The reported truncation was not established as an AI SDK defect and was ultimately resolved by model/deployment changes, so it is best classified as a support/environment issue.

### Evidence
- Maintainer could not reproduce the truncation with the Next/OpenAI example and suspected an environment timeout rather than AI SDK behavior.
- The problem varied between Netlify Edge and Vercel Edge, indicating deployment-specific behavior.
- The reporter later confirmed it was a “non-issue” after the GPT-4 Turbo release.
