### ISSUE TITLE
Amazon Bedrock as a provider

### ISSUE THREAD

**Issue by timcosta** [vercel/ai#708]
### Feature Description

[Amazon Bedrock](https://aws.amazon.com/bedrock/) is a new generally available AWS service that wraps models from various providers such as Anthropic, AI21, Cohere, and more. It would be great to include an example of how to use Amazon Bedrock as a provider on the SDK docs page.

### Use Case

Bedrock supports the synchronous [InvokeModelCommand](https://docs.aws.amazon.com/AWSJavaScriptSDK/v3/latest/client/bedrock-runtime/command/InvokeModelCommand/) as well as the streaming [InvokeModelWithResponseStreamCommand](https://docs.aws.amazon.com/AWSJavaScriptSDK/v3/latest/client/bedrock-runtime/command/InvokeModelWithResponseStreamCommand/) for all of these providers, which gives end users a consistent API to make calls against as well as a single pane of glass for their billing and model access. The AWS terms of service and EULA are also more appealing to certain industries than invoking these models directly through their provider due to security concerns.

**Comment by ApoorvaMadhusudan** [comment]
Yes! Another question, can we use the say the API key we get from AWS Bedrock for Anthropic's Claude in the Vercel AI SDK configuration? Does that directly work?

https://sdk.vercel.ai/docs/guides/providers/anthropic

**Comment by NickMandylas** [comment]
Hey – I've started working on the integration will raise a PR on it, this week.

**Comment by MaxLeiter** [comment]
We'd love to support Bedrock but haven't prioritized a provider. 

Thanks @NickMandylas, I look forward to your PR!

**Comment by lgrammel** [comment]
https://github.com/vercel/ai/pull/750

**Comment by MaxLeiter** [comment]
#750 has been merged and `2.2.25` is being released. Thanks @lgrammel!

**Comment by lgrammel** [comment]
## Identify issue type

Identified as **Feature**  
Confidence: **High**

### Rationale
Although the description mentions adding a docs example, the comments clarify that a new Bedrock provider integration was required and subsequently implemented. This is a new capability rather than a documentation-only change.

### Evidence
- The issue requests Amazon Bedrock support as an AI SDK provider.
- A maintainer stated that Bedrock provider support had not yet been prioritized.
- PR #750 implemented the integration and was released in version 2.2.25.
