### ISSUE TITLE
Parallel Function Calling

### ISSUE THREAD

**Issue by twobit** [vercel/ai#729]
### Feature Description

Parallel function calling was recently added using the `tools` field:
https://platform.openai.com/docs/guides/function-calling/parallel-function-calling

**Comment by nabilfatih** [comment]
would love to see this in ai sdk

**Comment by Archimagus** [comment]
I have included this in my work on using `tool_calls` in this branch, still quite WIP.
https://github.com/Archimagus/ai/tree/feature/ToolCalling

**Comment by nabilfatih** [comment]
you can actually call multiple function by this recursive https://sdk.vercel.ai/docs/guides/providers/openai-functions#recursive-function-calls but the problem is, cant in parallel :( ... parallel only available via new tools API (not function call)

**Comment by lgrammel** [comment]
## Identify issue type

Identified as **Feature**  
Confidence: **High**

### Rationale
This requests a new SDK capability to support parallel tool/function calls, rather than reporting a failure of existing promised behavior.

### Evidence
- The title and description request support for OpenAI's newly added parallel function calling through the `tools` field.
- A comment confirms recursive multiple function calls were possible, but parallel calls required the new tools API.
- No existing documented SDK behavior is reported as broken.
