### ISSUE TITLE
Pathname '/https,http://localhost:63450/api/chat' should have matched '/api/chat' with Next.js 14.0.2

### ISSUE THREAD

**Issue by AlexIsMaking** [vercel/ai#740]
### Description

> Pathname '/https,http://localhost:63450/api/chat' should have matched '/api/chat'

error when sending requests to the chat route with Next.js 14.0.2. This can be avoided by downgrading to Next.js 14.0.1.

Steps to reproduce -

1. Clone the [Vercel AI SDK, Next.js, and OpenAI Chat Example](https://github.com/vercel/ai/tree/main/examples/next-openai#vercel-ai-sdk-nextjs-and-openai-chat-example)
2. Configure the environment variable, install packages and run with `vercel deploy`, then submit a prompt - the app will work as expected
3. Update to latest stable release of Next.js with `npm i next@latest`
4. Run with `vercel deploy` - an error will be logged

>  ⨯ node_modules/next/dist/esm/server/web/edge-route-module-wrapper.js (58:18) @ EdgeRouteModuleWrapper.handler
>  ⨯ Invariant: no match found for request. Pathname '/https,http://localhost:63450/api/chat' should have matched '/api/chat'

**Comment by tgonzales** [comment]
@AlexIsMaking Are you using the useChat hook?

**Comment by AlexIsMaking** [comment]
@tgonzales yes I am, I haven't changed anything from the example project.

**Comment by tgonzales** [comment]
@AlexIsMaking  I believe it is related to this issue https://github.com/vercel/next.js/issues/48295
Awaiting

**Comment by AlexIsMaking** [comment]
@tgonzales ah, thanks for the heads up. I'll share some info on that issue too

**Comment by lgrammel** [comment]
## Identify issue type

Identified as **Bug**  
Confidence: **High**

### Rationale
This reports a reproducible regression in an existing AI SDK example and request flow, even though comments suggest the underlying cause may be in Next.js.

### Evidence
- The unchanged Next.js/OpenAI chat example fails when submitting prompts after upgrading from Next.js 14.0.1 to 14.0.2.
- The request produces an invariant error because pathname '/https,http://localhost:63450/api/chat' does not match '/api/chat'.
- The reporter confirms the example uses the AI SDK's `useChat` hook and that downgrading Next.js restores working behavior.
