### ISSUE TITLE
Please add GPT 4 Turbo to Vercel AI SDK!

### ISSUE THREAD

**Issue by ApoorvaMadhusudan** [vercel/ai#742]
### Feature Description

https://sdk.vercel.ai/docs/api-reference/openai-stream 
`This works with a variety of OpenAI models, including: gpt-4, gpt-4-0314, gpt-4-32k, gpt-4-32k-0314, gpt-3.5-turbo, gpt-3.5-turbo-0301`

Can you add GPT 4 Turbo? How long will it take before its added and tested, need it asap.

https://help.openai.com/en/articles/8555510-gpt-4-turbo

**Comment by verrannt** [comment]
GPT-4 Turbo has the model name `gpt-4-1106-preview`. Just plug that into `openai.chat.completions.create`. Since it functions like all other models, it is already supported.

Note however that vision input using `gpt-4-vision-preview` is not supported yet, see [this issue](https://github.com/vercel/ai/issues/712).

**Comment by lgrammel** [comment]
## Identify issue type

Identified as **None**  
Confidence: **High**

### Rationale
The requested capability already exists, so this is primarily a usage/support question rather than a new feature or a concrete SDK failure.

### Evidence
- The issue requests GPT-4 Turbo model support.
- A comment clarifies that GPT-4 Turbo already works by using the model name `gpt-4-1106-preview` with the existing OpenAI chat completions integration.
- Only the separate vision model is unsupported and tracked in another issue.
