### ISSUE TITLE
useAssistant: Add function to start a new thread/reset messages

### ISSUE THREAD

**Issue by codinginflow** [vercel/ai#767]
### Feature Description

There should be a way to clear the message history and start a brand new chat with an existing assistant. Since we can't clear a thread via the OpenAI Assistants API, I guess the correct way would be to start a new thread. To reset the `threadId` back to zero, in other words.

### Use Case

Building a chat UI with a "clear chat" button.

**Comment by lgrammel** [comment]
## Identify issue type

Identified as **Feature**  
Confidence: **High**

### Rationale
This is a request for a new API capability and ergonomic enhancement to reset an assistant conversation, rather than a failure of existing behavior.

### Evidence
- The issue requests a new `useAssistant` function to clear message history and start a new OpenAI Assistants thread.
- The stated use case is adding a “clear chat” button by resetting or replacing the current `threadId`.
- No existing documented behavior is described as broken.
