### ISSUE TITLE
Stream AssistantResponse just like chat responses

### ISSUE THREAD

**Issue by mfts** [vercel/ai#787]
### Feature Description

openai.chat.completions responses are converted to `OpenAIStream` and then returned to the client as a `StreamingTextResponse`. 

This should be doable with AssistantResponses too. It seems like they are already converted to a stream but not streamed to the client. Instead the `useAssistant` waits for the full message to display it. 

Would love a way to stream it.

**Comment by MaxLeiter** [comment]
OpenAI doesn’t officially support streaming assistant responses yet. We will support it when we can. 

https://platform.openai.com/docs/assistants/how-it-works/limitations

**Comment by lgrammel** [comment]
## Identify issue type

Identified as **Feature**  
Confidence: **High**

### Rationale
This requests a new streaming capability rather than reporting a failure of behavior that was already supported or promised.

### Evidence
- The reporter requests streaming support for Assistant responses so `useAssistant` does not wait for the full message.
- A maintainer states that OpenAI did not officially support streaming Assistant responses and that the SDK would support it when possible.
