### ISSUE TITLE
Streaming Run Step changes from the Assistants API

### ISSUE THREAD

**Issue by holdenmatt** [vercel/ai#796]
### Feature Description

I'm integrating the new `useAssistant` hook in a React project (nice so far!).

To provide the best user experience, it would be nice to update my UI when intermediate Run Steps change (e.g. the model is using a tool).

Wondering if I should implement this myself (e.g. polling the OpenAI API from the client), or if this will be in scope for the `ai` SDK?

I imagine steps could be added as a primitive to the hook. Or if there was a more general mechanism like `experimental_StreamData`, it could be used to stream down status/step changes?

### Use Case

See the OpenAI keynote demo (at [35:45](https://www.youtube.com/live/U9mJuUkhUzk?si=D9wc7jnoTNRkHN2z&t=2145)) for an example where displaying run steps is beneficial (vs waiting until the run is complete).

### Additional context

[Runs and Run Steps](https://platform.openai.com/docs/assistants/how-it-works/runs-and-run-steps)
[API reference](https://platform.openai.com/docs/api-reference/runs/listRunSteps)

**Comment by lgrammel** [comment]
I'm exploring data messages for this use case: https://github.com/vercel/ai/pull/798

**Comment by holdenmatt** [comment]
Love it. Great to see how fast y'all are iterating on this!

**Comment by mfts** [comment]
@lgrammel will this enable streaming the response from the assistant? 
Or is streaming already possible?

**Comment by mfts** [comment]
@lgrammel thanks for the clarification. I just read up on it again.

**Comment by holdenmatt** [comment]
Closing this, since I think `sendDataMessage` should be usable for this use case. Thanks!

**Comment by phact** [comment]
We just released streaming capability for [astra assistants](https://www.datastax.com/blog/introducing-the-astra-assistants-api) https://github.com/phact/streaming-assistants would folks be interest in a typescript version?

**Comment by lgrammel** [comment]
## Identify issue type

Identified as **Feature**  
Confidence: **High**

### Rationale
This requests an SDK capability or API mechanism for surfacing intermediate run-step status, rather than reporting broken existing behavior.

### Evidence
- The reporter requests a way for `useAssistant` to expose or stream intermediate Assistant Run Step changes.
- A maintainer explored data messages for the use case in PR #798.
- The issue was closed after `sendDataMessage` was considered sufficient for implementing the requested behavior.
