### ISSUE TITLE
OpenAIStream onCompletion does not provide correct completion when returninig a string in experimental_onFunctionCall

### ISSUE THREAD

**Issue by Yoha485** [vercel/ai#802]
### Description

When I return `Promise<string>` type(instead of `Promise<AsyncIterableOpenAIStreamReturnTypes>` ) variable inside my `experimental_onFunctionCall` function the `completion` in my `onFinal` and `onCompletion` callbacks is wrong. Instead of being a string that I returned in experimental_onFunctionCall, I get `{"function_call": {"name": "...", "arguments": "..."}}`

### Code example

```typescript
const stream = OpenAIStream(response, {
      experimental_onFunctionCall: async ({ name, arguments: args }, createFunctionCallMessages) => {
        return 'Static String';
      },
      onCompletion(completion) {
        console.log("completion", completion); // This won't log 'Static String'
      },
      async onFinal(completion) {
        streamMetadata.close();
      },
      experimental_streamData: true,
    });

```

**Comment by Yoha485** [comment]
#804 
This pull request should resolve the issue

**Comment by lgrammel** [comment]
Please check out our new tool calling with AI SDK Core and useChat: https://sdk.vercel.ai/docs/ai-sdk-ui/chatbot-with-tool-calling#example-server-side-tool-execution-with-roundtrips

**Comment by lgrammel** [comment]
## Identify issue type

Identified as **Bug**  
Confidence: **High**

### Rationale
This describes incorrect callback output in existing `OpenAIStream` behavior, with a concrete example and expected result.

### Evidence
- Returning a string from `experimental_onFunctionCall` causes `onCompletion` and `onFinal` to receive the original function-call JSON rather than the returned string.
- The reporter provides a concrete reproduction using `OpenAIStream`.
- A linked pull request was stated to resolve the issue.
