### ISSUE TITLE
experimental_StreamingReactResponse only streaming after completion

### ISSUE THREAD

**Issue by 0x-Legend** [vercel/ai#817]
### Description

Instead of the server action streaming the response as it gets chunks from OpenAI, it streams it after completion. Video attached to demonstrate.

Code is an almost exact copy from the docs:
https://sdk.vercel.ai/docs/api-reference/streaming-react-response

Only difference is this part in action.tsx:
```typescript
// Respond with the stream
  return new experimental_StreamingReactResponse(stream, {
    ui({ content }) {
      return <div>{content}</div>
    }
  })
  ```
  
  Also, can't seem to get experimental_StreamData working in server actions either. Will docs be added to show an example?
  
  Will server actions support SSE in general, is that on the roadmap. Adding SSE support through useFormState would be pretty cool.

**Comment by 0x-Legend** [comment]
Video: https://drive.google.com/file/d/1rX4wFYdffGSfbk7-pNeU2bscUzJSNDnP/view?usp=sharing

**Comment by lgrammel** [comment]
## Identify issue type

Identified as **None**  
Confidence: **Medium**

### Rationale
The alleged broken behavior was withdrawn as apparently intentional, while the remaining requests are exploratory support and roadmap questions rather than a definite documentation change or concrete feature proposal.

### Evidence
- The reporter initially says `experimental_StreamingReactResponse` emits output only after completion rather than chunk-by-chunk.
- The reporter later retracts the failure claim with “nvm, looks like that how it's intended to work?”
- The remaining content consists of questions about Server Action examples and possible future SSE support.
