### ISSUE TITLE
Error: (0 , ai_react__WEBPACK_IMPORTED_MODULE_1__.useCompletion) is not a function

### ISSUE THREAD

**Issue by lusentis** [vercel/ai#830]
### Description

Hi there,
I'm having issues importing the `useChat`/`useCompletion` hooks from `ai/react`. It seems to be working when using `--turbo` but not with Webpack (unfortunately my prod app is not ready for Turbopack yet).

Is there any way to make the import work when using webpack?

### Code example

I created this codesandbox, using the standard Next starter kit. I just removed `--turbo` from the "dev" script in `package.json`. After starting the app and visiting `/`, you'll see a runtime error - as in the screenshot below.

https://codesandbox.io/p/devbox/quizzical-colden-7hwnpp?file=%2Fapp%2Fpage.tsx%3A9%2C2

<img width="765" alt="Screenshot 2023-12-06 at 18 57 40" src="https://github.com/vercel/ai/assets/950086/cacdf5e9-afd7-4522-91a7-2fbe13f57df7">

**Comment by ijjk** [comment]
Hi, it looks like you are missing a `'use client'` directive at the top of your `page.tsx` file which is causing it to be treated a server component which imports a different module that doesn't contain the `useCompletion` function. 

This behaving differently with `--turbo` is not expected and has been reported to the team.

**Comment by ForsakenHarmony** [comment]
Might be a good idea to add the export to the server bundle but make it throw when called, this error is kinda cryptic

**Comment by lgrammel** [comment]
## Identify issue type

Identified as **None**  
Confidence: **High**

### Rationale
This is primarily a support question caused by incorrect client-component setup, not a demonstrated AI SDK failure. The cryptic-error improvement is only a follow-up suggestion.

### Evidence
- The page uses React hooks without the required `'use client'` directive, so Next.js treats it as a server component and resolves a bundle without `useCompletion`.
- The maintainer identifies adding `'use client'` as the solution; the differing Turbopack behavior was separately reported to the relevant team.
- A commenter suggests a more descriptive server-bundle error, but this is an optional enhancement rather than the primary report.
