### ISSUE TITLE
Add updater functionality for react setMessage

### ISSUE THREAD

**Issue by sshkeda** [vercel/ai#831]
### Feature Description

Add updater functionality for react setMessage to make functions like this possible:

```ts
function addMessage(message: Message) {
  setMessages((messages) => [...messages, message]);
}
  ```

### Use Case

I am building an extension app to help developers with web accessibility conformance. It is useful to add sequential messages programmatically; however, because there is no updater function, it is hard to sync the message values after each re-render.

See example of me using this feature here  https://github.com/sshkeda/waccesible.ai/blob/054c4636840f765e681b0883428b6d57d116c212/extension/src/App.tsx#L29-L84

**Comment by sshkeda** [comment]
PR created https://github.com/vercel/ai/pull/832

**Comment by Gr33nLight** [comment]
Any updates on this?

**Comment by kachar** [comment]
Bump on this

**Comment by lgrammel** [comment]
https://github.com/vercel/ai/pull/2347

**Comment by lgrammel** [comment]
## Identify issue type

Identified as **Feature**  
Confidence: **High**

### Rationale
This requests a new API capability for `setMessages`, rather than reporting broken or incorrect existing behavior.

### Evidence
- The issue explicitly requests updater-function support for React's `setMessages`, enabling calls such as `setMessages(messages => [...messages, message])`.
- The motivation is improved state synchronization and ergonomics for adding sequential messages programmatically.
- The comments reference implementation pull requests but do not describe an existing documented behavior failing.
