### ISSUE TITLE
Hugginface example not work

### ISSUE THREAD

**Issue by bien-phillip** [vercel/ai#845]
### Description

I just create app from  `pnpm create next-app --example https://github.com/vercel/ai/tree/main/examples/next-huggingface next-huggingface-app`

A few days ago, it works fine but it didn't work from yesterday. I try to change several models though it didn't work. I have huggingface PRO Subscription also. 

Please anyone test it.

**Comment by lgrammel** [comment]
@bien-phillip I just tested it (as follows) and it works for me. What error are you seeing?

1. `pnpm create next-app --example https://github.com/vercel/ai/tree/main/examples/next-huggingface next-huggingface-app`
2. `cd next-huggingface-app`
3. Add API key to `.env.local`
4. `pnpm dev`
5. go to http://localhost:3000/

**Comment by bien-phillip** [comment]
Right. It's my fault. I used Inference API from `meta-llama/Llama-2-7b-chat-hf`. The api just didn't work. 

I'm sorry for confused.

**Comment by lgrammel** [comment]
## Identify issue type

Identified as **None**  
Confidence: **High**

### Rationale
The reported example is not broken; this was a resolved user/provider-specific support issue rather than an SDK bug or requested examples change.

### Evidence
- The reporter later confirmed the failure was caused by the selected Hugging Face model's Inference API, not the SDK example.
- A maintainer reproduced the setup successfully, and the reporter acknowledged, "It's my fault."
