### ISSUE TITLE
Obfuscate response in post request to chat endpoint

### ISSUE THREAD

**Issue by avianion** [vercel/ai#858]
### Feature Description

Of course we're streaming a lot of data, but it can be seen in the browser. Even though it gets sent, we dont want to show the raw data.

So how can we obfuscate what is seen in the "Resposne" tab of the browser? Services like perplexity.ai successfully encrypt the stream contents that are shown. How do to this?

**Comment by flexchar** [comment]
No matter what you encrypt sent in the browser, you only protect it from the potentially successful Man in the Middle attacks in case that happened on a TLS encrypted network. Obfuscating client side will only add complexity and maintenance burden but won't prevent anyone from finding out what is being sent. 

That being said, just pick any encryption format that you can decrypt server side and go for it. You can already provide a custom `body` payload and it can be anything. Assuming you're talking about extra stuff other than the user's input message that are typed by the very user.

**Comment by lgrammel** [comment]
## Identify issue type

Identified as **None**  
Confidence: **High**

### Rationale
This is primarily a usage/security question rather than a concrete bug, documentation change, example request, or clearly specified SDK feature.

### Evidence
- The description asks how to hide or encrypt streamed response data visible in browser developer tools, without identifying broken SDK behavior or requesting a specific API change.
- The comment explains that client-side obfuscation cannot prevent users from inspecting transmitted data and points to existing custom body support.
