### ISSUE TITLE
Export `setInput` for Assistant Hook

### ISSUE THREAD

**Issue by johannbuscail** [vercel/ai#867]
### Feature Description

The useAssistant hook is not flexible enough. Being able to update messages and submitting only when a form is being submitted doesn't fit most use cases.

Please export `setMessages` and `setInput`.
https://github.com/vercel/ai/blob/37969fb4b4f7ac0d6d5fb4939a7d57a7f481fa07/packages/core/react/use-assistant.ts#L93
https://github.com/vercel/ai/blob/37969fb4b4f7ac0d6d5fb4939a7d57a7f481fa07/packages/core/react/use-assistant.ts#L94

**Comment by tchanxx** [comment]
This was solved in https://github.com/vercel/ai/pull/886

**Comment by lgrammel** [comment]
## Identify issue type

Identified as **Feature**  
Confidence: **High**

### Rationale
This asks for an API expansion and ergonomics improvement rather than reporting broken or contradictory existing behavior.

### Evidence
- The issue requests exposing `setMessages` and `setInput` from `useAssistant` to support more flexible message and submission flows.
- A commenter states that the request was implemented in pull request #886.
