### ISSUE TITLE
Passing chat ID with Server Action isn't working

### ISSUE THREAD

**Issue by mohamedcherifmo** [vercel/ai#887]
### Description

1. Create a useChat with the api as a server action (for experimental_StreamingReactResponse), 
2. pass an id as part of the useChat.
3. Id is not passed as a parameter to the handler

### Code example

`const { messages, input, handleInputChange, handleSubmit, isLoading, reload, setInput, stop } = useChat({
    id:"1",
    api: handler,
  });`

`
export async function handler(req:any) {
  console.log("Request", req)
}
`

The console.log output is:
Request { messages: [ { role: 'user', content: 'Hello' } ] }
(not including the id)

### Additional context

Would be great to also be able to include body, since users may need to add additional parameters

**Comment by wststone** [comment]
You can pass true to the `sendExtraMessageFields` option in useChat

**Comment by wststone** [comment]
You can pass id to the `body` option in useChat

**Comment by mohamedcherifmo** [comment]
> You can pass id to the `body` option in useChat

This works for routes, but not for server actions

**Comment by jancbeck** [comment]
https://github.com/vercel/ai-chatbot/pull/192/files#r1415764592

**Comment by mohamedcherifmo** [comment]
Perfect, this worked like a charm :)

**Comment by lgrammel** [comment]
## Identify issue type

Identified as **None**  
Confidence: **High**

### Rationale
This was resolved as a usage/support issue rather than a confirmed SDK defect or request requiring a product change.

### Evidence
- The reporter expected useChat's `id` or `body` options to be passed as arguments to a server action.
- A linked implementation demonstrated a working way to pass the value, and the reporter confirmed it “worked like a charm.”
- The comments do not establish that the documented server-action behavior was broken.
