### ISSUE TITLE
Requesting with useCompletion, initially. (or via script)

### ISSUE THREAD

**Issue by softmarshmallow** [vercel/ai#926]
### Feature Description

What If I want to trigger the completion stream when page loads?
My case is for non-user interactive use, but the prompt will be generated via the data that is ready on previous steps.
Thought, the current design forces use to use a form, with submit event.

**Comment by MaxLeiter** [comment]
You can use something like the `Tokens` RSC to stream in the response on the server when the page is loaded

https://sdk.vercel.ai/docs/api-reference/tokens

**Comment by lgrammel** [comment]
## Identify issue type

Identified as **None**  
Confidence: **High**

### Rationale
This is primarily a usage question answered with an existing API, not a confirmed product defect or a clear request for a new capability.

### Evidence
- The reporter asks how to trigger a completion stream automatically when a page loads rather than through a form submission.
- A maintainer points to the existing `Tokens` RSC API as a way to stream a response from the server on page load.
