### ISSUE TITLE
Unicode character question submit fired twice

### ISSUE THREAD

**Issue by bexoss** [vercel/ai#937]
### Description

![errorgif](https://github.com/vercel/ai/assets/12633102/d1f4b081-b9b3-4ced-a68c-6c6495459dc7)

I'm using `vercel ai sdk` to communicating with my own server and client. If I type the question ends without question mark, the client send messages twice like attached gif. If I type "추천해줘", The normal one "추천해줘" message and the weird one, last chracater ("줘") also make a message.

```javascript
 { role: 'user', content: '추천해줘' }
 { role: 'user', content: '줘' }
```

Is this a bug?

### Client ###
```javascript

  const { messages, input, setInput, handleInputChange, handleSubmit, isLoading, stop } = useChat({
    api: 'http://localhost:8080/test',
  })

 ...

   <TextField
              placeholder="Say something..."
              value={input}
              onChange={handleInputChange}
              onKeyDown={(e) => {
                if (e.key === 'Enter') {
                  handleSubmit(e)
                }
              }}
   />

```

**Comment by bexoss** [comment]
It turns out wrong usage of `handleSubmit`. I should use in `form` and remove enterKey event

**Comment by lgrammel** [comment]
## Identify issue type

Identified as **None**  
Confidence: **High**

### Rationale
The reported behavior was resolved as a usage/support issue rather than a defect in the AI SDK, and no documentation, example, or product change was requested.

### Evidence
- The reporter observed duplicate submission when pressing Enter after Korean text while calling `handleSubmit` from the input's `onKeyDown`.
- The reporter later confirmed this was incorrect usage and that `handleSubmit` should be used on a form with the Enter-key handler removed.
