### ISSUE TITLE
OpenAI, experimental_onToolCall - tool call messages are not streaming in realtime

### ISSUE THREAD

**Issue by edouard-blocktool** [vercel/ai#949]
### Description

1. Clone the main branch from my fork here: https://github.com/edouard-blocktool/ai
2. cd examples/next-openai
3. npm install && npm run dev
4. Visit http://localhost:3000/tool-calling
5. Type anything in the input, press enter
6. Look at the logs. The onToken messages are not properly streaming. They get all dumped at once, at the end of the streaming.

What's interesting is that it seems to happen only for user questions that require parallel tool_calls (i.e. 2 or more). If there's only one tool_call, streaming works. You can see that by replacing in chat-with-tools/route.ts replace `WITH_THIS_QUESTION_STREAMING_OF_TOOL_CALL_DOES_NOT_WORK` with `WITH_THIS_QUESTION_STREAMING_OF_TOOL_CALL_WORKS`

### Code example

See above

### Additional context

Our app uses gpt-4 for the tool_calls. Without proper streaming, it's unusable and we're stuck with function_calls (for which streaming works)

**Comment by edouard-blocktool** [comment]
Never mind. It's an OpenAI API bug. I actually reproduce with curl. Notified the OpenAI dev relationship team.

**Comment by lgrammel** [comment]
## Identify issue type

Identified as **None**  
Confidence: **High**

### Rationale
The follow-up establishes that the failure is upstream in OpenAI's API rather than in the AI SDK, so this is not an actionable SDK bug or requested repository change.

### Evidence
- The reporter observed tool-call tokens arriving all at once for parallel OpenAI tool calls.
- The reporter later reproduced the behavior directly with curl and stated that it is an OpenAI API bug.
