### ISSUE TITLE
message annotations are repeated

### ISSUE THREAD

**Issue by mohamedcherifmo** [vercel/ai#952]
### Description

I'm combining appendMessageAnnotation with function calling where I'm storing the result of the function call into the message annotations as follow:
`
 data.appendMessageAnnotation({
    messageID: messageID,
    result: top_stories.map((story: any) => ({
      id: story.id,
      title: story.title,
      description: story.subtitle || story.description,
      image_url: story.image_url || story.image,
      category: story.type,
      url: story.url,
    }))
  })
`

When i console.log the message.annotations from the client side, the annotations array has 294 items. It should only have one

**Comment by mohamedcherifmo** [comment]
I figured out that when adding it to the onFinal it works as intended however when added as a result of a function call, it repeats the annotations with every response. I tried onStart (to have it stream at the start instead of at the end, but still repeated)

**Comment by lgrammel** [comment]
## Identify issue type

Identified as **Bug**  
Confidence: **High**

### Rationale
This describes incorrect repetition of message annotations in an existing API workflow, and the subsequent fix confirms it was a product defect.

### Evidence
- Calling `appendMessageAnnotation` as the result of a function call produces 294 repeated annotation items instead of one.
- The reporter clarified that annotations repeat with every streamed response when appended during a function call, while `onFinal` behaves correctly.
- A maintainer proposed a fix and later stated that the issue was resolved in the latest version.
