### ISSUE TITLE
Limit number of words streaming at a time - useChat

### ISSUE THREAD

**Issue by veerbal1** [vercel/ai#953]
### Feature Description

Core OpenAI streaming response stream one word at a time e.g

Hello
!
How
can
I
help
you
?

![Screenshot 2024-02-02 at 7 09 09 PM](https://github.com/vercel/ai/assets/55359171/82c2c12e-5ba0-4f43-841c-bed6c8bfe534)

But `useChat` from `ai` package stream like approx 3-4 words at a time. e.g

Hello! How
can I help
you?

https://github.com/vercel/ai/assets/55359171/faa4d18b-cd9a-457f-9b64-76c90ae070c9

is there any option I can set word streaming limit at a time?

### Use Case

For rendering smooth streaming of incoming response instead of flickering

**Comment by yuichiromukaiyama** [comment]
It seems that the Azure OpenAI API will return it that way, so is there a way to deceive it on the front-end...？

https://github.com/Azure-Samples/azure-search-openai-demo/blob/33bc5058e0e7249e78e3b0822ef3cca09d03101a/app/frontend/src/pages/chat/Chat.tsx#L84

**Comment by MaxLeiter** [comment]
You'll need to handle this with your own code, as streaming can be performance / model dependent.

**Comment by lgrammel** [comment]
## Identify issue type

Identified as **Feature**  
Confidence: **High**

### Rationale
This requests a new configuration capability for controlling streamed text chunk size rather than reporting broken promised behavior.

### Evidence
- The reporter asks for an option to limit how many words `useChat` streams at once to improve rendering smoothness.
- No documented chunk-size guarantee or existing API failure is identified.
- A maintainer states that chunking is performance/model dependent and must currently be handled with custom code.
