### ISSUE TITLE
Azure OpenAI Assistants

### ISSUE THREAD

**Issue by tsuzaki430** [vercel/ai#964]
### Feature Description

Hi,  Microsoft has released Assistants API on Azure.
I hope it will be supported on vercel ai sdk.

https://github.com/Azure/azure-sdk-for-js/blob/main/sdk/openai/openai-assistants/README.md
https://learn.microsoft.com/en-us/azure/ai-services/openai/concepts/assistants

### Use Case

I think Assistants API will be used on Azure infrastructure , same as OpenAI infrastructure.

**Comment by tsuzaki430** [comment]
Hello FingerLiu,

Thnak you for message kindly.
Actually I found get it work on Azure OpenAI Assistant Api with 'openai' package.

https://github.com/openai/openai-node/issues/701
This issue's comversation about azure assistant API in 'openai' package example.

**Comment by lgrammel** [comment]
## Identify issue type

Identified as **Feature**  
Confidence: **High**

### Rationale
This is a request to add Azure OpenAI Assistants API support, which is a new provider capability rather than a failure of existing promised behavior.

### Evidence
- The issue explicitly requests support for Microsoft's Assistants API on Azure in the Vercel AI SDK.
- The follow-up notes a workaround using the separate `openai` package, but does not identify broken or incorrect existing AI SDK behavior.
