### ISSUE TITLE
Implement onChunk() Callback to AIStreamCallbacksAndOptions and in OpenAIStream

### ISSUE THREAD

**Issue by marclelamy** [vercel/ai#994]
### Feature Description

Issue Overview:
The current `onToken()` callback in streamed responses is limited to handling completion text data, overlooking information contained within each data chunk. This limitation restricts access to non-completion text data, such as usage metrics and custom metadata, provided by various LLM API providers

Proposed Enhancement:
Introduce an onChunk callback function to enable access to all data within each chunk, not just text. Perplexity currently sends the total token count on each chunk and having an easy way to get it, specially in `OpenAIStream()`
It would be great to have onChunk() return the whole chunk as an object that we can then parse.

### Use Case

- Enables access to a wider range of data within streamed responses.
- Supports enhanced data processing and manipulation capabilities.
- Increases API flexibility to accommodate the evolving needs of LLM API providers and consumers, especially the ones relying on OpenAI library.

**Comment by lgrammel** [comment]
Outdated with the new provider architecture

**Comment by lgrammel** [comment]
## Identify issue type

Identified as **None**  
Confidence: **High**

### Rationale
Although originally a feature request, the maintainer indicates it no longer applies to the current architecture, making it an obsolete request rather than an active product enhancement.

### Evidence
- The issue requests a new `onChunk()` callback exposing complete streamed chunks and metadata beyond completion text.
- A maintainer states that the request is outdated under the new provider architecture.
